package mcp

func (s *Server) appendBuiltInOpsToolRegistrations(registry []builtInToolRegistration) []builtInToolRegistration {
	if s != nil && s.dataops != nil {
		registry = append(registry,
			mustBuiltInToolRegistration((*Server).dataopsArtifactList, builtInTool{name: "dataops.artifact.list", title: "List Data Operation Artifacts", description: "List backup, archive, export, and migration artifacts.", permission: "configuration.read"}),
			mustBuiltInToolRegistration((*Server).dataopsArtifactGet, builtInTool{name: "dataops.artifact.get", title: "Get Data Operation Artifact", description: "Get one managed data operation artifact.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"artifact_id": map[string]any{"type": "string"}}, "required": []string{"artifact_id"}}}),
			mustBuiltInToolRegistration((*Server).dataopsOperationGet, builtInTool{name: "dataops.operation.get", title: "Get Data Operation Run", description: "Get one data operation execution run.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"operation_id": map[string]any{"type": "string"}}, "required": []string{"operation_id"}}}),
			mustBuiltInToolRegistration((*Server).dataopsCheckpointList, builtInTool{name: "dataops.checkpoint.list", title: "List Data Operation Checkpoints", description: "List incremental checkpoints by adapter and data class.", permission: "configuration.read"}),
			mustBuiltInToolRegistration((*Server).dataopsBackupPlan, builtInTool{name: "dataops.backup.plan", title: "Plan Backup", description: "Plan a class-selective backup, including incremental mode.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"selected_data_classes": map[string]any{"type": "array", "items": map[string]any{"type": "string"}}, "incremental": map[string]any{"type": "boolean"}, "name": map[string]any{"type": "string"}}, "required": []string{"selected_data_classes"}}}),
			mustBuiltInToolRegistration((*Server).dataopsBackupRun, builtInTool{name: "dataops.backup.run", title: "Run Backup", description: "Run a managed backup artifact creation. Requires confirmation.", permission: "configuration.manage", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"selected_data_classes": map[string]any{"type": "array", "items": map[string]any{"type": "string"}}, "incremental": map[string]any{"type": "boolean"}, "name": map[string]any{"type": "string"}, "confirm_apply": map[string]any{"type": "boolean"}}, "required": []string{"selected_data_classes", "confirm_apply"}}}),
			mustBuiltInToolRegistration((*Server).dataopsRestorePlan, builtInTool{name: "dataops.restore.plan", title: "Plan Restore", description: "Build a restore plan from a managed backup or archive artifact.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"artifact_id": map[string]any{"type": "string"}, "selected_data_classes": map[string]any{"type": "array", "items": map[string]any{"type": "string"}}}, "required": []string{"artifact_id"}}}),
			mustBuiltInToolRegistration((*Server).dataopsRestoreValidate, builtInTool{name: "dataops.restore.validate", title: "Validate Restore", description: "Validate a restore plan without applying it.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"artifact_id": map[string]any{"type": "string"}, "selected_data_classes": map[string]any{"type": "array", "items": map[string]any{"type": "string"}}}, "required": []string{"artifact_id"}}}),
			mustBuiltInToolRegistration((*Server).dataopsRestoreRun, builtInTool{name: "dataops.restore.run", title: "Run Restore", description: "Run a class-selective restore. Requires confirmation.", permission: "configuration.manage", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"artifact_id": map[string]any{"type": "string"}, "selected_data_classes": map[string]any{"type": "array", "items": map[string]any{"type": "string"}}, "confirm_apply": map[string]any{"type": "boolean"}}, "required": []string{"artifact_id", "confirm_apply"}}}),
			mustBuiltInToolRegistration((*Server).dataopsArchivePlan, builtInTool{name: "dataops.archive.plan", title: "Plan Archive", description: "Plan a transactional archive operation.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"selected_data_classes": map[string]any{"type": "array", "items": map[string]any{"type": "string"}}, "document_types": map[string]any{"type": "array", "items": map[string]any{"type": "string"}}, "statuses": map[string]any{"type": "array", "items": map[string]any{"type": "string"}}, "organization_id": map[string]any{"type": "string"}, "location_id": map[string]any{"type": "string"}, "created_before": map[string]any{"type": "string"}, "name": map[string]any{"type": "string"}}, "required": []string{"selected_data_classes"}}}),
			mustBuiltInToolRegistration((*Server).dataopsArchiveRun, builtInTool{name: "dataops.archive.run", title: "Run Archive", description: "Archive transactional data and remove it from live storage. Requires confirmation.", permission: "configuration.manage", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"selected_data_classes": map[string]any{"type": "array", "items": map[string]any{"type": "string"}}, "document_types": map[string]any{"type": "array", "items": map[string]any{"type": "string"}}, "statuses": map[string]any{"type": "array", "items": map[string]any{"type": "string"}}, "organization_id": map[string]any{"type": "string"}, "location_id": map[string]any{"type": "string"}, "created_before": map[string]any{"type": "string"}, "name": map[string]any{"type": "string"}, "confirm_apply": map[string]any{"type": "boolean"}}, "required": []string{"selected_data_classes", "confirm_apply"}}}),
			mustBuiltInToolRegistration((*Server).dataopsExportPlan, builtInTool{name: "dataops.export.plan", title: "Plan Export", description: "Plan a structured external export by data class.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"selected_data_classes": map[string]any{"type": "array", "items": map[string]any{"type": "string"}}, "name": map[string]any{"type": "string"}}, "required": []string{"selected_data_classes"}}}),
			mustBuiltInToolRegistration((*Server).dataopsExportRun, builtInTool{name: "dataops.export.run", title: "Run Export", description: "Create a structured external export artifact. Requires confirmation.", permission: "configuration.manage", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"selected_data_classes": map[string]any{"type": "array", "items": map[string]any{"type": "string"}}, "name": map[string]any{"type": "string"}, "confirm_apply": map[string]any{"type": "boolean"}}, "required": []string{"selected_data_classes", "confirm_apply"}}}),
			mustBuiltInToolRegistration((*Server).dataopsMigrationRegister, builtInTool{name: "dataops.migration.register", title: "Register Migration Input", description: "Register structured migration input as a managed artifact.", permission: "configuration.manage", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"name": map[string]any{"type": "string"}, "selected_data_classes": map[string]any{"type": "array", "items": map[string]any{"type": "string"}}, "segments": map[string]any{"type": "array", "items": map[string]any{"type": "object"}}}, "required": []string{"selected_data_classes", "segments"}}}),
			mustBuiltInToolRegistration((*Server).dataopsMigrationPlan, builtInTool{name: "dataops.migration.plan", title: "Plan Migration", description: "Build a migration apply plan from a registered migration artifact.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"artifact_id": map[string]any{"type": "string"}, "selected_data_classes": map[string]any{"type": "array", "items": map[string]any{"type": "string"}}}, "required": []string{"artifact_id"}}}),
			mustBuiltInToolRegistration((*Server).dataopsMigrationValidate, builtInTool{name: "dataops.migration.validate", title: "Validate Migration", description: "Validate a migration artifact without applying it.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"artifact_id": map[string]any{"type": "string"}, "selected_data_classes": map[string]any{"type": "array", "items": map[string]any{"type": "string"}}}, "required": []string{"artifact_id"}}}),
			mustBuiltInToolRegistration((*Server).dataopsMigrationRun, builtInTool{name: "dataops.migration.run", title: "Run Migration", description: "Apply a validated migration artifact. Requires confirmation.", permission: "configuration.manage", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"artifact_id": map[string]any{"type": "string"}, "selected_data_classes": map[string]any{"type": "array", "items": map[string]any{"type": "string"}}, "confirm_apply": map[string]any{"type": "boolean"}}, "required": []string{"artifact_id", "confirm_apply"}}}),
		)
	}
	if s != nil && s.engagement != nil {
		registry = append(registry,
			mustBuiltInToolRegistration((*Server).engagementProgramList, builtInTool{name: "engagement.program.list", title: "List Engagement Programs", description: "List engagement programs.", permission: "configuration.read"}),
			mustBuiltInToolRegistration((*Server).engagementProgramGet, builtInTool{name: "engagement.program.get", title: "Get Engagement Program", description: "Get one engagement program.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"program_key": map[string]any{"type": "string"}}, "required": []string{"program_key"}}}),
			mustBuiltInToolRegistration((*Server).engagementProgramCreate, builtInTool{name: "engagement.program.create", title: "Create Engagement Program", description: "Create one engagement program. Requires confirmation.", permission: "configuration.manage", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"program_key": map[string]any{"type": "string"}, "name": map[string]any{"type": "string"}, "subject_type": map[string]any{"type": "string"}, "confirm_apply": map[string]any{"type": "boolean"}}, "required": []string{"program_key", "confirm_apply"}}}),
			mustBuiltInToolRegistration((*Server).engagementProgramUpdate, builtInTool{name: "engagement.program.update", title: "Update Engagement Program", description: "Update one engagement program. Requires confirmation.", permission: "configuration.manage", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"program_key": map[string]any{"type": "string"}, "name": map[string]any{"type": "string"}, "subject_type": map[string]any{"type": "string"}, "status": map[string]any{"type": "string"}, "confirm_apply": map[string]any{"type": "boolean"}}, "required": []string{"program_key", "confirm_apply"}}}),
			mustBuiltInToolRegistration((*Server).engagementVersionCreate, builtInTool{name: "engagement.program.version.create", title: "Create Engagement Draft Version", description: "Create a new draft version for an engagement program. Requires confirmation.", permission: "configuration.manage", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"program_key": map[string]any{"type": "string"}, "change_note": map[string]any{"type": "string"}, "confirm_apply": map[string]any{"type": "boolean"}}, "required": []string{"program_key", "confirm_apply"}}}),
			mustBuiltInToolRegistration((*Server).engagementVersionSave, builtInTool{name: "engagement.program.version.save", title: "Save Engagement Draft Version", description: "Save rules onto an engagement draft version. Requires confirmation.", permission: "configuration.manage", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"program_key": map[string]any{"type": "string"}, "version": map[string]any{"type": "integer"}, "rules": map[string]any{"type": "array", "items": map[string]any{"type": "object"}}, "change_note": map[string]any{"type": "string"}, "confirm_apply": map[string]any{"type": "boolean"}}, "required": []string{"program_key", "version", "rules", "confirm_apply"}}}),
			mustBuiltInToolRegistration((*Server).engagementVersionValidate, builtInTool{name: "engagement.program.version.validate", title: "Validate Engagement Version", description: "Validate one engagement program version.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"program_key": map[string]any{"type": "string"}, "version": map[string]any{"type": "integer"}}, "required": []string{"program_key", "version"}}}),
			mustBuiltInToolRegistration((*Server).engagementVersionPublish, builtInTool{name: "engagement.program.version.publish", title: "Publish Engagement Version", description: "Publish one engagement program version. Requires confirmation.", permission: "configuration.manage", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"program_key": map[string]any{"type": "string"}, "version": map[string]any{"type": "integer"}, "confirm_apply": map[string]any{"type": "boolean"}}, "required": []string{"program_key", "version", "confirm_apply"}}}),
			mustBuiltInToolRegistration((*Server).engagementSubjectGet, builtInTool{name: "engagement.subject.get", title: "Get Engagement Subject", description: "Get balances, qualification, achievements, and recent journal for one subject.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"program_key": map[string]any{"type": "string"}, "subject_id": map[string]any{"type": "string"}}, "required": []string{"program_key", "subject_id"}}}),
			mustBuiltInToolRegistration((*Server).engagementAccountList, builtInTool{name: "engagement.account.list", title: "List Engagement Accounts", description: "List accounts for one engagement subject.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"program_key": map[string]any{"type": "string"}, "subject_id": map[string]any{"type": "string"}}, "required": []string{"program_key", "subject_id"}}}),
			mustBuiltInToolRegistration((*Server).engagementBalanceGet, builtInTool{name: "engagement.balance.get", title: "Get Engagement Balance", description: "Get one engagement account balance.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"program_key": map[string]any{"type": "string"}, "subject_id": map[string]any{"type": "string"}, "account_key": map[string]any{"type": "string"}}, "required": []string{"program_key", "subject_id"}}}),
			mustBuiltInToolRegistration((*Server).engagementJournalList, builtInTool{name: "engagement.journal.list", title: "List Engagement Journal", description: "List journal entries for one program or subject.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"program_key": map[string]any{"type": "string"}, "subject_id": map[string]any{"type": "string"}, "account_key": map[string]any{"type": "string"}}, "required": []string{"program_key"}}}),
			mustBuiltInToolRegistration((*Server).engagementQualificationGet, builtInTool{name: "engagement.qualification.get", title: "Get Engagement Qualification", description: "Get qualification or tier state for one subject.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"program_key": map[string]any{"type": "string"}, "subject_id": map[string]any{"type": "string"}}, "required": []string{"program_key", "subject_id"}}}),
			mustBuiltInToolRegistration((*Server).engagementAchievementList, builtInTool{name: "engagement.achievement.list", title: "List Engagement Achievements", description: "List granted achievements for one subject.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"program_key": map[string]any{"type": "string"}, "subject_id": map[string]any{"type": "string"}}, "required": []string{"program_key", "subject_id"}}}),
			mustBuiltInToolRegistration((*Server).engagementConsumerList, builtInTool{name: "engagement.consumer.list", title: "List Engagement Consumers", description: "List engagement consumer state.", permission: "configuration.read"}),
			mustBuiltInToolRegistration((*Server).engagementConsumerGet, builtInTool{name: "engagement.consumer.get", title: "Get Engagement Consumer", description: "Get one engagement consumer state.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"consumer_id": map[string]any{"type": "string"}}, "required": []string{"consumer_id"}}}),
			mustBuiltInToolRegistration((*Server).engagementReplayPlan, builtInTool{name: "engagement.replay.plan", title: "Plan Engagement Replay", description: "Plan a replay for one engagement program version.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"program_key": map[string]any{"type": "string"}, "version": map[string]any{"type": "integer"}}, "required": []string{"program_key"}}}),
			mustBuiltInToolRegistration((*Server).engagementReplayRun, builtInTool{name: "engagement.replay.run", title: "Run Engagement Replay", description: "Queue a replay for one engagement program version. Requires confirmation.", permission: "configuration.manage", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"program_key": map[string]any{"type": "string"}, "version": map[string]any{"type": "integer"}, "confirm_apply": map[string]any{"type": "boolean"}}, "required": []string{"program_key", "confirm_apply"}}}),
			mustBuiltInToolRegistration((*Server).engagementReplayGet, builtInTool{name: "engagement.replay.get", title: "Get Engagement Replay", description: "Get one engagement replay run.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"replay_run_id": map[string]any{"type": "string"}}, "required": []string{"replay_run_id"}}}),
			mustBuiltInToolRegistration((*Server).engagementSimulationRun, builtInTool{name: "engagement.simulation.run", title: "Simulate Engagement Rules", description: "Preview engagement rule outcomes for one event.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"program_key": map[string]any{"type": "string"}, "version": map[string]any{"type": "integer"}, "event": map[string]any{"type": "object"}}, "required": []string{"program_key", "event"}}}),
		)
	}
	if s != nil && (s.health != nil || s.audit != nil) {
		registry = append(registry,
			mustBuiltInToolRegistration((*Server).readinessGet, builtInTool{name: "readiness.get", title: "Get Implementation Readiness", description: "Get readiness for applying customer configuration.", permission: "configuration.read"}),
			mustBuiltInToolRegistration((*Server).opsHealthGet, builtInTool{name: "ops.health.get", title: "Get Runtime Health", description: "Get runtime health snapshot and subsystem status.", permission: "ops.read"}),
			mustBuiltInToolRegistration((*Server).opsAuditCorrelationGet, builtInTool{name: "ops.audit.correlation.get", title: "Get Audit Events By Correlation", description: "Get correlated audit events for one correlation id.", permission: "ops.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"correlation_id": map[string]any{"type": "string"}}, "required": []string{"correlation_id"}}}),
			mustBuiltInToolRegistration((*Server).opsTraceGet, builtInTool{name: "ops.trace.get", title: "Get Operational Trace", description: "Get a stitched trace summary for one correlation id.", permission: "ops.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"correlation_id": map[string]any{"type": "string"}}, "required": []string{"correlation_id"}}}),
		)
	}
	if s != nil && s.config != nil {
		registry = append(registry,
			mustBuiltInToolRegistration((*Server).implementationTenantInspect, builtInTool{name: "implementation.tenant.inspect", title: "Inspect Tenant Implementation State", description: "Aggregate config, flags, modules, integrations, and readiness for implementation work.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"organization_id": map[string]any{"type": "string"}, "location_id": map[string]any{"type": "string"}, "operating_unit_id": map[string]any{"type": "string"}}}}),
			mustBuiltInToolRegistration((*Server).implementationConfigPlan, builtInTool{name: "implementation.config.plan", title: "Plan Implementation Config Changes", description: "Dry-run desired config, flags, and role grants into a normalized plan.", permission: "configuration.manage", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"bundle": map[string]any{"type": "object"}, "role_grants": map[string]any{"type": "array", "items": map[string]any{"type": "object"}}}}}),
			mustBuiltInToolRegistration((*Server).implementationConfigApply, builtInTool{name: "implementation.config.apply", title: "Apply Implementation Plan", description: "Apply a validated implementation plan. Requires confirmation.", permission: "configuration.manage", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"bundle": map[string]any{"type": "object"}, "role_grants": map[string]any{"type": "array", "items": map[string]any{"type": "object"}}, "confirm_apply": map[string]any{"type": "boolean"}}, "required": []string{"confirm_apply"}}}),
			mustBuiltInToolRegistration((*Server).implementationReadinessCheck, builtInTool{name: "implementation.readiness.check", title: "Check Implementation Readiness", description: "Return readiness, validation warnings, and operator hints before apply.", permission: "configuration.read"}),
			mustBuiltInToolRegistration((*Server).implementationRollbackInspect, builtInTool{name: "implementation.rollback.inspect", title: "Inspect Recent Implementation Changes", description: "Inspect recent config, feature flag, RBAC, and integration audit trail for rollback planning.", permission: "configuration.read"}),
			mustBuiltInToolRegistration((*Server).implementationSessionCreate, builtInTool{name: "implementation.session.create", title: "Create Implementation Session", description: "Create an implementation session for staged rollout work.", permission: "configuration.manage", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"name": map[string]any{"type": "string"}, "organization_id": map[string]any{"type": "string"}, "location_id": map[string]any{"type": "string"}, "operating_unit_id": map[string]any{"type": "string"}}}}),
			mustBuiltInToolRegistration((*Server).implementationSessionList, builtInTool{name: "implementation.session.list", title: "List Implementation Sessions", description: "List implementation sessions.", permission: "configuration.read"}),
			mustBuiltInToolRegistration((*Server).implementationSessionGet, builtInTool{name: "implementation.session.get", title: "Get Implementation Session", description: "Get one implementation session.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"session_id": map[string]any{"type": "string"}}, "required": []string{"session_id"}}}),
			mustBuiltInToolRegistration((*Server).implementationSessionClose, builtInTool{name: "implementation.session.close", title: "Close Implementation Session", description: "Close one implementation session. Requires confirmation.", permission: "configuration.manage", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"session_id": map[string]any{"type": "string"}, "confirm_apply": map[string]any{"type": "boolean"}}, "required": []string{"session_id", "confirm_apply"}}}),
			mustBuiltInToolRegistration((*Server).implementationPlanBuild, builtInTool{name: "implementation.plan.build", title: "Build Implementation Plan", description: "Stage a normalized implementation plan onto a session.", permission: "configuration.manage", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"session_id": map[string]any{"type": "string"}, "plan": map[string]any{"type": "object"}}, "required": []string{"session_id"}}}),
			mustBuiltInToolRegistration((*Server).implementationPlanValidate, builtInTool{name: "implementation.plan.validate", title: "Validate Implementation Plan", description: "Validate the currently staged implementation plan for a session.", permission: "configuration.manage", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"session_id": map[string]any{"type": "string"}}, "required": []string{"session_id"}}}),
			mustBuiltInToolRegistration((*Server).implementationStageDiff, builtInTool{name: "implementation.stage.diff", title: "Diff Staged Implementation", description: "Compare staged session changes against current runtime state.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"session_id": map[string]any{"type": "string"}}, "required": []string{"session_id"}}}),
			mustBuiltInToolRegistration((*Server).implementationStageDiscard, builtInTool{name: "implementation.stage.discard", title: "Discard Staged Implementation", description: "Discard the staged plan for a session. Requires confirmation.", permission: "configuration.manage", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"session_id": map[string]any{"type": "string"}, "confirm_apply": map[string]any{"type": "boolean"}}, "required": []string{"session_id", "confirm_apply"}}}),
			mustBuiltInToolRegistration((*Server).implementationStageCommit, builtInTool{name: "implementation.stage.commit", title: "Commit Staged Implementation", description: "Apply the staged plan and record a change-set. Requires confirmation.", permission: "configuration.manage", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"session_id": map[string]any{"type": "string"}, "confirm_apply": map[string]any{"type": "boolean"}}, "required": []string{"session_id", "confirm_apply"}}}),
			mustBuiltInToolRegistration((*Server).implementationVerifyState, builtInTool{name: "implementation.verify.state", title: "Verify Implementation State", description: "Verify current runtime state for a session or context.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"session_id": map[string]any{"type": "string"}, "organization_id": map[string]any{"type": "string"}, "location_id": map[string]any{"type": "string"}, "operating_unit_id": map[string]any{"type": "string"}}}}),
			mustBuiltInToolRegistration((*Server).implementationVerifyReadiness, builtInTool{name: "implementation.verify.readiness", title: "Verify Implementation Readiness", description: "Verify readiness and runtime validity for a session or context.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"session_id": map[string]any{"type": "string"}, "organization_id": map[string]any{"type": "string"}, "location_id": map[string]any{"type": "string"}, "operating_unit_id": map[string]any{"type": "string"}}}}),
			mustBuiltInToolRegistration((*Server).implementationVerifyDiff, builtInTool{name: "implementation.verify.diff", title: "Verify Implementation Diff", description: "Return the staged diff for verification workflows.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"session_id": map[string]any{"type": "string"}}, "required": []string{"session_id"}}}),
			mustBuiltInToolRegistration((*Server).implementationVerifySmoke, builtInTool{name: "implementation.verify.smoke", title: "Smoke Verify Implementation", description: "Run a high-signal verification sweep for a session or context.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"session_id": map[string]any{"type": "string"}, "organization_id": map[string]any{"type": "string"}, "location_id": map[string]any{"type": "string"}, "operating_unit_id": map[string]any{"type": "string"}}}}),
			mustBuiltInToolRegistration((*Server).implementationCheckpointCreate, builtInTool{name: "implementation.checkpoint.create", title: "Create Implementation Checkpoint", description: "Create a checkpoint tied to the latest committed change-set.", permission: "configuration.manage", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"session_id": map[string]any{"type": "string"}, "name": map[string]any{"type": "string"}}, "required": []string{"session_id"}}}),
			mustBuiltInToolRegistration((*Server).implementationCheckpointList, builtInTool{name: "implementation.checkpoint.list", title: "List Implementation Checkpoints", description: "List checkpoints for a session.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"session_id": map[string]any{"type": "string"}}, "required": []string{"session_id"}}}),
			mustBuiltInToolRegistration((*Server).implementationCheckpointRestore, builtInTool{name: "implementation.checkpoint.restore", title: "Restore Implementation Checkpoint", description: "Apply rollback for a checkpoint when reversible. Requires confirmation.", permission: "configuration.manage", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"session_id": map[string]any{"type": "string"}, "checkpoint_id": map[string]any{"type": "string"}, "confirm_apply": map[string]any{"type": "boolean"}}, "required": []string{"session_id", "checkpoint_id", "confirm_apply"}}}),
			mustBuiltInToolRegistration((*Server).implementationRollbackPlan, builtInTool{name: "implementation.rollback.plan", title: "Plan Implementation Rollback", description: "Build a rollback plan for a change-set.", permission: "configuration.read", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"session_id": map[string]any{"type": "string"}, "change_set_id": map[string]any{"type": "string"}}, "required": []string{"session_id"}}}),
			mustBuiltInToolRegistration((*Server).implementationRollbackApply, builtInTool{name: "implementation.rollback.apply", title: "Apply Implementation Rollback", description: "Apply a reversible rollback plan. Requires confirmation.", permission: "configuration.manage", inputSchema: map[string]any{"type": "object", "properties": map[string]any{"session_id": map[string]any{"type": "string"}, "change_set_id": map[string]any{"type": "string"}, "confirm_apply": map[string]any{"type": "boolean"}}, "required": []string{"session_id", "confirm_apply"}}}),
		)
	}
	return registry
}
