package app

import (
	"orbyte/internal/platform/document"
	"orbyte/internal/platform/module"
	"orbyte/internal/platform/search"
	"orbyte/internal/platform/workflow"
)

func documentsKernelPackManifest() module.Manifest {
	return module.Manifest{
		Key:          "documents",
		Name:         "Document Kernel",
		NameI18n:     localize("Document Kernel", "Kernel Dokumen"),
		Version:      "1.1.0",
		DomainFamily: "platform",
		DependencyRequirements: []module.DependencyRequirement{
			{ModuleKey: "platform.core", VersionRange: ">=1.0.0,<2.0.0", Kind: module.DependencyKindRequired},
			{ModuleKey: "identity", VersionRange: ">=1.0.0,<2.0.0", Kind: module.DependencyKindRequired},
		},
		OwnedDocumentTypes: []string{"generic_request"},
		OwnedWorkflowKeys:  []string{"generic_request_flow"},
		AdminConsole: module.AdminConsoleDefinition{
			Title:           "Documents Console",
			TitleI18n:       localize("Documents Console", "Konsol Dokumen"),
			Description:     "Request operations, worklist entry points, workflow controls, and document templates.",
			DescriptionI18n: localize("Request operations, worklist entry points, workflow controls, and document templates.", "Operasi permintaan, pintu masuk worklist, kontrol workflow, dan template dokumen."),
			Sections: []module.AdminConsoleSectionDefinition{
				{
					Key:       "document_operations",
					Title:     "Document Operations",
					TitleI18n: localize("Document Operations", "Operasi Dokumen"),
					Kind:      module.AdminConsoleSectionResourceLinks,
					Links: []module.AdminConsoleLinkDefinition{
						adminConsoleLink("requests", "Requests", "Permintaan", "/ui/documents", "Open document requests.", "Buka permintaan dokumen.", "document.list"),
						adminConsoleLink("new_request", "New Request", "Permintaan Baru", "/ui/documents/new", "Create a new request.", "Buat permintaan baru.", "document.create"),
						adminConsoleLink("worklist", "Worklist", "Antrian Kerja", "/ui/worklist", "Open the worklist.", "Buka antrian kerja.", "document.list"),
						adminConsoleLink("self_service", "Self-Service Requests", "Permintaan Self-Service", "/ui/self-service/requests", "Open self-service requests.", "Buka permintaan self-service.", "document.list"),
					},
				},
				{
					Key:       "document_workflows",
					Title:     "Document Workflows",
					TitleI18n: localize("Document Workflows", "Workflow Dokumen"),
					Kind:      module.AdminConsoleSectionWorkflowLinks,
					Links: []module.AdminConsoleLinkDefinition{
						adminConsoleLink("generic_request_flow", "Generic Request Workflow", "Workflow Permintaan Generik", "/admin/workflows/designer?key=generic_request_flow", "Open the generic request workflow.", "Buka workflow permintaan generik.", "configuration.read"),
					},
				},
			},
		},
		Documents: []document.Definition{{
			Type:                   "generic_request",
			DisplayName:            "Generic Request",
			SchemaVersion:          "v1",
			WorkflowKey:            "generic_request_flow",
			NumberingKey:           "generic_request_number",
			OwnerModuleKey:         "documents",
			AllowedLinkTypes:       []string{"related_to", "amends"},
			AllowedAttachmentTypes: []string{"note", "image", "document"},
		}},
		Workflows: []workflow.Definition{{
			Key:    "generic_request_flow",
			States: []string{"draft", "submitted", "approved", "rejected", "cancelled"},
			Actions: []workflow.ActionRule{
				{Action: "submit", FromState: "draft", ToState: "submitted", PermissionKey: "document.submit", TaskType: "review", CreateApproval: true, LinkMode: "tokenized", LinkTTLSeconds: 24 * 60 * 60, LinkAllowedActions: []string{"approve", "reject"}},
				{Action: "approve", FromState: "submitted", ToState: "approved", PermissionKey: "document.approve"},
				{Action: "reject", FromState: "submitted", ToState: "rejected", PermissionKey: "document.reject"},
				{Action: "reopen", FromState: "rejected", ToState: "draft", PermissionKey: "document.reopen"},
				{Action: "reopen", FromState: "approved", ToState: "draft", PermissionKey: "document.reopen"},
				{Action: "cancel", FromState: "draft", ToState: "cancelled", PermissionKey: "document.cancel"},
				{Action: "cancel", FromState: "submitted", ToState: "cancelled", PermissionKey: "document.cancel"},
			},
		}},
		Security: module.SecurityDefinition{
			Permissions: []module.PermissionDefinition{
				{Key: "document.create", Action: "create", Resource: "document", DisplayName: "Create Documents", DisplayNameI18n: localize("Create Documents", "Buat Dokumen")},
				{Key: "document.list", Action: "list", Resource: "document", DisplayName: "List Documents", DisplayNameI18n: localize("List Documents", "Daftar Dokumen")},
				{Key: "document.read", Action: "read", Resource: "document", DisplayName: "Read Documents", DisplayNameI18n: localize("Read Documents", "Lihat Dokumen")},
				{Key: "document.update_draft", Action: "update_draft", Resource: "document", DisplayName: "Update Draft Documents", DisplayNameI18n: localize("Update Draft Documents", "Perbarui Dokumen Draf")},
				{Key: "document.submit", Action: "submit", Resource: "document", DisplayName: "Submit Documents", DisplayNameI18n: localize("Submit Documents", "Ajukan Dokumen")},
				{Key: "document.approve", Action: "approve", Resource: "document", DisplayName: "Approve Documents", DisplayNameI18n: localize("Approve Documents", "Setujui Dokumen"), RiskLevel: "medium"},
				{Key: "document.reject", Action: "reject", Resource: "document", DisplayName: "Reject Documents", DisplayNameI18n: localize("Reject Documents", "Tolak Dokumen"), RiskLevel: "medium"},
				{Key: "document.reopen", Action: "reopen", Resource: "document", DisplayName: "Reopen Documents", DisplayNameI18n: localize("Reopen Documents", "Buka Ulang Dokumen"), RiskLevel: "high"},
				{Key: "document.cancel", Action: "cancel", Resource: "document", DisplayName: "Cancel Documents", DisplayNameI18n: localize("Cancel Documents", "Batalkan Dokumen"), RiskLevel: "high"},
			},
			RoleTemplates: []module.RoleTemplateDefinition{
				{
					Key:            "document_clerk",
					Name:           "Document Clerk",
					NameI18n:       localize("Document Clerk", "Petugas Dokumen"),
					AllowedScopes:  []string{"location"},
					PermissionKeys: []string{"document.create", "document.list", "document.read", "document.update_draft", "document.submit"},
				},
				{
					Key:            "document_reviewer",
					Name:           "Document Reviewer",
					NameI18n:       localize("Document Reviewer", "Peninjau Dokumen"),
					AllowedScopes:  []string{"location"},
					PermissionKeys: []string{"document.list", "document.read", "document.approve", "document.reject", "document.reopen", "document.cancel"},
				},
			},
			PolicyHooks: []module.PolicyHookDefinition{
				{Key: "documents.extension.view", Kind: "access", Target: "document_extension_view", InputContractKey: "document.extension.access.v1", OutputContractKey: "decision.v1", Description: "Controls extension visibility in expanded/raw document reads."},
				{Key: "documents.extension.write", Kind: "access", Target: "document_extension_write", InputContractKey: "document.extension.access.v1", OutputContractKey: "decision.v1", Description: "Controls extension writes for draft documents."},
				{Key: "documents.workflow.transition", Kind: "workflow", Target: "document_transition", InputContractKey: "document.transition.v1", OutputContractKey: "decision.v1", Description: "Controls workflow transitions before they are committed."},
				{Key: "documents.workflow.assignment", Kind: "workflow", Target: "document_assignment", InputContractKey: "document.assignment.v1", OutputContractKey: "decision.v1", Description: "Controls workflow assignment before side effects are persisted."},
				{Key: "documents.workflow.sla", Kind: "workflow", Target: "document_sla", InputContractKey: "document.sla.v1", OutputContractKey: "decision.v1", Description: "Controls workflow task due and escalation timing before side effects are persisted."},
				{Key: "documents.search.visibility", Kind: "search", Target: "document_search", InputContractKey: "document.search.v1", OutputContractKey: "decision.v1", Description: "Controls document visibility in search and list views."},
				{Key: "documents.numbering.assign", Kind: "numbering", Target: "document_numbering", InputContractKey: "document.numbering.v1", OutputContractKey: "decision.v1", Description: "Assigns document numbers when numbering is policy-bound."},
				{Key: "documents.action.render", Kind: "ui", Target: "document_action_render", InputContractKey: "document.action.render.v1", OutputContractKey: "decision.v1", Description: "Controls action placement and visibility in generic detail views."},
			},
		},
		Observability: module.ObservabilityDefinition{
			Projections: []module.ProjectionDefinition{{
				Key: "document_summary", SourceEventTypes: []string{"document.updated", "document.submitted", "document.approved", "document.reject", "document.reopened", "document.cancelled"}, RefreshMode: "event_driven",
			}},
			DomainEvents: []module.DomainEventDefinition{
				{Type: "document.updated", Role: "producer", CorrelationRequired: true},
				{Type: "document.submitted", Role: "producer", CorrelationRequired: true, ExternalPublish: true, Topic: "documents.lifecycle.submitted", SchemaVersion: "v1"},
				{Type: "document.approved", Role: "producer", CorrelationRequired: true, ExternalPublish: true, Topic: "documents.lifecycle.approved", SchemaVersion: "v1"},
				{Type: "document.reject", Role: "producer", CorrelationRequired: true},
				{Type: "document.reopened", Role: "producer", CorrelationRequired: true},
				{Type: "document.cancelled", Role: "producer", CorrelationRequired: true},
				{Type: "document.extension.updated", Role: "producer", CorrelationRequired: true},
			},
			Metrics: []module.MetricDefinition{
				{Key: "document.actions.total", Type: "counter", Labels: []string{"action", "outcome"}},
			},
			LogEvents: []module.LogEventDefinition{{
				Key: "document.action", Category: "document", Severity: "info", RequiredFields: []string{"document_id", "action", "actor_id"},
			}},
		},
		SelfService: module.SelfServiceDefinition{
			APIs: []module.SelfServiceAPIDefinition{
				{
					Key:                 "documents.self_service.requests.list",
					Title:               "List Self-Service Requests",
					TitleI18n:           localize("List Self-Service Requests", "Daftar Permintaan Self-Service"),
					Method:              "GET",
					RoutePath:           "/ui/data/documents?type=generic_request",
					HandlerKind:         "ui_data",
					DocumentType:        "generic_request",
					RequiredPermissions: []string{"document.list"},
					AudienceKinds:       []string{"customer", "employee", "patient"},
					ResponseContractKey: "documents.generic_request.list",
				},
				{
					Key:                 "documents.self_service.requests.get",
					Title:               "Get Self-Service Request",
					TitleI18n:           localize("Get Self-Service Request", "Lihat Permintaan Self-Service"),
					Method:              "GET",
					RoutePath:           "/ui/data/documents/{documentID}",
					HandlerKind:         "ui_data",
					DocumentType:        "generic_request",
					RequiredPermissions: []string{"document.read"},
					AudienceKinds:       []string{"customer", "employee", "patient"},
					ResponseContractKey: "documents.generic_request.detail",
				},
				{
					Key:                 "documents.self_service.requests.create",
					Title:               "Create Self-Service Request",
					TitleI18n:           localize("Create Self-Service Request", "Buat Permintaan Self-Service"),
					Method:              "POST",
					RoutePath:           "/document-flows/documents.self_service.requests.intake/commit",
					HandlerKind:         "flow_commit",
					DocumentType:        "generic_request",
					FlowKey:             "documents.self_service.requests.intake",
					RequiredPermissions: []string{"document.create"},
					AudienceKinds:       []string{"customer", "employee", "patient"},
					RequestContractKey:  "documents.generic_request.create",
					ResponseContractKey: "documents.generic_request.detail",
					Idempotent:          true,
				},
				{
					Key:                 "documents.self_service.requests.submit",
					Title:               "Submit Self-Service Request",
					TitleI18n:           localize("Submit Self-Service Request", "Ajukan Permintaan Self-Service"),
					Method:              "POST",
					RoutePath:           "/documents/{documentID}/actions",
					HandlerKind:         "document_action",
					DocumentType:        "generic_request",
					RequiredPermissions: []string{"document.submit"},
					AudienceKinds:       []string{"customer", "employee", "patient"},
					RequestContractKey:  "documents.generic_request.action.submit",
					ResponseContractKey: "documents.generic_request.detail",
					Idempotent:          true,
				},
			},
		},
		Frontend: module.FrontendDefinition{
			Menus: []module.MenuDefinition{{
				Key:                 "documents.requests",
				Label:               "Requests",
				LabelI18n:           localize("Requests", "Permintaan"),
				ActionKey:           "documents.requests.list",
				Order:               10,
				RequiredPermissions: []string{"document.list"},
			}, {
				Key:                 "documents.self_service.requests",
				Label:               "My Requests",
				LabelI18n:           localize("My Requests", "Permintaan Saya"),
				Surface:             module.UISurfaceSelfService,
				ActionKey:           "documents.self_service.requests.list",
				Order:               8,
				RequiredPermissions: []string{"document.list"},
			}, {
				Key:                 "documents.worklist",
				Label:               "Worklist",
				LabelI18n:           localize("Worklist", "Antrian Kerja"),
				Surface:             module.UISurfaceWorklist,
				ActionKey:           "documents.worklist.tasks",
				Order:               5,
				RequiredPermissions: []string{"document.list"},
			}},
			Actions: []module.ActionDefinition{
				{
					Key:                 "documents.requests.create",
					Label:               "New Request",
					LabelI18n:           localize("New Request", "Permintaan Baru"),
					Kind:                "navigate",
					RoutePath:           "/documents/new",
					FlowKey:             "documents.requests.intake",
					RenderMode:          module.RenderModeFlow,
					RequiredPermissions: []string{"document.create"},
				},
				{
					Key:                 "documents.requests.list",
					Label:               "Requests",
					LabelI18n:           localize("Requests", "Permintaan"),
					Kind:                "navigate",
					RoutePath:           "/documents",
					ViewKey:             "documents.requests.list",
					RenderMode:          module.RenderModeGeneric,
					RequiredPermissions: []string{"document.list"},
				},
				{
					Key:                 "documents.requests.detail",
					Label:               "Request Detail",
					LabelI18n:           localize("Request Detail", "Detail Permintaan"),
					Kind:                "navigate",
					RoutePath:           "/documents/detail",
					ViewKey:             "documents.requests.detail",
					RenderMode:          module.RenderModeGeneric,
					RequiredPermissions: []string{"document.read"},
				},
				{
					Key:                 "documents.requests.form",
					Label:               "Request Draft",
					LabelI18n:           localize("Request Draft", "Draf Permintaan"),
					Kind:                "navigate",
					RoutePath:           "/documents/form",
					ViewKey:             "documents.requests.form",
					RenderMode:          module.RenderModeGeneric,
					RequiredPermissions: []string{"document.update_draft"},
				},
				{
					Key:                 "documents.self_service.requests.create",
					Label:               "New Request",
					LabelI18n:           localize("New Request", "Permintaan Baru"),
					Surface:             module.UISurfaceSelfService,
					Kind:                "navigate",
					RoutePath:           "/self-service/requests/new",
					FlowKey:             "documents.self_service.requests.intake",
					RenderMode:          module.RenderModeFlow,
					RequiredPermissions: []string{"document.create"},
				},
				{
					Key:                 "documents.self_service.requests.list",
					Label:               "My Requests",
					LabelI18n:           localize("My Requests", "Permintaan Saya"),
					Surface:             module.UISurfaceSelfService,
					Kind:                "navigate",
					RoutePath:           "/self-service/requests",
					ViewKey:             "documents.self_service.requests.list",
					RenderMode:          module.RenderModeGeneric,
					RequiredPermissions: []string{"document.list"},
				},
				{
					Key:                 "documents.self_service.requests.detail",
					Label:               "Request Detail",
					LabelI18n:           localize("Request Detail", "Detail Permintaan"),
					Surface:             module.UISurfaceSelfService,
					Kind:                "navigate",
					RoutePath:           "/self-service/requests/detail",
					ViewKey:             "documents.self_service.requests.detail",
					RenderMode:          module.RenderModeGeneric,
					RequiredPermissions: []string{"document.read"},
				},
				{
					Key:                 "documents.self_service.requests.form",
					Label:               "Request Draft",
					LabelI18n:           localize("Request Draft", "Draf Permintaan"),
					Surface:             module.UISurfaceSelfService,
					Kind:                "navigate",
					RoutePath:           "/self-service/requests/form",
					ViewKey:             "documents.self_service.requests.form",
					RenderMode:          module.RenderModeGeneric,
					RequiredPermissions: []string{"document.update_draft"},
				},
				{
					Key:                 "documents.worklist.tasks",
					Label:               "Task Queue",
					LabelI18n:           localize("Task Queue", "Antrian Tugas"),
					Surface:             module.UISurfaceWorklist,
					Kind:                "navigate",
					RoutePath:           "/worklist",
					ViewKey:             "documents.worklist.tasks",
					RenderMode:          module.RenderModeGeneric,
					RequiredPermissions: []string{"document.list"},
				},
				{
					Key:                 "documents.worklist.approvals",
					Label:               "Approval Queue",
					LabelI18n:           localize("Approval Queue", "Antrian Persetujuan"),
					Surface:             module.UISurfaceWorklist,
					Kind:                "navigate",
					RoutePath:           "/worklist/approvals",
					ViewKey:             "documents.worklist.approvals",
					RenderMode:          module.RenderModeGeneric,
					RequiredPermissions: []string{"document.list"},
				},
			},
			Views: []module.ViewDefinition{
				{
					Key:                 "documents.requests.list",
					Title:               "Requests",
					TitleI18n:           localize("Requests", "Permintaan"),
					Kind:                "list",
					DocumentType:        "generic_request",
					ProjectionKey:       "document_summary",
					RequiredPermissions: []string{"document.list"},
					Columns: []module.ColumnDefinition{
						{Key: "id", Label: "Document", LabelI18n: localize("Document", "Dokumen"), Path: "header.id"},
						{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "header.status"},
						{Key: "updated_at", Label: "Updated", LabelI18n: localize("Updated", "Diperbarui"), Path: "header.updated_at"},
					},
					Filters: []module.FilterDefinition{
						{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Type: "enum", Options: []string{"draft", "submitted", "approved", "rejected", "cancelled"}},
					},
					DefaultPageSize: 10,
					EmptyState:      "No governed request documents exist yet.",
					EmptyStateI18n:  localize("No governed request documents exist yet.", "Belum ada dokumen permintaan yang dikelola."),
				},
				{
					Key:                 "documents.requests.detail",
					Title:               "Request Detail",
					TitleI18n:           localize("Request Detail", "Detail Permintaan"),
					Kind:                "detail",
					DocumentType:        "generic_request",
					Printable:           true,
					PrintPurpose:        "official",
					PrintChannel:        "print",
					RequiredPermissions: []string{"document.read"},
					AllowedActions:      []string{"submit", "approve", "reject", "reopen", "cancel"},
					Tabs: []module.TabDefinition{
						{
							Key:       "summary",
							Title:     "Summary",
							TitleI18n: localize("Summary", "Ringkasan"),
							Sections: []module.SectionDefinition{
								{
									Key:       "header",
									Title:     "Header",
									TitleI18n: localize("Header", "Header"),
									Fields: []module.FieldDefinition{
										{Key: "doc_id", Label: "Document ID", LabelI18n: localize("Document ID", "ID Dokumen"), Path: "header.id", Type: "string", ReadOnly: true},
										{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "header.status", Type: "string", ReadOnly: true},
										{Key: "updated_by", Label: "Updated By", LabelI18n: localize("Updated By", "Diperbarui Oleh"), Path: "header.updated_by", Type: "string", ReadOnly: true},
									},
								},
								{
									Key:       "payload",
									Title:     "Payload",
									TitleI18n: localize("Payload", "Payload"),
									Fields: []module.FieldDefinition{
										{Key: "title", Label: "Title", LabelI18n: localize("Title", "Judul"), Path: "body.payload.title", Type: "string"},
									},
								},
							},
						},
						{
							Key:       "extensions",
							Title:     "Extensions",
							TitleI18n: localize("Extensions", "Ekstensi"),
							Sections: []module.SectionDefinition{{
								Key: "analytics_extension", Title: "Analytics Extension", TitleI18n: localize("Analytics Extension", "Ekstensi Analitik"), ExtensionSlotKey: "analytics",
							}},
						},
					},
					RelatedViews: []module.RelatedViewDefinition{
						{Key: "lines", Title: "Lines", TitleI18n: localize("Lines", "Baris"), Source: "lines", EmptyState: "No lines", EmptyStateI18n: localize("No lines", "Belum ada baris")},
						{Key: "links", Title: "Links", TitleI18n: localize("Links", "Tautan"), Source: "links", EmptyState: "No links", EmptyStateI18n: localize("No links", "Belum ada tautan")},
						{Key: "attachments", Title: "Attachments", TitleI18n: localize("Attachments", "Lampiran"), Source: "attachments", EmptyState: "No attachments", EmptyStateI18n: localize("No attachments", "Belum ada lampiran")},
					},
					ActionPlacements: []module.ActionPlacementDefinition{
						{ActionKey: "submit", Zone: "primary"},
						{ActionKey: "approve", Zone: "primary"},
						{ActionKey: "reject", Zone: "secondary", Style: "warn"},
						{ActionKey: "reopen", Zone: "secondary"},
						{ActionKey: "cancel", Zone: "secondary", Style: "warn"},
					},
				},
				{
					Key:                 "documents.self_service.requests.list",
					Title:               "My Requests",
					TitleI18n:           localize("My Requests", "Permintaan Saya"),
					Surface:             module.UISurfaceSelfService,
					Kind:                "list",
					DocumentType:        "generic_request",
					ProjectionKey:       "document_summary",
					RequiredPermissions: []string{"document.list"},
					Columns: []module.ColumnDefinition{
						{Key: "id", Label: "Request", LabelI18n: localize("Request", "Permintaan"), Path: "header.id"},
						{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "header.status"},
						{Key: "updated_at", Label: "Updated", LabelI18n: localize("Updated", "Diperbarui"), Path: "header.updated_at"},
					},
					Filters: []module.FilterDefinition{
						{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Type: "enum", Options: []string{"draft", "submitted", "approved", "rejected", "cancelled"}},
					},
					DefaultPageSize: 10,
					EmptyState:      "No self-service requests yet.",
					EmptyStateI18n:  localize("No self-service requests yet.", "Belum ada permintaan self-service."),
				},
				{
					Key:                 "documents.self_service.requests.detail",
					Title:               "My Request",
					TitleI18n:           localize("My Request", "Permintaan Saya"),
					Surface:             module.UISurfaceSelfService,
					Kind:                "detail",
					DocumentType:        "generic_request",
					RequiredPermissions: []string{"document.read"},
					AllowedActions:      []string{"submit", "reopen", "cancel"},
					Tabs: []module.TabDefinition{
						{
							Key:       "summary",
							Title:     "Summary",
							TitleI18n: localize("Summary", "Ringkasan"),
							Sections: []module.SectionDefinition{
								{
									Key:       "header",
									Title:     "Header",
									TitleI18n: localize("Header", "Header"),
									Fields: []module.FieldDefinition{
										{Key: "doc_id", Label: "Request ID", LabelI18n: localize("Request ID", "ID Permintaan"), Path: "header.id", Type: "string", ReadOnly: true},
										{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "header.status", Type: "string", ReadOnly: true},
									},
								},
								{
									Key:       "payload",
									Title:     "Payload",
									TitleI18n: localize("Payload", "Payload"),
									Fields: []module.FieldDefinition{
										{Key: "title", Label: "Title", LabelI18n: localize("Title", "Judul"), Path: "body.payload.title", Type: "string", ReadOnly: true},
									},
								},
							},
						},
					},
					ActionPlacements: []module.ActionPlacementDefinition{
						{ActionKey: "submit", Zone: "primary"},
						{ActionKey: "reopen", Zone: "secondary"},
						{ActionKey: "cancel", Zone: "secondary", Style: "warn"},
					},
				},
				{
					Key:                 "documents.self_service.requests.form",
					Title:               "Request Form",
					TitleI18n:           localize("Request Form", "Form Permintaan"),
					Surface:             module.UISurfaceSelfService,
					Kind:                "form",
					DocumentType:        "generic_request",
					RequiredPermissions: []string{"document.update_draft"},
					Sections: []module.SectionDefinition{{
						Key: "request_fields", Title: "Request", TitleI18n: localize("Request", "Permintaan"), Fields: []module.FieldDefinition{
							{Key: "title", Label: "Title", LabelI18n: localize("Title", "Judul"), Path: "body.payload.title", Type: "string", Widget: "textarea", Placeholder: "Describe your request", PlaceholderI18n: localize("Describe your request", "Jelaskan permintaan Anda"), Required: true, MinLength: 5, MaxLength: 280},
						},
					}},
				},
				{
					Key:                 "documents.worklist.tasks",
					Title:               "Task Queue",
					TitleI18n:           localize("Task Queue", "Antrian Tugas"),
					Surface:             module.UISurfaceWorklist,
					Kind:                "queue",
					ProjectionKey:       "workflow.tasks",
					RequiredPermissions: []string{"document.list"},
					EmptyState:          "No open workflow tasks.",
					EmptyStateI18n:      localize("No open workflow tasks.", "Belum ada tugas workflow terbuka."),
				},
				{
					Key:                 "documents.worklist.approvals",
					Title:               "Approval Queue",
					TitleI18n:           localize("Approval Queue", "Antrian Persetujuan"),
					Surface:             module.UISurfaceWorklist,
					Kind:                "queue",
					ProjectionKey:       "workflow.approvals",
					RequiredPermissions: []string{"document.list"},
					EmptyState:          "No pending workflow approvals.",
					EmptyStateI18n:      localize("No pending workflow approvals.", "Belum ada persetujuan workflow tertunda."),
				},
				{
					Key:                 "documents.requests.form",
					Title:               "Request Draft Form",
					TitleI18n:           localize("Request Draft Form", "Form Draf Permintaan"),
					Kind:                "form",
					DocumentType:        "generic_request",
					RequiredPermissions: []string{"document.update_draft"},
					Fields: []module.FieldDefinition{
						{Key: "title", Label: "Title", LabelI18n: localize("Title", "Judul"), Path: "body.payload.title", Type: "string", Widget: "text", Placeholder: "Enter request title", PlaceholderI18n: localize("Enter request title", "Masukkan judul permintaan"), HelpText: "Short summary used in lists.", HelpTextI18n: localize("Short summary used in lists.", "Ringkasan singkat yang dipakai di daftar."), Required: true, MinLength: 5, MaxLength: 280},
					},
					Sections: []module.SectionDefinition{{
						Key: "draft_fields", Title: "Draft Fields", TitleI18n: localize("Draft Fields", "Field Draf"), Fields: []module.FieldDefinition{
							{Key: "title", Label: "Title", LabelI18n: localize("Title", "Judul"), Path: "body.payload.title", Type: "string", Widget: "textarea", Placeholder: "Describe the request", PlaceholderI18n: localize("Describe the request", "Jelaskan permintaan"), Required: true, MinLength: 5, MaxLength: 280},
						},
					}},
				},
			},
			DocumentFlows: []module.DocumentFlowDefinition{{
				Key:                 "documents.requests.intake",
				Title:               "Request Intake",
				TitleI18n:           localize("Request Intake", "Intake Permintaan"),
				RoutePath:           "/documents/new",
				PrimaryDocumentType: "generic_request",
				RequiredPermissions: []string{"document.create"},
				Steps: []module.DocumentFlowStepDefinition{
					{
						Key:       "intake",
						Title:     "Primary Request",
						TitleI18n: localize("Primary Request", "Permintaan Utama"),
						Documents: []module.DocumentFlowDocumentDefinition{{
							Key:           "request",
							Title:         "Request",
							TitleI18n:     localize("Request", "Permintaan"),
							DocumentType:  "generic_request",
							PrimaryOutput: true,
							Sections: []module.SectionDefinition{{
								Key: "request_core", Title: "Request Details", TitleI18n: localize("Request Details", "Detail Permintaan"), Fields: []module.FieldDefinition{
									{Key: "title", Label: "Title", LabelI18n: localize("Title", "Judul"), Path: "body.payload.title", Type: "string", Widget: "text", Placeholder: "Enter request title", PlaceholderI18n: localize("Enter request title", "Masukkan judul permintaan"), Required: true, MinLength: 5, MaxLength: 280},
									{Key: "request_kind", Label: "Request Kind", LabelI18n: localize("Request Kind", "Jenis Permintaan"), Path: "body.payload.request_kind", Type: "string", Widget: "select", Options: []string{"review", "followup"}, Required: true},
								},
							}},
						}},
						NextRules: []module.DocumentFlowBranchRule{
							{Path: "documents.request.payload.request_kind", Equals: "review", NextStepKey: "review_packet"},
							{Path: "documents.request.payload.request_kind", Equals: "followup", NextStepKey: "followup_plan"},
						},
					},
					{
						Key:       "review_packet",
						Title:     "Review Packet",
						TitleI18n: localize("Review Packet", "Paket Tinjauan"),
						Documents: []module.DocumentFlowDocumentDefinition{
							{
								Key:          "review_note",
								Title:        "Review Note",
								TitleI18n:    localize("Review Note", "Catatan Tinjauan"),
								DocumentType: "generic_request",
								LinkType:     "related_to",
								Sections: []module.SectionDefinition{{
									Key: "review_note", Title: "Review Note", TitleI18n: localize("Review Note", "Catatan Tinjauan"), Fields: []module.FieldDefinition{
										{Key: "title", Label: "Title", LabelI18n: localize("Title", "Judul"), Path: "body.payload.title", Type: "string", Widget: "text", Required: true, MinLength: 3, MaxLength: 120},
										{Key: "notes", Label: "Notes", LabelI18n: localize("Notes", "Catatan"), Path: "body.payload.notes", Type: "string", Widget: "textarea", Required: true, MinLength: 5, MaxLength: 500},
									},
								}},
							},
							{
								Key:          "review_checklist",
								Title:        "Review Checklist",
								TitleI18n:    localize("Review Checklist", "Daftar Periksa Tinjauan"),
								DocumentType: "generic_request",
								LinkType:     "related_to",
								Sections: []module.SectionDefinition{{
									Key: "review_checklist", Title: "Checklist", TitleI18n: localize("Checklist", "Daftar Periksa"), Fields: []module.FieldDefinition{
										{Key: "title", Label: "Title", LabelI18n: localize("Title", "Judul"), Path: "body.payload.title", Type: "string", Widget: "text", Required: true, MinLength: 3, MaxLength: 120},
										{Key: "owner", Label: "Owner", LabelI18n: localize("Owner", "Penanggung Jawab"), Path: "body.payload.owner", Type: "string", Widget: "text", Required: true, MinLength: 3, MaxLength: 120},
									},
								}},
							},
						},
					},
					{
						Key:       "followup_plan",
						Title:     "Follow-up Plan",
						TitleI18n: localize("Follow-up Plan", "Rencana Tindak Lanjut"),
						Documents: []module.DocumentFlowDocumentDefinition{{
							Key:          "followup_plan",
							Title:        "Follow-up Plan",
							TitleI18n:    localize("Follow-up Plan", "Rencana Tindak Lanjut"),
							DocumentType: "generic_request",
							LinkType:     "related_to",
							Sections: []module.SectionDefinition{{
								Key: "followup_plan", Title: "Plan", TitleI18n: localize("Plan", "Rencana"), Fields: []module.FieldDefinition{
									{Key: "title", Label: "Title", LabelI18n: localize("Title", "Judul"), Path: "body.payload.title", Type: "string", Widget: "text", Required: true, MinLength: 3, MaxLength: 120},
									{Key: "next_action", Label: "Next Action", LabelI18n: localize("Next Action", "Tindak Lanjut"), Path: "body.payload.next_action", Type: "string", Widget: "textarea", Required: true, MinLength: 5, MaxLength: 500},
								},
							}},
						}},
					},
				},
			}, {
				Key:                 "documents.self_service.requests.intake",
				Title:               "Self-Service Request",
				TitleI18n:           localize("Self-Service Request", "Permintaan Self-Service"),
				Surface:             module.UISurfaceSelfService,
				RoutePath:           "/self-service/requests/new",
				PrimaryDocumentType: "generic_request",
				RequiredPermissions: []string{"document.create"},
				Steps: []module.DocumentFlowStepDefinition{{
					Key:       "request",
					Title:     "Request",
					TitleI18n: localize("Request", "Permintaan"),
					Documents: []module.DocumentFlowDocumentDefinition{{
						Key:           "request",
						Title:         "Request",
						TitleI18n:     localize("Request", "Permintaan"),
						DocumentType:  "generic_request",
						PrimaryOutput: true,
						Sections: []module.SectionDefinition{{
							Key: "request_core", Title: "Request", TitleI18n: localize("Request", "Permintaan"), Fields: []module.FieldDefinition{
								{Key: "title", Label: "Title", LabelI18n: localize("Title", "Judul"), Path: "body.payload.title", Type: "string", Widget: "textarea", Placeholder: "Describe your request", PlaceholderI18n: localize("Describe your request", "Jelaskan permintaan Anda"), Required: true, MinLength: 5, MaxLength: 280},
							},
						}},
					}},
				}},
			}},
		},
		SearchIndexes: []search.IndexDefinition{{
			Key:                 "documents.requests.search",
			Title:               "Request Search",
			SourceKind:          "document",
			DocumentType:        "generic_request",
			ViewKey:             "documents.requests.list",
			Modes:               []string{"keyword", "vector", "hybrid"},
			OrganizationSplit:   true,
			RequiredPermissions: []string{"document.list"},
			QueryFilterFields:   []string{"status", "location_id", "document_type"},
			QuerySortFields:     []string{"status", "updated_at", "title"},
			Fields: []search.IndexFieldDefinition{
				{Key: "document_id", Path: "header.id", Type: "string", Searchable: true},
				{Key: "document_type", Path: "header.type", Type: "string", Facet: true},
				{Key: "status", Path: "header.status", Type: "string", Facet: true, Sort: true},
				{Key: "title", Path: "body.payload.title", Type: "string", Searchable: true, Sort: true},
			},
			VectorFields: []search.VectorFieldDefinition{{
				Key: "semantic", SourcePaths: []string{"body.payload.title"}, EmbeddingMode: "external", Dimensions: 8, DistanceMetric: "cosine",
			}},
		}, {
			Key:                 "documents.summary.search",
			Title:               "Request Summary Projection Search",
			SourceKind:          "projection",
			ProjectionKey:       "document_summary",
			ViewKey:             "documents.requests.list",
			Modes:               []string{"keyword"},
			OrganizationSplit:   true,
			RequiredPermissions: []string{"document.list"},
			QueryFilterFields:   []string{"status", "location_id", "document_type"},
			QuerySortFields:     []string{"status", "updated_at"},
			Fields: []search.IndexFieldDefinition{
				{Key: "document_id", Path: "document_id", Type: "string", Searchable: true},
				{Key: "document_type", Path: "document_type", Type: "string", Facet: true},
				{Key: "status", Path: "status", Type: "string", Facet: true, Sort: true},
			},
		}},
		Offline: module.OfflineDefinition{
			Projections: []module.OfflineProjectionDefinition{{
				IndexKey:             "documents.requests.search",
				Title:                "Requests",
				TitleI18n:            localize("Requests", "Permintaan"),
				RequiredPermissions:  []string{"document.list"},
				DefaultFilters:       []string{"status=draft"},
				DefaultIncludeFields: []string{"document_id", "document_type", "status", "title"},
			}},
			Documents: []module.OfflineDocumentDefinition{{
				Type:                "generic_request",
				Title:               "Generic Request",
				TitleI18n:           localize("Generic Request", "Permintaan Generik"),
				CreatePermissionKey: "document.create",
				UpdatePermissionKey: "document.update_draft",
				RequiredPermissions: []string{"document.read"},
			}},
		},
	}
}
