package app

import (
	"orbyte/internal/platform/httpx"
	"orbyte/internal/platform/model"
	"orbyte/internal/platform/module"
)

func financeReportingCoreKernelPackManifest() module.Manifest {
	return module.Manifest{
		Key:          "finance_reporting_core",
		Name:         "Finance Reporting Core",
		NameI18n:     localize("Finance Reporting Core", "Inti Pelaporan Keuangan"),
		Version:      "1.0.0",
		DomainFamily: "business",
		Dependencies: []string{"platform.core", "commercial_core", "procurement_core", "inventory_core", "production_core"},
		AdminConsole: module.AdminConsoleDefinition{
			Title:           "Finance Console",
			TitleI18n:       localize("Finance Console", "Konsol Keuangan"),
			Description:     "Financial statements, tax summary, journal review, and accounting period close.",
			DescriptionI18n: localize("Financial statements, tax summary, journal review, and accounting period close.", "Laporan keuangan, ringkasan pajak, tinjauan jurnal, dan tutup periode akuntansi."),
			Sections: []module.AdminConsoleSectionDefinition{
				{
					Key:       "reports",
					Title:     "Finance Reports",
					TitleI18n: localize("Finance Reports", "Laporan Keuangan"),
					Kind:      module.AdminConsoleSectionResourceLinks,
					Links: []module.AdminConsoleLinkDefinition{
						adminConsoleLink("trial_balance", "Trial Balance", "Neraca Saldo", "/ui/finance/trial-balance", "Open trial balance.", "Buka neraca saldo.", "finance.read"),
						adminConsoleLink("profit_loss", "Profit and Loss", "Laba Rugi", "/ui/finance/profit-and-loss", "Open profit and loss.", "Buka laporan laba rugi.", "finance.read"),
						adminConsoleLink("balance_sheet", "Balance Sheet", "Neraca", "/ui/finance/balance-sheet", "Open balance sheet.", "Buka neraca.", "finance.read"),
						adminConsoleLink("tax_summary", "Tax Summary", "Ringkasan Pajak", "/ui/finance/tax-summary", "Open tax summary.", "Buka ringkasan pajak.", "finance.read"),
						{
							Key:                 "ar_aging",
							Label:               "AR Aging",
							LabelI18n:           localize("AR Aging", "Umur Piutang"),
							RoutePath:           "/ui/finance/ar-aging",
							Description:         "Open accounts receivable aging.",
							DescriptionI18n:     localize("Open accounts receivable aging.", "Buka umur piutang."),
							RequiredPermissions: []string{"finance.read", "document.read"},
						},
						{
							Key:                 "ap_aging",
							Label:               "AP Aging",
							LabelI18n:           localize("AP Aging", "Umur Utang"),
							RoutePath:           "/ui/finance/ap-aging",
							Description:         "Open accounts payable aging.",
							DescriptionI18n:     localize("Open accounts payable aging.", "Buka umur utang."),
							RequiredPermissions: []string{"finance.read", "document.read"},
						},
						{
							Key:                 "ar_reconciliation",
							Label:               "AR Reconciliation",
							LabelI18n:           localize("AR Reconciliation", "Rekonsiliasi Piutang"),
							RoutePath:           "/ui/finance/ar-reconciliation",
							Description:         "Open receivable reconciliation.",
							DescriptionI18n:     localize("Open receivable reconciliation.", "Buka rekonsiliasi piutang."),
							RequiredPermissions: []string{"finance.read", "document.read"},
						},
						{
							Key:                 "ap_reconciliation",
							Label:               "AP Reconciliation",
							LabelI18n:           localize("AP Reconciliation", "Rekonsiliasi Utang"),
							RoutePath:           "/ui/finance/ap-reconciliation",
							Description:         "Open payable reconciliation.",
							DescriptionI18n:     localize("Open payable reconciliation.", "Buka rekonsiliasi utang."),
							RequiredPermissions: []string{"finance.read", "document.read"},
						},
						{
							Key:                 "journal_ledger",
							Label:               "Journal Ledger",
							LabelI18n:           localize("Journal Ledger", "Buku Jurnal"),
							RoutePath:           "/ui/finance/journal-ledger",
							Description:         "Open journal ledger.",
							DescriptionI18n:     localize("Open journal ledger.", "Buka buku jurnal."),
							RequiredPermissions: []string{"finance.read", "document.read"},
						},
					},
				},
				{
					Key:       "masters",
					Title:     "Accounting Setup",
					TitleI18n: localize("Accounting Setup", "Pengaturan Akuntansi"),
					Kind:      module.AdminConsoleSectionResourceLinks,
					Links: []module.AdminConsoleLinkDefinition{
						adminConsoleLink("finance_accounts", "Finance Accounts", "Akun Keuangan", "/ui/finance/accounts", "Manage finance accounts and report grouping.", "Kelola akun keuangan dan grup laporan.", "finance_account.list"),
						adminConsoleLink("accounting_periods", "Accounting Periods", "Periode Akuntansi", "/ui/finance/periods", "Manage open and closed accounting periods.", "Kelola periode akuntansi terbuka dan tertutup.", "accounting_period.list"),
						adminConsoleLink("journal_templates", "Journal Templates", "Template Jurnal", "/ui/finance/journal-templates", "Manage recurring and accrual journal templates.", "Kelola template jurnal berulang dan akrual.", "journal_template.list"),
						adminConsoleLink("journal_runs", "Journal Runs", "Run Jurnal", "/ui/finance/journal-runs", "Review generated period-end journal runs.", "Tinjau run jurnal akhir periode.", "journal_run.list"),
						adminConsoleLink("period_tasks", "Period Tasks", "Tugas Tutup Periode", "/ui/finance/period-tasks", "Review period close checklist tasks.", "Tinjau tugas checklist tutup periode.", "accounting_period_task.list"),
					},
				},
			},
		},
		Models: []model.Definition{
			{
				Key:                 "finance_account",
				DisplayName:         "Finance Account",
				DisplayNameI18n:     localize("Finance Account", "Akun Keuangan"),
				OwnerModuleKey:      "finance_reporting_core",
				Version:             "v1",
				CreatePermissionKey: "finance_account.create",
				ListPermissionKey:   "finance_account.list",
				ReadPermissionKey:   "finance_account.read",
				UpdatePermissionKey: "finance_account.update",
				DefaultSort:         "code",
				Fields: []model.FieldDefinition{
					{Key: "code", Label: "Code", LabelI18n: localize("Code", "Kode"), Type: "string", Required: true},
					{Key: "name", Label: "Name", LabelI18n: localize("Name", "Nama"), Type: "string", Required: true},
					{Key: "account_type", Label: "Account Type", LabelI18n: localize("Account Type", "Tipe Akun"), Type: "string", Required: true, DefaultValue: "expense"},
					{Key: "report_group", Label: "Report Group", LabelI18n: localize("Report Group", "Grup Laporan"), Type: "string"},
					{Key: "normal_balance", Label: "Normal Balance", LabelI18n: localize("Normal Balance", "Saldo Normal"), Type: "string", DefaultValue: "debit"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Type: "string", DefaultValue: "active"},
				},
			},
			{
				Key:                 "accounting_period",
				DisplayName:         "Accounting Period",
				DisplayNameI18n:     localize("Accounting Period", "Periode Akuntansi"),
				OwnerModuleKey:      "finance_reporting_core",
				Version:             "v1",
				CreatePermissionKey: "accounting_period.create",
				ListPermissionKey:   "accounting_period.list",
				ReadPermissionKey:   "accounting_period.read",
				UpdatePermissionKey: "accounting_period.update",
				DefaultSort:         "start_date",
				Fields: []model.FieldDefinition{
					{Key: "organization_id", Label: "Organization", LabelI18n: localize("Organization", "Organisasi"), Type: "string", Required: true},
					{Key: "location_id", Label: "Location", LabelI18n: localize("Location", "Lokasi"), Type: "string"},
					{Key: "period_key", Label: "Period Key", LabelI18n: localize("Period Key", "Kunci Periode"), Type: "string", Required: true},
					{Key: "start_date", Label: "Start Date", LabelI18n: localize("Start Date", "Tanggal Mulai"), Type: "string", Required: true},
					{Key: "end_date", Label: "End Date", LabelI18n: localize("End Date", "Tanggal Selesai"), Type: "string", Required: true, ConstraintRuleKeys: []string{"accounting_period.date_range"}},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Type: "string", DefaultValue: "open"},
					{Key: "closed_at", Label: "Closed At", LabelI18n: localize("Closed At", "Ditutup Pada"), Type: "string"},
					{Key: "closed_by", Label: "Closed By", LabelI18n: localize("Closed By", "Ditutup Oleh"), Type: "string"},
					{Key: "notes", Label: "Notes", LabelI18n: localize("Notes", "Catatan"), Type: "string"},
				},
			},
			{
				Key:                 "journal_template",
				DisplayName:         "Journal Template",
				DisplayNameI18n:     localize("Journal Template", "Template Jurnal"),
				OwnerModuleKey:      "finance_reporting_core",
				Version:             "v1",
				CreatePermissionKey: "journal_template.create",
				ListPermissionKey:   "journal_template.list",
				ReadPermissionKey:   "journal_template.read",
				UpdatePermissionKey: "journal_template.update",
				DefaultSort:         "code",
				Fields: []model.FieldDefinition{
					{Key: "organization_id", Label: "Organization", LabelI18n: localize("Organization", "Organisasi"), Type: "string", Required: true},
					{Key: "location_id", Label: "Location", LabelI18n: localize("Location", "Lokasi"), Type: "string"},
					{Key: "code", Label: "Code", LabelI18n: localize("Code", "Kode"), Type: "string", Required: true},
					{Key: "name", Label: "Name", LabelI18n: localize("Name", "Nama"), Type: "string", Required: true},
					{Key: "journal_kind", Label: "Journal Kind", LabelI18n: localize("Journal Kind", "Jenis Jurnal"), Type: "string", Required: true, DefaultValue: "recurring"},
					{Key: "cadence", Label: "Cadence", LabelI18n: localize("Cadence", "Cadence"), Type: "string", Required: true, DefaultValue: "monthly"},
					{Key: "currency_code", Label: "Currency", LabelI18n: localize("Currency", "Mata Uang"), Type: "string", DefaultValue: "IDR"},
					{Key: "description_template", Label: "Description Template", LabelI18n: localize("Description Template", "Template Deskripsi"), Type: "string"},
					{Key: "required_for_period_close", Label: "Required For Close", LabelI18n: localize("Required For Close", "Wajib Untuk Tutup"), Type: "bool"},
					{Key: "journal_lines", Label: "Journal Lines", LabelI18n: localize("Journal Lines", "Baris Jurnal"), Type: "object"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Type: "string", DefaultValue: "active"},
					{Key: "notes", Label: "Notes", LabelI18n: localize("Notes", "Catatan"), Type: "string"},
				},
			},
			{
				Key:                 "journal_run",
				DisplayName:         "Journal Run",
				DisplayNameI18n:     localize("Journal Run", "Run Jurnal"),
				OwnerModuleKey:      "finance_reporting_core",
				Version:             "v1",
				CreatePermissionKey: "journal_run.create",
				ListPermissionKey:   "journal_run.list",
				ReadPermissionKey:   "journal_run.read",
				UpdatePermissionKey: "journal_run.update",
				DefaultSort:         "period_key",
				Fields: []model.FieldDefinition{
					{Key: "organization_id", Label: "Organization", LabelI18n: localize("Organization", "Organisasi"), Type: "string", Required: true},
					{Key: "location_id", Label: "Location", LabelI18n: localize("Location", "Lokasi"), Type: "string"},
					{Key: "accounting_period_id", Label: "Accounting Period ID", LabelI18n: localize("Accounting Period ID", "ID Periode Akuntansi"), Type: "string", Required: true},
					{Key: "period_key", Label: "Period Key", LabelI18n: localize("Period Key", "Kunci Periode"), Type: "string", Required: true},
					{Key: "journal_template_id", Label: "Journal Template ID", LabelI18n: localize("Journal Template ID", "ID Template Jurnal"), Type: "string", Required: true},
					{Key: "template_code", Label: "Template Code", LabelI18n: localize("Template Code", "Kode Template"), Type: "string"},
					{Key: "template_name", Label: "Template Name", LabelI18n: localize("Template Name", "Nama Template"), Type: "string"},
					{Key: "cadence", Label: "Cadence", LabelI18n: localize("Cadence", "Cadence"), Type: "string"},
					{Key: "journal_kind", Label: "Journal Kind", LabelI18n: localize("Journal Kind", "Jenis Jurnal"), Type: "string"},
					{Key: "posting_date", Label: "Posting Date", LabelI18n: localize("Posting Date", "Tanggal Posting"), Type: "string"},
					{Key: "generated_posting_id", Label: "Posting ID", LabelI18n: localize("Posting ID", "ID Posting"), Type: "string"},
					{Key: "generated_posting_number", Label: "Posting Number", LabelI18n: localize("Posting Number", "Nomor Posting"), Type: "string"},
					{Key: "generated_posting_status", Label: "Posting Status", LabelI18n: localize("Posting Status", "Status Posting"), Type: "string"},
					{Key: "reversal_status", Label: "Reversal Status", LabelI18n: localize("Reversal Status", "Status Reversal"), Type: "string"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Type: "string", DefaultValue: "generated"},
				},
			},
			{
				Key:                 "accounting_period_task",
				DisplayName:         "Accounting Period Task",
				DisplayNameI18n:     localize("Accounting Period Task", "Tugas Periode Akuntansi"),
				OwnerModuleKey:      "finance_reporting_core",
				Version:             "v1",
				CreatePermissionKey: "accounting_period_task.create",
				ListPermissionKey:   "accounting_period_task.list",
				ReadPermissionKey:   "accounting_period_task.read",
				UpdatePermissionKey: "accounting_period_task.update",
				DefaultSort:         "task_code",
				Fields: []model.FieldDefinition{
					{Key: "organization_id", Label: "Organization", LabelI18n: localize("Organization", "Organisasi"), Type: "string", Required: true},
					{Key: "location_id", Label: "Location", LabelI18n: localize("Location", "Lokasi"), Type: "string"},
					{Key: "accounting_period_id", Label: "Accounting Period ID", LabelI18n: localize("Accounting Period ID", "ID Periode Akuntansi"), Type: "string", Required: true},
					{Key: "period_key", Label: "Period Key", LabelI18n: localize("Period Key", "Kunci Periode"), Type: "string"},
					{Key: "task_code", Label: "Task Code", LabelI18n: localize("Task Code", "Kode Tugas"), Type: "string", Required: true},
					{Key: "label", Label: "Label", LabelI18n: localize("Label", "Label"), Type: "string", Required: true},
					{Key: "task_type", Label: "Task Type", LabelI18n: localize("Task Type", "Tipe Tugas"), Type: "string", Required: true, DefaultValue: "checklist"},
					{Key: "required", Label: "Required", LabelI18n: localize("Required", "Wajib"), Type: "bool"},
					{Key: "journal_template_id", Label: "Journal Template ID", LabelI18n: localize("Journal Template ID", "ID Template Jurnal"), Type: "string"},
					{Key: "journal_run_id", Label: "Journal Run ID", LabelI18n: localize("Journal Run ID", "ID Run Jurnal"), Type: "string"},
					{Key: "posting_id", Label: "Posting ID", LabelI18n: localize("Posting ID", "ID Posting"), Type: "string"},
					{Key: "posting_number", Label: "Posting Number", LabelI18n: localize("Posting Number", "Nomor Posting"), Type: "string"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Type: "string", DefaultValue: "pending"},
					{Key: "completed_at", Label: "Completed At", LabelI18n: localize("Completed At", "Diselesaikan Pada"), Type: "string"},
					{Key: "completed_by", Label: "Completed By", LabelI18n: localize("Completed By", "Diselesaikan Oleh"), Type: "string"},
					{Key: "note", Label: "Note", LabelI18n: localize("Note", "Catatan"), Type: "string"},
				},
			},
		},
		Security: module.SecurityDefinition{
			Permissions: append(
				append(
					commercialModelPermissions("finance_account", "Finance Account"),
					append(
						commercialModelPermissions("accounting_period", "Accounting Period"),
						append(
							commercialModelPermissions("journal_template", "Journal Template"),
							append(
								commercialModelPermissions("journal_run", "Journal Run"),
								commercialModelPermissions("accounting_period_task", "Accounting Period Task")...,
							)...,
						)...,
					)...,
				),
				[]module.PermissionDefinition{
					{Key: "finance.read", Action: "read", Resource: "finance", DisplayName: "Read Finance Reports", DisplayNameI18n: localize("Read Finance Reports", "Lihat Laporan Keuangan")},
					{Key: "finance.close", Action: "close", Resource: "finance", DisplayName: "Close Finance Periods", DisplayNameI18n: localize("Close Finance Periods", "Tutup Periode Keuangan")},
					{Key: "finance.period_end.manage", Action: "manage", Resource: "finance_period_end", DisplayName: "Manage Period-End Journals", DisplayNameI18n: localize("Manage Period-End Journals", "Kelola Jurnal Tutup Periode")},
					{Key: "finance.reverse", Action: "reverse", Resource: "finance_journal", DisplayName: "Reverse Finance Journals", DisplayNameI18n: localize("Reverse Finance Journals", "Reverse Jurnal Keuangan")},
				}...,
			),
			RoleTemplates: []module.RoleTemplateDefinition{
				{
					Key:            "finance_manager",
					Name:           "Finance Manager",
					NameI18n:       localize("Finance Manager", "Manajer Keuangan"),
					AllowedScopes:  []string{"deployment", "organization", "location"},
					PermissionKeys: []string{"finance_account.create", "finance_account.list", "finance_account.read", "finance_account.update", "accounting_period.create", "accounting_period.list", "accounting_period.read", "accounting_period.update", "journal_template.create", "journal_template.list", "journal_template.read", "journal_template.update", "journal_run.create", "journal_run.list", "journal_run.read", "journal_run.update", "accounting_period_task.create", "accounting_period_task.list", "accounting_period_task.read", "accounting_period_task.update", "finance.read", "finance.close", "finance.period_end.manage", "finance.reverse", "document.list", "document.read", "document.create", "document.update_draft"},
				},
			},
		},
		Frontend: module.FrontendDefinition{
			Menus: []module.MenuDefinition{
				{Key: "finance.accounts", Label: "Finance Accounts", LabelI18n: localize("Finance Accounts", "Akun Keuangan"), ActionKey: "finance.accounts.list", Order: 88, RequiredPermissions: []string{"finance_account.list"}},
				{Key: "finance.periods", Label: "Accounting Periods", LabelI18n: localize("Accounting Periods", "Periode Akuntansi"), ActionKey: "finance.periods.list", Order: 89, RequiredPermissions: []string{"accounting_period.list"}},
				{Key: "finance.journal_templates", Label: "Journal Templates", LabelI18n: localize("Journal Templates", "Template Jurnal"), ActionKey: "finance.journal_templates.list", Order: 90, RequiredPermissions: []string{"journal_template.list"}},
				{Key: "finance.journal_runs", Label: "Journal Runs", LabelI18n: localize("Journal Runs", "Run Jurnal"), ActionKey: "finance.journal_runs.list", Order: 91, RequiredPermissions: []string{"journal_run.list"}},
				{Key: "finance.period_close", Label: "Period Close", LabelI18n: localize("Period Close", "Tutup Periode"), ActionKey: "finance.period_close", Order: 92, RequiredPermissions: []string{"finance.read", "accounting_period.read"}},
				{Key: "finance.trial_balance", Label: "Trial Balance", LabelI18n: localize("Trial Balance", "Neraca Saldo"), ActionKey: "finance.trial_balance", Order: 93, RequiredPermissions: []string{"finance.read"}},
				{Key: "finance.profit_loss", Label: "Profit and Loss", LabelI18n: localize("Profit and Loss", "Laba Rugi"), ActionKey: "finance.profit_and_loss", Order: 94, RequiredPermissions: []string{"finance.read"}},
				{Key: "finance.balance_sheet", Label: "Balance Sheet", LabelI18n: localize("Balance Sheet", "Neraca"), ActionKey: "finance.balance_sheet", Order: 95, RequiredPermissions: []string{"finance.read"}},
				{Key: "finance.tax_summary", Label: "Tax Summary", LabelI18n: localize("Tax Summary", "Ringkasan Pajak"), ActionKey: "finance.tax_summary", Order: 96, RequiredPermissions: []string{"finance.read"}},
				{Key: "finance.ar_aging", Label: "AR Aging", LabelI18n: localize("AR Aging", "Umur Piutang"), ActionKey: "finance.ar_aging", Order: 97, RequiredPermissions: []string{"finance.read", "document.read"}},
				{Key: "finance.ap_aging", Label: "AP Aging", LabelI18n: localize("AP Aging", "Umur Utang"), ActionKey: "finance.ap_aging", Order: 98, RequiredPermissions: []string{"finance.read", "document.read"}},
				{Key: "finance.ar_reconciliation", Label: "AR Reconciliation", LabelI18n: localize("AR Reconciliation", "Rekonsiliasi Piutang"), ActionKey: "finance.ar_reconciliation", Order: 99, RequiredPermissions: []string{"finance.read", "document.read"}},
				{Key: "finance.ap_reconciliation", Label: "AP Reconciliation", LabelI18n: localize("AP Reconciliation", "Rekonsiliasi Utang"), ActionKey: "finance.ap_reconciliation", Order: 100, RequiredPermissions: []string{"finance.read", "document.read"}},
				{Key: "finance.journal_ledger", Label: "Journal Ledger", LabelI18n: localize("Journal Ledger", "Buku Jurnal"), ActionKey: "finance.journal_ledger", Order: 101, RequiredPermissions: []string{"finance.read", "document.read"}},
			},
			Actions: []module.ActionDefinition{
				{Key: "finance.accounts.list", Label: "Finance Accounts", LabelI18n: localize("Finance Accounts", "Akun Keuangan"), Kind: "navigate", RoutePath: "/finance/accounts", ViewKey: "finance.accounts.list", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"finance_account.list"}},
				{Key: "finance.accounts.detail", Label: "Finance Account Detail", LabelI18n: localize("Finance Account Detail", "Detail Akun Keuangan"), Kind: "navigate", RoutePath: "/finance/accounts/detail", ViewKey: "finance.accounts.detail", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"finance_account.read"}},
				{Key: "finance.accounts.form", Label: "Finance Account Form", LabelI18n: localize("Finance Account Form", "Form Akun Keuangan"), Kind: "navigate", RoutePath: "/finance/accounts/form", ViewKey: "finance.accounts.form", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"finance_account.update"}},
				{Key: "finance.periods.list", Label: "Accounting Periods", LabelI18n: localize("Accounting Periods", "Periode Akuntansi"), Kind: "navigate", RoutePath: "/finance/periods", ViewKey: "finance.periods.list", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"accounting_period.list"}},
				{Key: "finance.periods.detail", Label: "Accounting Period Detail", LabelI18n: localize("Accounting Period Detail", "Detail Periode Akuntansi"), Kind: "navigate", RoutePath: "/finance/periods/detail", ViewKey: "finance.periods.detail", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"accounting_period.read"}},
				{Key: "finance.periods.form", Label: "Accounting Period Form", LabelI18n: localize("Accounting Period Form", "Form Periode Akuntansi"), Kind: "navigate", RoutePath: "/finance/periods/form", ViewKey: "finance.periods.form", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"accounting_period.update"}},
				{Key: "finance.journal_templates.list", Label: "Journal Templates", LabelI18n: localize("Journal Templates", "Template Jurnal"), Kind: "navigate", RoutePath: "/finance/journal-templates", ViewKey: "finance.journal_templates.list", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"journal_template.list"}},
				{Key: "finance.journal_templates.detail", Label: "Journal Template Detail", LabelI18n: localize("Journal Template Detail", "Detail Template Jurnal"), Kind: "navigate", RoutePath: "/finance/journal-templates/detail", ViewKey: "finance.journal_templates.detail", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"journal_template.read"}},
				{Key: "finance.journal_templates.form", Label: "Journal Template Form", LabelI18n: localize("Journal Template Form", "Form Template Jurnal"), Kind: "navigate", RoutePath: "/finance/journal-templates/form", ViewKey: "finance.journal_templates.form", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"journal_template.update"}},
				{Key: "finance.journal_runs.list", Label: "Journal Runs", LabelI18n: localize("Journal Runs", "Run Jurnal"), Kind: "navigate", RoutePath: "/finance/journal-runs", ViewKey: "finance.journal_runs.list", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"journal_run.list"}},
				{Key: "finance.journal_runs.detail", Label: "Journal Run Detail", LabelI18n: localize("Journal Run Detail", "Detail Run Jurnal"), Kind: "navigate", RoutePath: "/finance/journal-runs/detail", ViewKey: "finance.journal_runs.detail", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"journal_run.read"}},
				{Key: "finance.period_tasks.list", Label: "Period Tasks", LabelI18n: localize("Period Tasks", "Tugas Tutup Periode"), Kind: "navigate", RoutePath: "/finance/period-tasks", ViewKey: "finance.period_tasks.list", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"accounting_period_task.list"}},
				{Key: "finance.period_tasks.detail", Label: "Period Task Detail", LabelI18n: localize("Period Task Detail", "Detail Tugas Periode"), Kind: "navigate", RoutePath: "/finance/period-tasks/detail", ViewKey: "finance.period_tasks.detail", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"accounting_period_task.read"}},
				{Key: "finance.period_close", Label: "Period Close", LabelI18n: localize("Period Close", "Tutup Periode"), Kind: "navigate", RoutePath: "/finance/period-close", CustomEntryKey: "finance.period_close", RenderMode: module.RenderModeCustom, RequiredPermissions: []string{"finance.read", "accounting_period.read"}},
				{Key: "finance.trial_balance", Label: "Trial Balance", LabelI18n: localize("Trial Balance", "Neraca Saldo"), Kind: "navigate", RoutePath: "/finance/trial-balance", CustomEntryKey: "finance.trial_balance", RenderMode: module.RenderModeCustom, RequiredPermissions: []string{"finance.read"}},
				{Key: "finance.profit_and_loss", Label: "Profit and Loss", LabelI18n: localize("Profit and Loss", "Laba Rugi"), Kind: "navigate", RoutePath: "/finance/profit-and-loss", CustomEntryKey: "finance.profit_and_loss", RenderMode: module.RenderModeCustom, RequiredPermissions: []string{"finance.read"}},
				{Key: "finance.balance_sheet", Label: "Balance Sheet", LabelI18n: localize("Balance Sheet", "Neraca"), Kind: "navigate", RoutePath: "/finance/balance-sheet", CustomEntryKey: "finance.balance_sheet", RenderMode: module.RenderModeCustom, RequiredPermissions: []string{"finance.read"}},
				{Key: "finance.tax_summary", Label: "Tax Summary", LabelI18n: localize("Tax Summary", "Ringkasan Pajak"), Kind: "navigate", RoutePath: "/finance/tax-summary", CustomEntryKey: "finance.tax_summary", RenderMode: module.RenderModeCustom, RequiredPermissions: []string{"finance.read"}},
				{Key: "finance.ar_aging", Label: "AR Aging", LabelI18n: localize("AR Aging", "Umur Piutang"), Kind: "navigate", RoutePath: "/finance/ar-aging", CustomEntryKey: "finance.ar_aging", RenderMode: module.RenderModeCustom, RequiredPermissions: []string{"finance.read", "document.read"}},
				{Key: "finance.ap_aging", Label: "AP Aging", LabelI18n: localize("AP Aging", "Umur Utang"), Kind: "navigate", RoutePath: "/finance/ap-aging", CustomEntryKey: "finance.ap_aging", RenderMode: module.RenderModeCustom, RequiredPermissions: []string{"finance.read", "document.read"}},
				{Key: "finance.ar_reconciliation", Label: "AR Reconciliation", LabelI18n: localize("AR Reconciliation", "Rekonsiliasi Piutang"), Kind: "navigate", RoutePath: "/finance/ar-reconciliation", CustomEntryKey: "finance.ar_reconciliation", RenderMode: module.RenderModeCustom, RequiredPermissions: []string{"finance.read", "document.read"}},
				{Key: "finance.ap_reconciliation", Label: "AP Reconciliation", LabelI18n: localize("AP Reconciliation", "Rekonsiliasi Utang"), Kind: "navigate", RoutePath: "/finance/ap-reconciliation", CustomEntryKey: "finance.ap_reconciliation", RenderMode: module.RenderModeCustom, RequiredPermissions: []string{"finance.read", "document.read"}},
				{Key: "finance.journal_ledger", Label: "Journal Ledger", LabelI18n: localize("Journal Ledger", "Buku Jurnal"), Kind: "navigate", RoutePath: "/finance/journal-ledger", CustomEntryKey: "finance.journal_ledger", RenderMode: module.RenderModeCustom, RequiredPermissions: []string{"finance.read", "document.read"}},
			},
			Views: []module.ViewDefinition{
				commercialModelListView("finance.accounts.list", "Finance Accounts", "finance_account", []module.ColumnDefinition{
					{Key: "code", Label: "Code", LabelI18n: localize("Code", "Kode"), Path: "values.code"},
					{Key: "name", Label: "Name", LabelI18n: localize("Name", "Nama"), Path: "values.name"},
					{Key: "account_type", Label: "Type", LabelI18n: localize("Type", "Tipe"), Path: "values.account_type"},
					{Key: "report_group", Label: "Group", LabelI18n: localize("Group", "Grup"), Path: "values.report_group"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status"},
				}, []string{"active", "inactive"}),
				commercialModelDetailView("finance.accounts.detail", "Finance Account Detail", "finance_account", []module.FieldDefinition{
					{Key: "code", Label: "Code", LabelI18n: localize("Code", "Kode"), Path: "values.code", Type: "string"},
					{Key: "name", Label: "Name", LabelI18n: localize("Name", "Nama"), Path: "values.name", Type: "string"},
					{Key: "account_type", Label: "Account Type", LabelI18n: localize("Account Type", "Tipe Akun"), Path: "values.account_type", Type: "string"},
					{Key: "report_group", Label: "Report Group", LabelI18n: localize("Report Group", "Grup Laporan"), Path: "values.report_group", Type: "string"},
					{Key: "normal_balance", Label: "Normal Balance", LabelI18n: localize("Normal Balance", "Saldo Normal"), Path: "values.normal_balance", Type: "string"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status", Type: "string"},
				}),
				commercialModelFormView("finance.accounts.form", "Finance Account Form", "finance_account", []module.FieldDefinition{
					{Key: "code", Label: "Code", LabelI18n: localize("Code", "Kode"), Path: "values.code", Type: "string", Widget: "text", Required: true},
					{Key: "name", Label: "Name", LabelI18n: localize("Name", "Nama"), Path: "values.name", Type: "string", Widget: "text", Required: true},
					{Key: "account_type", Label: "Account Type", LabelI18n: localize("Account Type", "Tipe Akun"), Path: "values.account_type", Type: "string", Widget: "select", Options: []string{"asset", "liability", "equity", "revenue", "expense"}},
					{Key: "report_group", Label: "Report Group", LabelI18n: localize("Report Group", "Grup Laporan"), Path: "values.report_group", Type: "string", Widget: "text"},
					{Key: "normal_balance", Label: "Normal Balance", LabelI18n: localize("Normal Balance", "Saldo Normal"), Path: "values.normal_balance", Type: "string", Widget: "select", Options: []string{"debit", "credit"}},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status", Type: "string", Widget: "select", Options: []string{"active", "inactive"}},
				}),
				commercialModelListView("finance.periods.list", "Accounting Periods", "accounting_period", []module.ColumnDefinition{
					{Key: "period_key", Label: "Period", LabelI18n: localize("Period", "Periode"), Path: "values.period_key"},
					{Key: "organization_id", Label: "Organization", LabelI18n: localize("Organization", "Organisasi"), Path: "values.organization_id"},
					{Key: "location_id", Label: "Location", LabelI18n: localize("Location", "Lokasi"), Path: "values.location_id"},
					{Key: "start_date", Label: "Start", LabelI18n: localize("Start", "Mulai"), Path: "values.start_date"},
					{Key: "end_date", Label: "End", LabelI18n: localize("End", "Selesai"), Path: "values.end_date"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status"},
				}, []string{"open", "closed"}),
				commercialModelDetailView("finance.periods.detail", "Accounting Period Detail", "accounting_period", []module.FieldDefinition{
					{Key: "period_key", Label: "Period", LabelI18n: localize("Period", "Periode"), Path: "values.period_key", Type: "string"},
					{Key: "organization_id", Label: "Organization", LabelI18n: localize("Organization", "Organisasi"), Path: "values.organization_id", Type: "string"},
					{Key: "location_id", Label: "Location", LabelI18n: localize("Location", "Lokasi"), Path: "values.location_id", Type: "string"},
					{Key: "start_date", Label: "Start Date", LabelI18n: localize("Start Date", "Tanggal Mulai"), Path: "values.start_date", Type: "string"},
					{Key: "end_date", Label: "End Date", LabelI18n: localize("End Date", "Tanggal Selesai"), Path: "values.end_date", Type: "string"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status", Type: "string"},
					{Key: "closed_at", Label: "Closed At", LabelI18n: localize("Closed At", "Ditutup Pada"), Path: "values.closed_at", Type: "string"},
					{Key: "closed_by", Label: "Closed By", LabelI18n: localize("Closed By", "Ditutup Oleh"), Path: "values.closed_by", Type: "string"},
					{Key: "notes", Label: "Notes", LabelI18n: localize("Notes", "Catatan"), Path: "values.notes", Type: "string"},
				}),
				commercialModelFormView("finance.periods.form", "Accounting Period Form", "accounting_period", []module.FieldDefinition{
					{Key: "organization_id", Label: "Organization", LabelI18n: localize("Organization", "Organisasi"), Path: "values.organization_id", Type: "string", Widget: "text", Required: true},
					{Key: "location_id", Label: "Location", LabelI18n: localize("Location", "Lokasi"), Path: "values.location_id", Type: "string", Widget: "text"},
					{Key: "period_key", Label: "Period Key", LabelI18n: localize("Period Key", "Kunci Periode"), Path: "values.period_key", Type: "string", Widget: "text", Required: true},
					{Key: "start_date", Label: "Start Date", LabelI18n: localize("Start Date", "Tanggal Mulai"), Path: "values.start_date", Type: "string", Widget: "text", Required: true},
					{Key: "end_date", Label: "End Date", LabelI18n: localize("End Date", "Tanggal Selesai"), Path: "values.end_date", Type: "string", Widget: "text", Required: true},
					{Key: "notes", Label: "Notes", LabelI18n: localize("Notes", "Catatan"), Path: "values.notes", Type: "string", Widget: "textarea"},
				}),
				commercialModelListView("finance.journal_templates.list", "Journal Templates", "journal_template", []module.ColumnDefinition{
					{Key: "code", Label: "Code", LabelI18n: localize("Code", "Kode"), Path: "values.code"},
					{Key: "name", Label: "Name", LabelI18n: localize("Name", "Nama"), Path: "values.name"},
					{Key: "journal_kind", Label: "Kind", LabelI18n: localize("Kind", "Jenis"), Path: "values.journal_kind"},
					{Key: "cadence", Label: "Cadence", LabelI18n: localize("Cadence", "Cadence"), Path: "values.cadence"},
					{Key: "required_for_period_close", Label: "Required", LabelI18n: localize("Required", "Wajib"), Path: "values.required_for_period_close"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status"},
				}, []string{"active", "inactive"}),
				commercialModelDetailView("finance.journal_templates.detail", "Journal Template Detail", "journal_template", []module.FieldDefinition{
					{Key: "organization_id", Label: "Organization", LabelI18n: localize("Organization", "Organisasi"), Path: "values.organization_id", Type: "string"},
					{Key: "location_id", Label: "Location", LabelI18n: localize("Location", "Lokasi"), Path: "values.location_id", Type: "string"},
					{Key: "code", Label: "Code", LabelI18n: localize("Code", "Kode"), Path: "values.code", Type: "string"},
					{Key: "name", Label: "Name", LabelI18n: localize("Name", "Nama"), Path: "values.name", Type: "string"},
					{Key: "journal_kind", Label: "Journal Kind", LabelI18n: localize("Journal Kind", "Jenis Jurnal"), Path: "values.journal_kind", Type: "string"},
					{Key: "cadence", Label: "Cadence", LabelI18n: localize("Cadence", "Cadence"), Path: "values.cadence", Type: "string"},
					{Key: "currency_code", Label: "Currency", LabelI18n: localize("Currency", "Mata Uang"), Path: "values.currency_code", Type: "string"},
					{Key: "description_template", Label: "Description Template", LabelI18n: localize("Description Template", "Template Deskripsi"), Path: "values.description_template", Type: "string"},
					{Key: "required_for_period_close", Label: "Required For Close", LabelI18n: localize("Required For Close", "Wajib Untuk Tutup"), Path: "values.required_for_period_close", Type: "bool"},
					{Key: "journal_lines", Label: "Journal Lines", LabelI18n: localize("Journal Lines", "Baris Jurnal"), Path: "values.journal_lines", Type: "object", Widget: "json"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status", Type: "string"},
					{Key: "notes", Label: "Notes", LabelI18n: localize("Notes", "Catatan"), Path: "values.notes", Type: "string"},
				}),
				commercialModelFormView("finance.journal_templates.form", "Journal Template Form", "journal_template", []module.FieldDefinition{
					{Key: "organization_id", Label: "Organization", LabelI18n: localize("Organization", "Organisasi"), Path: "values.organization_id", Type: "string", Widget: "text", Required: true},
					{Key: "location_id", Label: "Location", LabelI18n: localize("Location", "Lokasi"), Path: "values.location_id", Type: "string", Widget: "text"},
					{Key: "code", Label: "Code", LabelI18n: localize("Code", "Kode"), Path: "values.code", Type: "string", Widget: "text", Required: true},
					{Key: "name", Label: "Name", LabelI18n: localize("Name", "Nama"), Path: "values.name", Type: "string", Widget: "text", Required: true},
					{Key: "journal_kind", Label: "Journal Kind", LabelI18n: localize("Journal Kind", "Jenis Jurnal"), Path: "values.journal_kind", Type: "string", Widget: "select", Options: []string{"recurring", "accrual"}},
					{Key: "cadence", Label: "Cadence", LabelI18n: localize("Cadence", "Cadence"), Path: "values.cadence", Type: "string", Widget: "select", Options: []string{"monthly", "quarterly", "yearly"}},
					{Key: "currency_code", Label: "Currency", LabelI18n: localize("Currency", "Mata Uang"), Path: "values.currency_code", Type: "string", Widget: "text"},
					{Key: "description_template", Label: "Description Template", LabelI18n: localize("Description Template", "Template Deskripsi"), Path: "values.description_template", Type: "string", Widget: "textarea"},
					{Key: "required_for_period_close", Label: "Required For Close", LabelI18n: localize("Required For Close", "Wajib Untuk Tutup"), Path: "values.required_for_period_close", Type: "bool", Widget: "checkbox"},
					{Key: "journal_lines", Label: "Journal Lines", LabelI18n: localize("Journal Lines", "Baris Jurnal"), Path: "values.journal_lines", Type: "object", Widget: "json"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status", Type: "string", Widget: "select", Options: []string{"active", "inactive"}},
					{Key: "notes", Label: "Notes", LabelI18n: localize("Notes", "Catatan"), Path: "values.notes", Type: "string", Widget: "textarea"},
				}),
				commercialModelListView("finance.journal_runs.list", "Journal Runs", "journal_run", []module.ColumnDefinition{
					{Key: "period_key", Label: "Period", LabelI18n: localize("Period", "Periode"), Path: "values.period_key"},
					{Key: "template_code", Label: "Template", LabelI18n: localize("Template", "Template"), Path: "values.template_code"},
					{Key: "journal_kind", Label: "Kind", LabelI18n: localize("Kind", "Jenis"), Path: "values.journal_kind"},
					{Key: "posting_date", Label: "Posting Date", LabelI18n: localize("Posting Date", "Tanggal Posting"), Path: "values.posting_date"},
					{Key: "generated_posting_status", Label: "Posting Status", LabelI18n: localize("Posting Status", "Status Posting"), Path: "values.generated_posting_status"},
					{Key: "status", Label: "Run Status", LabelI18n: localize("Run Status", "Status Run"), Path: "values.status"},
				}, []string{"generated", "submitted", "posted", "reversed", "cancelled"}),
				commercialModelDetailView("finance.journal_runs.detail", "Journal Run Detail", "journal_run", []module.FieldDefinition{
					{Key: "period_key", Label: "Period", LabelI18n: localize("Period", "Periode"), Path: "values.period_key", Type: "string"},
					{Key: "template_code", Label: "Template Code", LabelI18n: localize("Template Code", "Kode Template"), Path: "values.template_code", Type: "string"},
					{Key: "template_name", Label: "Template Name", LabelI18n: localize("Template Name", "Nama Template"), Path: "values.template_name", Type: "string"},
					{Key: "journal_kind", Label: "Journal Kind", LabelI18n: localize("Journal Kind", "Jenis Jurnal"), Path: "values.journal_kind", Type: "string"},
					{Key: "cadence", Label: "Cadence", LabelI18n: localize("Cadence", "Cadence"), Path: "values.cadence", Type: "string"},
					{Key: "posting_date", Label: "Posting Date", LabelI18n: localize("Posting Date", "Tanggal Posting"), Path: "values.posting_date", Type: "string"},
					{Key: "generated_posting_id", Label: "Posting ID", LabelI18n: localize("Posting ID", "ID Posting"), Path: "values.generated_posting_id", Type: "string"},
					{Key: "generated_posting_number", Label: "Posting Number", LabelI18n: localize("Posting Number", "Nomor Posting"), Path: "values.generated_posting_number", Type: "string"},
					{Key: "generated_posting_status", Label: "Posting Status", LabelI18n: localize("Posting Status", "Status Posting"), Path: "values.generated_posting_status", Type: "string"},
					{Key: "reversal_status", Label: "Reversal Status", LabelI18n: localize("Reversal Status", "Status Reversal"), Path: "values.reversal_status", Type: "string"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status", Type: "string"},
				}),
				commercialModelListView("finance.period_tasks.list", "Period Close Tasks", "accounting_period_task", []module.ColumnDefinition{
					{Key: "period_key", Label: "Period", LabelI18n: localize("Period", "Periode"), Path: "values.period_key"},
					{Key: "task_code", Label: "Task", LabelI18n: localize("Task", "Tugas"), Path: "values.task_code"},
					{Key: "label", Label: "Label", LabelI18n: localize("Label", "Label"), Path: "values.label"},
					{Key: "task_type", Label: "Type", LabelI18n: localize("Type", "Tipe"), Path: "values.task_type"},
					{Key: "required", Label: "Required", LabelI18n: localize("Required", "Wajib"), Path: "values.required"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status"},
				}, []string{"pending", "completed", "waived"}),
				commercialModelDetailView("finance.period_tasks.detail", "Period Task Detail", "accounting_period_task", []module.FieldDefinition{
					{Key: "period_key", Label: "Period", LabelI18n: localize("Period", "Periode"), Path: "values.period_key", Type: "string"},
					{Key: "task_code", Label: "Task Code", LabelI18n: localize("Task Code", "Kode Tugas"), Path: "values.task_code", Type: "string"},
					{Key: "label", Label: "Label", LabelI18n: localize("Label", "Label"), Path: "values.label", Type: "string"},
					{Key: "task_type", Label: "Task Type", LabelI18n: localize("Task Type", "Tipe Tugas"), Path: "values.task_type", Type: "string"},
					{Key: "required", Label: "Required", LabelI18n: localize("Required", "Wajib"), Path: "values.required", Type: "bool"},
					{Key: "journal_template_id", Label: "Journal Template ID", LabelI18n: localize("Journal Template ID", "ID Template Jurnal"), Path: "values.journal_template_id", Type: "string"},
					{Key: "journal_run_id", Label: "Journal Run ID", LabelI18n: localize("Journal Run ID", "ID Run Jurnal"), Path: "values.journal_run_id", Type: "string"},
					{Key: "posting_id", Label: "Posting ID", LabelI18n: localize("Posting ID", "ID Posting"), Path: "values.posting_id", Type: "string"},
					{Key: "posting_number", Label: "Posting Number", LabelI18n: localize("Posting Number", "Nomor Posting"), Path: "values.posting_number", Type: "string"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status", Type: "string"},
					{Key: "completed_at", Label: "Completed At", LabelI18n: localize("Completed At", "Diselesaikan Pada"), Path: "values.completed_at", Type: "string"},
					{Key: "completed_by", Label: "Completed By", LabelI18n: localize("Completed By", "Diselesaikan Oleh"), Path: "values.completed_by", Type: "string"},
					{Key: "note", Label: "Note", LabelI18n: localize("Note", "Catatan"), Path: "values.note", Type: "string"},
				}),
			},
			CustomEntries: []module.CustomEntryDefinition{
				{Key: "finance.period_close", Title: "Period Close", TitleI18n: localize("Period Close", "Tutup Periode"), RoutePath: "/finance/period-close", BundleKey: "finance-reports", ComponentExport: "render", RequiredPermissions: []string{"finance.read", "accounting_period.read"}},
				{Key: "finance.trial_balance", Title: "Trial Balance", TitleI18n: localize("Trial Balance", "Neraca Saldo"), RoutePath: "/finance/trial-balance", BundleKey: "finance-reports", ComponentExport: "render", RequiredPermissions: []string{"finance.read"}},
				{Key: "finance.profit_and_loss", Title: "Profit and Loss", TitleI18n: localize("Profit and Loss", "Laba Rugi"), RoutePath: "/finance/profit-and-loss", BundleKey: "finance-reports", ComponentExport: "render", RequiredPermissions: []string{"finance.read"}},
				{Key: "finance.balance_sheet", Title: "Balance Sheet", TitleI18n: localize("Balance Sheet", "Neraca"), RoutePath: "/finance/balance-sheet", BundleKey: "finance-reports", ComponentExport: "render", RequiredPermissions: []string{"finance.read"}},
				{Key: "finance.tax_summary", Title: "Tax Summary", TitleI18n: localize("Tax Summary", "Ringkasan Pajak"), RoutePath: "/finance/tax-summary", BundleKey: "finance-reports", ComponentExport: "render", RequiredPermissions: []string{"finance.read"}},
				{Key: "finance.ar_aging", Title: "AR Aging", TitleI18n: localize("AR Aging", "Umur Piutang"), RoutePath: "/finance/ar-aging", BundleKey: "finance-reports", ComponentExport: "render", RequiredPermissions: []string{"finance.read", "document.read"}},
				{Key: "finance.ap_aging", Title: "AP Aging", TitleI18n: localize("AP Aging", "Umur Utang"), RoutePath: "/finance/ap-aging", BundleKey: "finance-reports", ComponentExport: "render", RequiredPermissions: []string{"finance.read", "document.read"}},
				{Key: "finance.ar_reconciliation", Title: "AR Reconciliation", TitleI18n: localize("AR Reconciliation", "Rekonsiliasi Piutang"), RoutePath: "/finance/ar-reconciliation", BundleKey: "finance-reports", ComponentExport: "render", RequiredPermissions: []string{"finance.read", "document.read"}},
				{Key: "finance.ap_reconciliation", Title: "AP Reconciliation", TitleI18n: localize("AP Reconciliation", "Rekonsiliasi Utang"), RoutePath: "/finance/ap-reconciliation", BundleKey: "finance-reports", ComponentExport: "render", RequiredPermissions: []string{"finance.read", "document.read"}},
				{Key: "finance.journal_ledger", Title: "Journal Ledger", TitleI18n: localize("Journal Ledger", "Buku Jurnal"), RoutePath: "/finance/journal-ledger", BundleKey: "finance-reports", ComponentExport: "render", RequiredPermissions: []string{"finance.read", "document.read"}},
			},
		},
		Bundles: []module.BundleDefinition{{
			Key:    "finance-reports",
			Script: httpx.FinanceReportsBundle(),
		}},
	}
}

func financeReportingCoreKernelPackManifests() []module.Manifest {
	return []module.Manifest{financeReportingCoreKernelPackManifest()}
}
