package app

import (
	"orbyte/internal/platform/model"
	"orbyte/internal/platform/module"
)

func financeCollectionsCoreKernelPackManifests() []module.Manifest {
	return []module.Manifest{financeCollectionsCoreKernelPackManifest()}
}

func financeCollectionsCoreKernelPackManifest() module.Manifest {
	return module.Manifest{
		Key:                    "finance_collections_core",
		Name:                   "Finance Collections Core",
		NameI18n:               localize("Finance Collections Core", "Inti Koleksi Keuangan"),
		Version:                "1.0.0",
		DomainFamily:           "business",
		DependencyRequirements: requiredModuleDependencies("finance_reporting_core", "commercial_core", "procurement_core"),
		AdminConsole: module.AdminConsoleDefinition{
			Title:           "Finance Collections Console",
			TitleI18n:       localize("Finance Collections Console", "Konsol Koleksi Keuangan"),
			Description:     "Statements, collections cases, settlement exceptions, and write-offs.",
			DescriptionI18n: localize("Statements, collections cases, settlement exceptions, and write-offs.", "Statement, kasus penagihan, pengecualian settlement, dan write-off."),
			Sections: []module.AdminConsoleSectionDefinition{
				{
					Key:       "operations",
					Title:     "Collections Operations",
					TitleI18n: localize("Collections Operations", "Operasi Penagihan"),
					Kind:      module.AdminConsoleSectionResourceLinks,
					Links: []module.AdminConsoleLinkDefinition{
						adminConsoleLink("ar_statements", "AR Statements", "Statement Piutang", "/ui/finance/ar-statements", "Open customer statements.", "Buka statement pelanggan.", "finance.read"),
						adminConsoleLink("ap_statements", "AP Statements", "Statement Utang", "/ui/finance/ap-statements", "Open vendor statements.", "Buka statement vendor.", "finance.read"),
						adminConsoleLink("collections", "Collections", "Penagihan", "/ui/finance/collections", "Open collections dashboard.", "Buka dashboard penagihan.", "finance.read"),
						adminConsoleLink("settlement_exceptions", "Settlement Exceptions", "Pengecualian Settlement", "/ui/finance/settlement-exceptions", "Open settlement exceptions.", "Buka pengecualian settlement.", "finance.read"),
						adminConsoleLink("collection_cases", "Collection Cases", "Kasus Penagihan", "/ui/finance/collection-cases", "Review collection case records.", "Tinjau record kasus penagihan.", "collection_case.list"),
					},
				},
			},
		},
		Models: []model.Definition{
			{
				Key:                 "party_statement_run",
				DisplayName:         "Party Statement Run",
				DisplayNameI18n:     localize("Party Statement Run", "Run Statement Pelanggan"),
				OwnerModuleKey:      "finance_collections_core",
				Version:             "v1",
				CreatePermissionKey: "party_statement_run.create",
				ListPermissionKey:   "party_statement_run.list",
				ReadPermissionKey:   "party_statement_run.read",
				UpdatePermissionKey: "party_statement_run.update",
				DefaultSort:         "as_of_date",
				Fields: []model.FieldDefinition{
					{Key: "organization_id", Label: "Organization", LabelI18n: localize("Organization", "Organisasi"), Type: "string", Required: true},
					{Key: "location_id", Label: "Location", LabelI18n: localize("Location", "Lokasi"), Type: "string"},
					{Key: "party_id", Label: "Party", LabelI18n: localize("Party", "Pihak"), Type: "string", Required: true},
					{Key: "counterparty_name", Label: "Customer", LabelI18n: localize("Customer", "Pelanggan"), Type: "string"},
					{Key: "as_of_date", Label: "As Of", LabelI18n: localize("As Of", "Per Tanggal"), Type: "string", Required: true},
					{Key: "open_amount_total", Label: "Open Amount", LabelI18n: localize("Open Amount", "Saldo Terbuka"), Type: "number"},
					{Key: "overdue_amount_total", Label: "Overdue Amount", LabelI18n: localize("Overdue Amount", "Saldo Lewat Jatuh Tempo"), Type: "number"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Type: "string", DefaultValue: "issued"},
					{Key: "statement_snapshot", Label: "Snapshot", LabelI18n: localize("Snapshot", "Snapshot"), Type: "object"},
				},
			},
			{
				Key:                 "vendor_statement_run",
				DisplayName:         "Vendor Statement Run",
				DisplayNameI18n:     localize("Vendor Statement Run", "Run Statement Vendor"),
				OwnerModuleKey:      "finance_collections_core",
				Version:             "v1",
				CreatePermissionKey: "vendor_statement_run.create",
				ListPermissionKey:   "vendor_statement_run.list",
				ReadPermissionKey:   "vendor_statement_run.read",
				UpdatePermissionKey: "vendor_statement_run.update",
				DefaultSort:         "as_of_date",
				Fields: []model.FieldDefinition{
					{Key: "organization_id", Label: "Organization", LabelI18n: localize("Organization", "Organisasi"), Type: "string", Required: true},
					{Key: "location_id", Label: "Location", LabelI18n: localize("Location", "Lokasi"), Type: "string"},
					{Key: "vendor_id", Label: "Vendor", LabelI18n: localize("Vendor", "Vendor"), Type: "string", Required: true},
					{Key: "counterparty_name", Label: "Vendor Name", LabelI18n: localize("Vendor Name", "Nama Vendor"), Type: "string"},
					{Key: "as_of_date", Label: "As Of", LabelI18n: localize("As Of", "Per Tanggal"), Type: "string", Required: true},
					{Key: "open_amount_total", Label: "Open Amount", LabelI18n: localize("Open Amount", "Saldo Terbuka"), Type: "number"},
					{Key: "overdue_amount_total", Label: "Overdue Amount", LabelI18n: localize("Overdue Amount", "Saldo Lewat Jatuh Tempo"), Type: "number"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Type: "string", DefaultValue: "issued"},
					{Key: "statement_snapshot", Label: "Snapshot", LabelI18n: localize("Snapshot", "Snapshot"), Type: "object"},
				},
			},
			{
				Key:                 "collection_case",
				DisplayName:         "Collection Case",
				DisplayNameI18n:     localize("Collection Case", "Kasus Penagihan"),
				OwnerModuleKey:      "finance_collections_core",
				Version:             "v1",
				CreatePermissionKey: "collection_case.create",
				ListPermissionKey:   "collection_case.list",
				ReadPermissionKey:   "collection_case.read",
				UpdatePermissionKey: "collection_case.update",
				DefaultSort:         "counterparty_name",
				Fields: []model.FieldDefinition{
					{Key: "organization_id", Label: "Organization", LabelI18n: localize("Organization", "Organisasi"), Type: "string", Required: true},
					{Key: "location_id", Label: "Location", LabelI18n: localize("Location", "Lokasi"), Type: "string"},
					{Key: "kind", Label: "Kind", LabelI18n: localize("Kind", "Jenis"), Type: "string", Required: true},
					{Key: "counterparty_id", Label: "Counterparty", LabelI18n: localize("Counterparty", "Mitra"), Type: "string", Required: true},
					{Key: "counterparty_name", Label: "Counterparty Name", LabelI18n: localize("Counterparty Name", "Nama Mitra"), Type: "string"},
					{Key: "source_document_ids", Label: "Source Documents", LabelI18n: localize("Source Documents", "Dokumen Sumber"), Type: "object"},
					{Key: "source_document_numbers", Label: "Source Numbers", LabelI18n: localize("Source Numbers", "Nomor Sumber"), Type: "object"},
					{Key: "settlement_exception_ids", Label: "Settlement Exceptions", LabelI18n: localize("Settlement Exceptions", "Pengecualian Settlement"), Type: "object"},
					{Key: "assignee_user_id", Label: "Assignee", LabelI18n: localize("Assignee", "Penanggung Jawab"), Type: "string"},
					{Key: "follow_up_date", Label: "Follow Up Date", LabelI18n: localize("Follow Up Date", "Tanggal Tindak Lanjut"), Type: "string"},
					{Key: "promised_payment_date", Label: "Promised Payment Date", LabelI18n: localize("Promised Payment Date", "Tanggal Janji Bayar"), Type: "string"},
					{Key: "last_contact_date", Label: "Last Contact", LabelI18n: localize("Last Contact", "Kontak Terakhir"), Type: "string"},
					{Key: "total_open_amount", Label: "Open Amount", LabelI18n: localize("Open Amount", "Saldo Terbuka"), Type: "number"},
					{Key: "overdue_amount", Label: "Overdue Amount", LabelI18n: localize("Overdue Amount", "Saldo Lewat Jatuh Tempo"), Type: "number"},
					{Key: "oldest_due_date", Label: "Oldest Due Date", LabelI18n: localize("Oldest Due Date", "Tanggal Jatuh Tempo Tertua"), Type: "string"},
					{Key: "priority", Label: "Priority", LabelI18n: localize("Priority", "Prioritas"), Type: "string", DefaultValue: "normal"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Type: "string", DefaultValue: "open"},
					{Key: "note", Label: "Note", LabelI18n: localize("Note", "Catatan"), Type: "string"},
				},
			},
			{
				Key:                 "settlement_exception",
				DisplayName:         "Settlement Exception",
				DisplayNameI18n:     localize("Settlement Exception", "Pengecualian Settlement"),
				OwnerModuleKey:      "finance_collections_core",
				Version:             "v1",
				CreatePermissionKey: "settlement_exception.create",
				ListPermissionKey:   "settlement_exception.list",
				ReadPermissionKey:   "settlement_exception.read",
				UpdatePermissionKey: "settlement_exception.update",
				DefaultSort:         "counterparty_name",
				Fields: []model.FieldDefinition{
					{Key: "organization_id", Label: "Organization", LabelI18n: localize("Organization", "Organisasi"), Type: "string", Required: true},
					{Key: "location_id", Label: "Location", LabelI18n: localize("Location", "Lokasi"), Type: "string"},
					{Key: "source_key", Label: "Source Key", LabelI18n: localize("Source Key", "Kunci Sumber"), Type: "string", Required: true},
					{Key: "kind", Label: "Kind", LabelI18n: localize("Kind", "Jenis"), Type: "string", Required: true},
					{Key: "exception_type", Label: "Exception Type", LabelI18n: localize("Exception Type", "Tipe Pengecualian"), Type: "string", Required: true},
					{Key: "as_of_date", Label: "As Of", LabelI18n: localize("As Of", "Per Tanggal"), Type: "string", Required: true},
					{Key: "counterparty_id", Label: "Counterparty", LabelI18n: localize("Counterparty", "Mitra"), Type: "string"},
					{Key: "counterparty_name", Label: "Counterparty Name", LabelI18n: localize("Counterparty Name", "Nama Mitra"), Type: "string"},
					{Key: "account_code", Label: "Account", LabelI18n: localize("Account", "Akun"), Type: "string"},
					{Key: "source_document_id", Label: "Source Document ID", LabelI18n: localize("Source Document ID", "ID Dokumen Sumber"), Type: "string"},
					{Key: "source_document_number", Label: "Source Document", LabelI18n: localize("Source Document", "Dokumen Sumber"), Type: "string"},
					{Key: "source_payment_id", Label: "Source Payment ID", LabelI18n: localize("Source Payment ID", "ID Pembayaran Sumber"), Type: "string"},
					{Key: "source_payment_number", Label: "Source Payment", LabelI18n: localize("Source Payment", "Pembayaran Sumber"), Type: "string"},
					{Key: "open_amount", Label: "Open Amount", LabelI18n: localize("Open Amount", "Saldo Terbuka"), Type: "number"},
					{Key: "unapplied_amount", Label: "Unapplied Amount", LabelI18n: localize("Unapplied Amount", "Jumlah Belum Dialokasikan"), Type: "number"},
					{Key: "collection_case_id", Label: "Collection Case", LabelI18n: localize("Collection Case", "Kasus Penagihan"), Type: "string"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Type: "string", DefaultValue: "open"},
					{Key: "note", Label: "Note", LabelI18n: localize("Note", "Catatan"), Type: "string"},
				},
			},
		},
		Security: module.SecurityDefinition{
			Permissions: append(
				append(
					append(
						commercialModelPermissions("party_statement_run", "Party Statement Run"),
						commercialModelPermissions("vendor_statement_run", "Vendor Statement Run")...,
					),
					append(
						commercialModelPermissions("collection_case", "Collection Case"),
						commercialModelPermissions("settlement_exception", "Settlement Exception")...,
					)...,
				),
				[]module.PermissionDefinition{
					{Key: "finance.collections.manage", Action: "manage", Resource: "finance_collections", DisplayName: "Manage Finance Collections", DisplayNameI18n: localize("Manage Finance Collections", "Kelola Penagihan Keuangan")},
					{Key: "finance.writeoff", Action: "writeoff", Resource: "finance", DisplayName: "Create Finance Write-offs", DisplayNameI18n: localize("Create Finance Write-offs", "Buat Write-off Keuangan")},
				}...,
			),
			RoleTemplates: []module.RoleTemplateDefinition{
				{
					Key:           "finance_collections_manager",
					Name:          "Finance Collections Manager",
					NameI18n:      localize("Finance Collections Manager", "Manajer Penagihan Keuangan"),
					AllowedScopes: []string{"deployment", "organization", "location"},
					PermissionKeys: []string{
						"party_statement_run.create", "party_statement_run.list", "party_statement_run.read", "party_statement_run.update",
						"vendor_statement_run.create", "vendor_statement_run.list", "vendor_statement_run.read", "vendor_statement_run.update",
						"collection_case.create", "collection_case.list", "collection_case.read", "collection_case.update",
						"settlement_exception.create", "settlement_exception.list", "settlement_exception.read", "settlement_exception.update",
						"finance.read", "finance.collections.manage", "finance.writeoff", "document.read", "document.create", "document.update_draft",
					},
				},
			},
		},
		Frontend: module.FrontendDefinition{
			Menus: []module.MenuDefinition{
				{Key: "finance.ar_statements", Label: "AR Statements", LabelI18n: localize("AR Statements", "Statement Piutang"), ActionKey: "finance.ar_statements", Order: 102, RequiredPermissions: []string{"finance.read", "document.read"}},
				{Key: "finance.ap_statements", Label: "AP Statements", LabelI18n: localize("AP Statements", "Statement Utang"), ActionKey: "finance.ap_statements", Order: 103, RequiredPermissions: []string{"finance.read", "document.read"}},
				{Key: "finance.collections", Label: "Collections", LabelI18n: localize("Collections", "Penagihan"), ActionKey: "finance.collections", Order: 104, RequiredPermissions: []string{"finance.read", "collection_case.read"}},
				{Key: "finance.settlement_exceptions", Label: "Settlement Exceptions", LabelI18n: localize("Settlement Exceptions", "Pengecualian Settlement"), ActionKey: "finance.settlement_exceptions", Order: 105, RequiredPermissions: []string{"finance.read", "settlement_exception.read"}},
				{Key: "finance.collection_cases", Label: "Collection Cases", LabelI18n: localize("Collection Cases", "Kasus Penagihan"), ActionKey: "finance.collection_cases.list", Order: 106, RequiredPermissions: []string{"collection_case.list"}},
			},
			Actions: []module.ActionDefinition{
				{Key: "finance.ar_statements", Label: "AR Statements", LabelI18n: localize("AR Statements", "Statement Piutang"), Kind: "navigate", RoutePath: "/finance/ar-statements", CustomEntryKey: "finance.ar_statements", RenderMode: module.RenderModeCustom, RequiredPermissions: []string{"finance.read", "document.read"}},
				{Key: "finance.ap_statements", Label: "AP Statements", LabelI18n: localize("AP Statements", "Statement Utang"), Kind: "navigate", RoutePath: "/finance/ap-statements", CustomEntryKey: "finance.ap_statements", RenderMode: module.RenderModeCustom, RequiredPermissions: []string{"finance.read", "document.read"}},
				{Key: "finance.collections", Label: "Collections", LabelI18n: localize("Collections", "Penagihan"), Kind: "navigate", RoutePath: "/finance/collections", CustomEntryKey: "finance.collections", RenderMode: module.RenderModeCustom, RequiredPermissions: []string{"finance.read", "collection_case.read"}},
				{Key: "finance.settlement_exceptions", Label: "Settlement Exceptions", LabelI18n: localize("Settlement Exceptions", "Pengecualian Settlement"), Kind: "navigate", RoutePath: "/finance/settlement-exceptions", CustomEntryKey: "finance.settlement_exceptions", RenderMode: module.RenderModeCustom, RequiredPermissions: []string{"finance.read", "settlement_exception.read"}},
				{Key: "finance.collection_cases.list", Label: "Collection Cases", LabelI18n: localize("Collection Cases", "Kasus Penagihan"), Kind: "navigate", RoutePath: "/finance/collection-cases", ViewKey: "finance.collection_cases.list", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"collection_case.list"}},
				{Key: "finance.collection_cases.detail", Label: "Collection Case Detail", LabelI18n: localize("Collection Case Detail", "Detail Kasus Penagihan"), Kind: "navigate", RoutePath: "/finance/collection-cases/detail", ViewKey: "finance.collection_cases.detail", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"collection_case.read"}},
				{Key: "finance.collection_cases.form", Label: "Collection Case Form", LabelI18n: localize("Collection Case Form", "Form Kasus Penagihan"), Kind: "navigate", RoutePath: "/finance/collection-cases/form", ViewKey: "finance.collection_cases.form", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"collection_case.update"}},
			},
			Views: []module.ViewDefinition{
				commercialModelListView("finance.collection_cases.list", "Collection Cases", "collection_case", []module.ColumnDefinition{
					{Key: "counterparty_name", Label: "Counterparty", LabelI18n: localize("Counterparty", "Mitra"), Path: "values.counterparty_name"},
					{Key: "kind", Label: "Kind", LabelI18n: localize("Kind", "Jenis"), Path: "values.kind"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status"},
					{Key: "assignee_user_id", Label: "Assignee", LabelI18n: localize("Assignee", "Penanggung Jawab"), Path: "values.assignee_user_id"},
					{Key: "total_open_amount", Label: "Open", LabelI18n: localize("Open", "Terbuka"), Path: "values.total_open_amount"},
					{Key: "overdue_amount", Label: "Overdue", LabelI18n: localize("Overdue", "Lewat Jatuh Tempo"), Path: "values.overdue_amount"},
				}, []string{"open", "promised", "disputed", "escalated", "resolved", "closed"}),
				commercialModelDetailView("finance.collection_cases.detail", "Collection Case Detail", "collection_case", []module.FieldDefinition{
					{Key: "kind", Label: "Kind", LabelI18n: localize("Kind", "Jenis"), Path: "values.kind", Type: "string"},
					{Key: "counterparty_name", Label: "Counterparty", LabelI18n: localize("Counterparty", "Mitra"), Path: "values.counterparty_name", Type: "string"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status", Type: "string"},
					{Key: "priority", Label: "Priority", LabelI18n: localize("Priority", "Prioritas"), Path: "values.priority", Type: "string"},
					{Key: "assignee_user_id", Label: "Assignee", LabelI18n: localize("Assignee", "Penanggung Jawab"), Path: "values.assignee_user_id", Type: "string"},
					{Key: "follow_up_date", Label: "Follow Up Date", LabelI18n: localize("Follow Up Date", "Tanggal Tindak Lanjut"), Path: "values.follow_up_date", Type: "string"},
					{Key: "promised_payment_date", Label: "Promised Payment Date", LabelI18n: localize("Promised Payment Date", "Tanggal Janji Bayar"), Path: "values.promised_payment_date", Type: "string"},
					{Key: "last_contact_date", Label: "Last Contact", LabelI18n: localize("Last Contact", "Kontak Terakhir"), Path: "values.last_contact_date", Type: "string"},
					{Key: "total_open_amount", Label: "Open Amount", LabelI18n: localize("Open Amount", "Saldo Terbuka"), Path: "values.total_open_amount", Type: "number"},
					{Key: "overdue_amount", Label: "Overdue Amount", LabelI18n: localize("Overdue Amount", "Saldo Lewat Jatuh Tempo"), Path: "values.overdue_amount", Type: "number"},
					{Key: "oldest_due_date", Label: "Oldest Due Date", LabelI18n: localize("Oldest Due Date", "Tanggal Jatuh Tempo Tertua"), Path: "values.oldest_due_date", Type: "string"},
					{Key: "source_document_numbers", Label: "Source Documents", LabelI18n: localize("Source Documents", "Dokumen Sumber"), Path: "values.source_document_numbers", Type: "object"},
					{Key: "note", Label: "Note", LabelI18n: localize("Note", "Catatan"), Path: "values.note", Type: "string"},
				}),
				commercialModelFormView("finance.collection_cases.form", "Collection Case Form", "collection_case", []module.FieldDefinition{
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status", Type: "string", Widget: "select", Options: []string{"open", "promised", "disputed", "escalated", "resolved", "closed"}},
					{Key: "priority", Label: "Priority", LabelI18n: localize("Priority", "Prioritas"), Path: "values.priority", Type: "string", Widget: "select", Options: []string{"low", "normal", "high", "critical"}},
					{Key: "assignee_user_id", Label: "Assignee", LabelI18n: localize("Assignee", "Penanggung Jawab"), Path: "values.assignee_user_id", Type: "string", Widget: "text"},
					{Key: "follow_up_date", Label: "Follow Up Date", LabelI18n: localize("Follow Up Date", "Tanggal Tindak Lanjut"), Path: "values.follow_up_date", Type: "string", Widget: "text"},
					{Key: "promised_payment_date", Label: "Promised Payment Date", LabelI18n: localize("Promised Payment Date", "Tanggal Janji Bayar"), Path: "values.promised_payment_date", Type: "string", Widget: "text"},
					{Key: "last_contact_date", Label: "Last Contact", LabelI18n: localize("Last Contact", "Kontak Terakhir"), Path: "values.last_contact_date", Type: "string", Widget: "text"},
					{Key: "note", Label: "Note", LabelI18n: localize("Note", "Catatan"), Path: "values.note", Type: "string", Widget: "textarea"},
				}),
			},
			CustomEntries: []module.CustomEntryDefinition{
				{Key: "finance.ar_statements", Title: "AR Statements", TitleI18n: localize("AR Statements", "Statement Piutang"), RoutePath: "/finance/ar-statements", BundleKey: "finance-reports", ComponentExport: "render", RequiredPermissions: []string{"finance.read", "document.read"}},
				{Key: "finance.ap_statements", Title: "AP Statements", TitleI18n: localize("AP Statements", "Statement Utang"), RoutePath: "/finance/ap-statements", BundleKey: "finance-reports", ComponentExport: "render", RequiredPermissions: []string{"finance.read", "document.read"}},
				{Key: "finance.collections", Title: "Collections", TitleI18n: localize("Collections", "Penagihan"), RoutePath: "/finance/collections", BundleKey: "finance-reports", ComponentExport: "render", RequiredPermissions: []string{"finance.read", "collection_case.read"}},
				{Key: "finance.settlement_exceptions", Title: "Settlement Exceptions", TitleI18n: localize("Settlement Exceptions", "Pengecualian Settlement"), RoutePath: "/finance/settlement-exceptions", BundleKey: "finance-reports", ComponentExport: "render", RequiredPermissions: []string{"finance.read", "settlement_exception.read"}},
			},
		},
	}
}
