package app

import (
	"orbyte/internal/platform/config"
	"orbyte/internal/platform/module"
)

func platformCoreKernelPackManifest(httpDefinition, acpDefinition, mcpDefinition config.Definition) module.Manifest {
	return module.Manifest{
		Key:                 "platform.core",
		Name:                "Platform Core",
		NameI18n:            localize("Platform Core", "Inti Platform"),
		Version:             "1.0.0",
		DomainFamily:        "platform",
		OwnedPermissionKeys: []string{"platform.context.read", "agent.workspace.use", "module.read", "module.manage", "configuration.read", "configuration.manage", "search.manage", "template.read", "template.manage", "template.publish", "template.bind", "template.render"},
		ConfigDefinitions:   []config.Definition{httpDefinition, acpDefinition, mcpDefinition},
		AdminConsole: module.AdminConsoleDefinition{
			Title:           "Platform Core Console",
			TitleI18n:       localize("Platform Core Console", "Konsol Inti Platform"),
			Description:     "Core platform settings and shortcuts for module, configuration, template, and observability operations.",
			DescriptionI18n: localize("Core platform settings and shortcuts for module, configuration, template, and observability operations.", "Pengaturan inti platform dan pintasan untuk operasi modul, konfigurasi, template, dan observabilitas."),
			Sections: []module.AdminConsoleSectionDefinition{
				{
					Key:                 "http_settings",
					Title:               "HTTP Settings",
					TitleI18n:           localize("HTTP Settings", "Pengaturan HTTP"),
					Description:         "Deployment-level listener and origin settings.",
					DescriptionI18n:     localize("Deployment-level listener and origin settings.", "Pengaturan listener dan origin tingkat deployment."),
					Kind:                module.AdminConsoleSectionSettingsForm,
					ConfigKey:           "platform.http",
					RequiredPermissions: []string{"configuration.read"},
				},
				{
					Key:       "admin_operations",
					Title:     "Admin Operations",
					TitleI18n: localize("Admin Operations", "Operasi Admin"),
					Kind:      module.AdminConsoleSectionResourceLinks,
					Links: []module.AdminConsoleLinkDefinition{
						adminConsoleLink("modules", "Modules", "Modul", "/admin/modules", "Open the module inventory.", "Buka inventaris modul.", "module.read"),
						adminConsoleLink("config", "Configuration", "Konfigurasi", "/admin/config", "Open global configuration entries.", "Buka entri konfigurasi global.", "configuration.read"),
						adminConsoleLink("mcp", "MCP", "MCP", "/admin/mcp", "Inspect MCP endpoints and tool controls.", "Periksa endpoint MCP dan kontrol tool.", "configuration.read"),
						adminConsoleLink("acp", "ACP", "ACP", "/admin/acp", "Configure ACP providers for the agent surface.", "Konfigurasikan penyedia ACP untuk surface agen.", "configuration.read"),
						adminConsoleLink("definitions", "Definitions", "Definisi", "/admin/definitions", "Open platform definitions.", "Buka definisi platform.", "configuration.read"),
						adminConsoleLink("audit", "Audit Trail", "Jejak Audit", "/admin/audit", "Search and inspect audit events.", "Cari dan periksa event audit.", "audit.read"),
						adminConsoleLink("observability", "Observability", "Observabilitas", "/admin/observability", "Open platform observability.", "Buka observabilitas platform.", "module.read"),
					},
				},
				{
					Key:       "template_operations",
					Title:     "Template Operations",
					TitleI18n: localize("Template Operations", "Operasi Template"),
					Kind:      module.AdminConsoleSectionTemplateLinks,
					Links: []module.AdminConsoleLinkDefinition{
						adminConsoleLink("templates", "Templates", "Template", "/admin/templates", "Open the template list and designer.", "Buka daftar dan perancang template.", "template.read"),
					},
				},
			},
		},
		Security: module.SecurityDefinition{
			Permissions: []module.PermissionDefinition{
				{Key: "platform.context.read", Action: "read", Resource: "context", DisplayName: "Read Platform Context", DisplayNameI18n: localize("Read Platform Context", "Lihat Konteks Platform")},
				{Key: "agent.workspace.use", Action: "use", Resource: "agent_workspace", DisplayName: "Use Agent Workspace", DisplayNameI18n: localize("Use Agent Workspace", "Gunakan Workspace Agen")},
				{Key: "module.read", Action: "read", Resource: "module", DisplayName: "Read Modules", DisplayNameI18n: localize("Read Modules", "Lihat Modul")},
				{Key: "module.manage", Action: "manage", Resource: "module", DisplayName: "Manage Modules", DisplayNameI18n: localize("Manage Modules", "Kelola Modul"), RiskLevel: "high"},
				{Key: "configuration.read", Action: "read", Resource: "configuration", DisplayName: "Read Configuration", DisplayNameI18n: localize("Read Configuration", "Lihat Konfigurasi")},
				{Key: "configuration.manage", Action: "manage", Resource: "configuration", DisplayName: "Manage Configuration", DisplayNameI18n: localize("Manage Configuration", "Kelola Konfigurasi"), RiskLevel: "high"},
				{Key: "search.manage", Action: "manage", Resource: "search", DisplayName: "Manage Search Indexes", DisplayNameI18n: localize("Manage Search Indexes", "Kelola Indeks Pencarian"), RiskLevel: "high"},
				{Key: "template.read", Action: "read", Resource: "template", DisplayName: "Read Templates", DisplayNameI18n: localize("Read Templates", "Lihat Template")},
				{Key: "template.manage", Action: "manage", Resource: "template", DisplayName: "Manage Templates", DisplayNameI18n: localize("Manage Templates", "Kelola Template"), RiskLevel: "high"},
				{Key: "template.publish", Action: "publish", Resource: "template", DisplayName: "Publish Templates", DisplayNameI18n: localize("Publish Templates", "Publikasikan Template"), RiskLevel: "high"},
				{Key: "template.bind", Action: "bind", Resource: "template", DisplayName: "Bind Templates", DisplayNameI18n: localize("Bind Templates", "Atur Binding Template"), RiskLevel: "high"},
				{Key: "template.render", Action: "render", Resource: "template_output", DisplayName: "Render Template Outputs", DisplayNameI18n: localize("Render Template Outputs", "Render Output Template")},
			},
			RoleTemplates: []module.RoleTemplateDefinition{{
				Key:            "platform_operator",
				Name:           "Platform Operator",
				NameI18n:       localize("Platform Operator", "Operator Platform"),
				AllowedScopes:  []string{"deployment"},
				PermissionKeys: []string{"platform.context.read", "agent.workspace.use", "module.read", "configuration.read", "template.read", "template.render"},
			}},
		},
		Frontend: module.FrontendDefinition{
			Menus: []module.MenuDefinition{
				{
					Key:                 "agent.workspace",
					Label:               "Agent",
					LabelI18n:           localize("Agent", "Agen"),
					ActionKey:           "agent.workspace",
					Order:               70,
					Surface:             module.UISurfaceAgent,
					RequiredPermissions: []string{"agent.workspace.use"},
				},
				{
					Key:                 "admin.modules",
					Label:               "Modules",
					LabelI18n:           localize("Modules", "Modul"),
					ActionKey:           "admin.modules",
					Order:               10,
					Surface:             module.UISurfaceAdmin,
					RequiredPermissions: []string{"module.read"},
				},
				{
					Key:                 "admin.auth",
					Label:               "Authentication",
					LabelI18n:           localize("Authentication", "Autentikasi"),
					ActionKey:           "admin.auth",
					Order:               20,
					Surface:             module.UISurfaceAdmin,
					RequiredPermissions: []string{"configuration.read"},
				},
				{
					Key:                 "admin.configuration",
					Label:               "Configuration",
					LabelI18n:           localize("Configuration", "Konfigurasi"),
					ActionKey:           "admin.configuration",
					Order:               30,
					Surface:             module.UISurfaceAdmin,
					RequiredPermissions: []string{"configuration.read"},
				},
				{
					Key:                 "admin.mcp",
					Label:               "MCP",
					LabelI18n:           localize("MCP", "MCP"),
					ActionKey:           "admin.mcp",
					Order:               32,
					Surface:             module.UISurfaceAdmin,
					RequiredPermissions: []string{"configuration.read"},
				},
				{
					Key:                 "admin.acp",
					Label:               "ACP",
					LabelI18n:           localize("ACP", "ACP"),
					ActionKey:           "admin.acp",
					Order:               33,
					Surface:             module.UISurfaceAdmin,
					RequiredPermissions: []string{"configuration.read"},
				},
				{
					Key:                 "admin.finance",
					Label:               "Finance",
					LabelI18n:           localize("Finance", "Keuangan"),
					ActionKey:           "admin.finance",
					Order:               35,
					Surface:             module.UISurfaceAdmin,
					RequiredPermissions: []string{"configuration.read"},
				},
				{
					Key:                 "admin.definitions",
					Label:               "Definitions",
					LabelI18n:           localize("Definitions", "Definisi"),
					ActionKey:           "admin.definitions",
					Order:               40,
					Surface:             module.UISurfaceAdmin,
					RequiredPermissions: []string{"configuration.read"},
				},
				{
					Key:                 "admin.templates",
					Label:               "Templates",
					LabelI18n:           localize("Templates", "Template"),
					ActionKey:           "admin.templates",
					Order:               45,
					Surface:             module.UISurfaceAdmin,
					RequiredPermissions: []string{"template.read"},
				},
				{
					Key:                 "admin.workflows",
					Label:               "Workflows",
					LabelI18n:           localize("Workflows", "Workflow"),
					ActionKey:           "admin.workflows",
					Order:               47,
					Surface:             module.UISurfaceAdmin,
					RequiredPermissions: []string{"configuration.read"},
				},
				{
					Key:                 "admin.security",
					Label:               "Security",
					LabelI18n:           localize("Security", "Keamanan"),
					ActionKey:           "admin.security",
					Order:               50,
					Surface:             module.UISurfaceAdmin,
					RequiredPermissions: []string{"configuration.read"},
				},
				{
					Key:                 "admin.audit",
					Label:               "Audit Trail",
					LabelI18n:           localize("Audit Trail", "Jejak Audit"),
					ActionKey:           "admin.audit",
					Order:               55,
					Surface:             module.UISurfaceAdmin,
					RequiredPermissions: []string{"audit.read"},
				},
				{
					Key:                 "admin.observability",
					Label:               "Observability",
					LabelI18n:           localize("Observability", "Observabilitas"),
					ActionKey:           "admin.observability",
					Order:               60,
					Surface:             module.UISurfaceAdmin,
					RequiredPermissions: []string{"module.read"},
				},
			},
			Views: []module.ViewDefinition{{
				Key:     "agent.workspace.view",
				Title:   "Agent Workspace",
				Kind:    "dashboard",
				Surface: module.UISurfaceAgent,
			}},
			Actions: []module.ActionDefinition{
				{
					Key:                 "agent.workspace",
					Label:               "Agent Workspace",
					LabelI18n:           localize("Agent Workspace", "Workspace Agen"),
					Kind:                "navigate",
					RoutePath:           "/agent/workspace",
					Surface:             module.UISurfaceAgent,
					ViewKey:             "agent.workspace.view",
					RenderMode:          module.RenderModeGeneric,
					RequiredPermissions: []string{"agent.workspace.use"},
				},
				{
					Key:                 "admin.modules",
					Label:               "Modules",
					LabelI18n:           localize("Modules", "Modul"),
					Kind:                "navigate",
					RoutePath:           "/admin/modules",
					Surface:             module.UISurfaceAdmin,
					RequiredPermissions: []string{"module.read"},
				},
				{
					Key:                 "admin.auth",
					Label:               "Authentication",
					LabelI18n:           localize("Authentication", "Autentikasi"),
					Kind:                "navigate",
					RoutePath:           "/admin/auth",
					Surface:             module.UISurfaceAdmin,
					RequiredPermissions: []string{"configuration.read"},
				},
				{
					Key:                 "admin.configuration",
					Label:               "Configuration",
					LabelI18n:           localize("Configuration", "Konfigurasi"),
					Kind:                "navigate",
					RoutePath:           "/admin/config",
					Surface:             module.UISurfaceAdmin,
					RequiredPermissions: []string{"configuration.read"},
				},
				{
					Key:                 "admin.mcp",
					Label:               "MCP",
					LabelI18n:           localize("MCP", "MCP"),
					Kind:                "navigate",
					RoutePath:           "/admin/mcp",
					Surface:             module.UISurfaceAdmin,
					RequiredPermissions: []string{"configuration.read"},
				},
				{
					Key:                 "admin.acp",
					Label:               "ACP",
					LabelI18n:           localize("ACP", "ACP"),
					Kind:                "navigate",
					RoutePath:           "/admin/acp",
					Surface:             module.UISurfaceAdmin,
					RequiredPermissions: []string{"configuration.read"},
				},
				{
					Key:                 "admin.finance",
					Label:               "Finance",
					LabelI18n:           localize("Finance", "Keuangan"),
					Kind:                "navigate",
					RoutePath:           "/admin/finance",
					Surface:             module.UISurfaceAdmin,
					RequiredPermissions: []string{"configuration.read"},
				},
				{
					Key:                 "admin.definitions",
					Label:               "Definitions",
					LabelI18n:           localize("Definitions", "Definisi"),
					Kind:                "navigate",
					RoutePath:           "/admin/definitions",
					Surface:             module.UISurfaceAdmin,
					RequiredPermissions: []string{"configuration.read"},
				},
				{
					Key:                 "admin.templates",
					Label:               "Templates",
					LabelI18n:           localize("Templates", "Template"),
					Kind:                "navigate",
					RoutePath:           "/admin/templates",
					Surface:             module.UISurfaceAdmin,
					RequiredPermissions: []string{"template.read"},
				},
				{
					Key:                 "admin.workflows",
					Label:               "Workflows",
					LabelI18n:           localize("Workflows", "Workflow"),
					Kind:                "navigate",
					RoutePath:           "/admin/workflows",
					Surface:             module.UISurfaceAdmin,
					RequiredPermissions: []string{"configuration.read"},
				},
				{
					Key:                 "admin.security",
					Label:               "Security",
					LabelI18n:           localize("Security", "Keamanan"),
					Kind:                "navigate",
					RoutePath:           "/admin/security",
					Surface:             module.UISurfaceAdmin,
					RequiredPermissions: []string{"configuration.read"},
				},
				{
					Key:                 "admin.audit",
					Label:               "Audit Trail",
					LabelI18n:           localize("Audit Trail", "Jejak Audit"),
					Kind:                "navigate",
					RoutePath:           "/admin/audit",
					Surface:             module.UISurfaceAdmin,
					RequiredPermissions: []string{"audit.read"},
				},
				{
					Key:                 "admin.observability",
					Label:               "Observability",
					LabelI18n:           localize("Observability", "Observabilitas"),
					Kind:                "navigate",
					RoutePath:           "/admin/observability",
					Surface:             module.UISurfaceAdmin,
					RequiredPermissions: []string{"module.read"},
				},
			},
		},
		Observability: module.ObservabilityDefinition{
			Metrics: []module.MetricDefinition{
				{Key: "http.requests.total", Type: "counter", Description: "Total HTTP requests"},
				{Key: "http.request.duration", Type: "timing", Description: "HTTP request duration"},
			},
			LogEvents: []module.LogEventDefinition{{
				Key: "http.request.completed", Category: "http", Severity: "info", RequiredFields: []string{"correlation_id", "method", "path", "status"},
			}},
		},
	}
}

func identityKernelPackManifest(authDefinition config.Definition) module.Manifest {
	return module.Manifest{
		Key:          "identity",
		Name:         "Identity and Access",
		NameI18n:     localize("Identity and Access", "Identitas dan Akses"),
		Version:      "1.0.0",
		DomainFamily: "platform",
		DependencyRequirements: []module.DependencyRequirement{{
			ModuleKey: "platform.core", VersionRange: ">=1.0.0,<2.0.0", Kind: module.DependencyKindRequired,
		}},
		OwnedPermissionKeys: []string{"identity.manage_sessions", "identity.manage_users"},
		ConfigDefinitions:   []config.Definition{authDefinition},
		AdminConsole: module.AdminConsoleDefinition{
			Title:           "Identity Console",
			TitleI18n:       localize("Identity Console", "Konsol Identitas"),
			Description:     "Authentication policy, security operations, and identity administration shortcuts.",
			DescriptionI18n: localize("Authentication policy, security operations, and identity administration shortcuts.", "Kebijakan autentikasi, operasi keamanan, dan pintasan administrasi identitas."),
			Sections: []module.AdminConsoleSectionDefinition{
				{
					Key:                 "auth_policy",
					Title:               "Authentication Policy",
					TitleI18n:           localize("Authentication Policy", "Kebijakan Autentikasi"),
					Description:         "Password, session, sign-in, and 2FA policy settings.",
					DescriptionI18n:     localize("Password, session, sign-in, and 2FA policy settings.", "Pengaturan kebijakan kata sandi, sesi, masuk, dan 2FA."),
					Kind:                module.AdminConsoleSectionSettingsForm,
					ConfigKey:           "identity.auth",
					RequiredPermissions: []string{"configuration.read"},
				},
				{
					Key:       "identity_admin",
					Title:     "Identity Administration",
					TitleI18n: localize("Identity Administration", "Administrasi Identitas"),
					Kind:      module.AdminConsoleSectionResourceLinks,
					Links: []module.AdminConsoleLinkDefinition{
						adminConsoleLink("auth", "Authentication", "Autentikasi", "/admin/auth", "Open authentication settings.", "Buka pengaturan autentikasi.", "configuration.read"),
						adminConsoleLink("security", "Security", "Keamanan", "/admin/security", "Open policy and security management.", "Buka manajemen kebijakan dan keamanan.", "configuration.read"),
						adminConsoleLink("modules", "Modules", "Modul", "/admin/modules", "Return to the module inventory.", "Kembali ke inventaris modul.", "module.read"),
					},
				},
			},
		},
		Security: module.SecurityDefinition{
			Permissions: []module.PermissionDefinition{
				{Key: "identity.manage_sessions", Action: "manage", Resource: "session", DisplayName: "Manage Sessions", DisplayNameI18n: localize("Manage Sessions", "Kelola Sesi"), RiskLevel: "high"},
				{Key: "identity.manage_users", Action: "manage", Resource: "user", DisplayName: "Manage Users", DisplayNameI18n: localize("Manage Users", "Kelola Pengguna"), RiskLevel: "high"},
			},
		},
	}
}
