package app

import (
	"orbyte/internal/platform/model"
	"orbyte/internal/platform/module"
)

func financeAssetCoreKernelPackManifests() []module.Manifest {
	return []module.Manifest{financeAssetCoreKernelPackManifest()}
}

func financeAssetCoreKernelPackManifest() module.Manifest {
	return module.Manifest{
		Key:                    "finance_asset_core",
		Name:                   "Finance Asset Core",
		NameI18n:               localize("Finance Asset Core", "Inti Aset Keuangan"),
		Version:                "1.0.0",
		DomainFamily:           "business",
		DependencyRequirements: requiredModuleDependencies("finance_reporting_core", "procurement_core"),
		AdminConsole: module.AdminConsoleDefinition{
			Title:           "Assets and Prepaids Console",
			TitleI18n:       localize("Assets and Prepaids Console", "Konsol Aset dan Biaya Dibayar Dimuka"),
			Description:     "Fixed assets, prepaid expenses, schedules, and periodic depreciation or amortization journals.",
			DescriptionI18n: localize("Fixed assets, prepaid expenses, schedules, and periodic depreciation or amortization journals.", "Aset tetap, biaya dibayar dimuka, jadwal, dan jurnal depresiasi atau amortisasi berkala."),
			Sections: []module.AdminConsoleSectionDefinition{
				{
					Key:       "assets",
					Title:     "Asset Operations",
					TitleI18n: localize("Asset Operations", "Operasi Aset"),
					Kind:      module.AdminConsoleSectionResourceLinks,
					Links: []module.AdminConsoleLinkDefinition{
						adminConsoleLink("fixed_assets", "Fixed Assets", "Aset Tetap", "/ui/finance/fixed-assets", "Review fixed assets.", "Tinjau aset tetap.", "fixed_asset.list"),
						adminConsoleLink("fixed_asset_schedules", "Fixed Asset Schedules", "Jadwal Aset Tetap", "/ui/finance/fixed-asset-schedules", "Review fixed asset schedules.", "Tinjau jadwal aset tetap.", "fixed_asset_schedule.list"),
						adminConsoleLink("prepaid_expenses", "Prepaid Expenses", "Biaya Dibayar Dimuka", "/ui/finance/prepaids", "Review prepaid expenses.", "Tinjau biaya dibayar dimuka.", "prepaid_expense.list"),
						adminConsoleLink("prepaid_schedules", "Prepaid Schedules", "Jadwal Biaya Dibayar Dimuka", "/ui/finance/prepaid-schedules", "Review prepaid schedules.", "Tinjau jadwal biaya dibayar dimuka.", "prepaid_schedule.list"),
					},
				},
			},
		},
		Models: []model.Definition{
			{
				Key:                 "fixed_asset",
				DisplayName:         "Fixed Asset",
				DisplayNameI18n:     localize("Fixed Asset", "Aset Tetap"),
				OwnerModuleKey:      "finance_asset_core",
				Version:             "v1",
				CreatePermissionKey: "fixed_asset.create",
				ListPermissionKey:   "fixed_asset.list",
				ReadPermissionKey:   "fixed_asset.read",
				UpdatePermissionKey: "fixed_asset.update",
				DefaultSort:         "code",
				Fields: []model.FieldDefinition{
					{Key: "organization_id", Label: "Organization", LabelI18n: localize("Organization", "Organisasi"), Type: "string", Required: true},
					{Key: "location_id", Label: "Location", LabelI18n: localize("Location", "Lokasi"), Type: "string"},
					{Key: "code", Label: "Code", LabelI18n: localize("Code", "Kode"), Type: "string", Required: true},
					{Key: "name", Label: "Name", LabelI18n: localize("Name", "Nama"), Type: "string", Required: true},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Type: "string", DefaultValue: "active"},
					{Key: "acquisition_date", Label: "Acquisition Date", LabelI18n: localize("Acquisition Date", "Tanggal Perolehan"), Type: "string"},
					{Key: "capitalization_date", Label: "Capitalization Date", LabelI18n: localize("Capitalization Date", "Tanggal Kapitalisasi"), Type: "string"},
					{Key: "basis_amount", Label: "Basis Amount", LabelI18n: localize("Basis Amount", "Nilai Dasar"), Type: "number", Required: true},
					{Key: "salvage_amount", Label: "Salvage Amount", LabelI18n: localize("Salvage Amount", "Nilai Residu"), Type: "number"},
					{Key: "method", Label: "Method", LabelI18n: localize("Method", "Metode"), Type: "string", DefaultValue: "straight_line"},
					{Key: "declining_rate_percent", Label: "Declining Rate %", LabelI18n: localize("Declining Rate %", "Tarif Menurun %"), Type: "number"},
					{Key: "cadence", Label: "Cadence", LabelI18n: localize("Cadence", "Cadence"), Type: "string", DefaultValue: "monthly"},
					{Key: "total_periods", Label: "Total Periods", LabelI18n: localize("Total Periods", "Total Periode"), Type: "int", Required: true},
					{Key: "periods_booked", Label: "Booked Periods", LabelI18n: localize("Booked Periods", "Periode Dibukukan"), Type: "int"},
					{Key: "booked_amount", Label: "Booked Amount", LabelI18n: localize("Booked Amount", "Jumlah Dibukukan"), Type: "number"},
					{Key: "remaining_amount", Label: "Remaining Amount", LabelI18n: localize("Remaining Amount", "Jumlah Tersisa"), Type: "number"},
					{Key: "next_posting_date", Label: "Next Posting Date", LabelI18n: localize("Next Posting Date", "Tanggal Posting Berikutnya"), Type: "string"},
					{Key: "asset_account_code", Label: "Asset Account", LabelI18n: localize("Asset Account", "Akun Aset"), Type: "string"},
					{Key: "accumulated_depreciation_account_code", Label: "Accumulated Depreciation Account", LabelI18n: localize("Accumulated Depreciation Account", "Akun Akumulasi Depresiasi"), Type: "string"},
					{Key: "depreciation_expense_account_code", Label: "Depreciation Expense Account", LabelI18n: localize("Depreciation Expense Account", "Akun Beban Depresiasi"), Type: "string"},
					{Key: "schedule_id", Label: "Schedule", LabelI18n: localize("Schedule", "Jadwal"), Type: "string"},
					{Key: "linked_journal_template_id", Label: "Journal Template", LabelI18n: localize("Journal Template", "Template Jurnal"), Type: "string"},
					{Key: "source_vendor_bill_id", Label: "Source Vendor Bill ID", LabelI18n: localize("Source Vendor Bill ID", "ID Tagihan Vendor Sumber"), Type: "string"},
					{Key: "source_vendor_bill_number", Label: "Source Vendor Bill", LabelI18n: localize("Source Vendor Bill", "Tagihan Vendor Sumber"), Type: "string"},
					{Key: "source_vendor_bill_line_index", Label: "Source Line Index", LabelI18n: localize("Source Line Index", "Indeks Baris Sumber"), Type: "int"},
					{Key: "origin_location_id", Label: "Origin Location", LabelI18n: localize("Origin Location", "Lokasi Asal"), Type: "string"},
					{Key: "current_location_id", Label: "Current Location", LabelI18n: localize("Current Location", "Lokasi Saat Ini"), Type: "string"},
					{Key: "cost_center_code", Label: "Cost Center", LabelI18n: localize("Cost Center", "Pusat Biaya"), Type: "string"},
					{Key: "origin_cost_center_code", Label: "Origin Cost Center", LabelI18n: localize("Origin Cost Center", "Pusat Biaya Asal"), Type: "string"},
					{Key: "current_cost_center_code", Label: "Current Cost Center", LabelI18n: localize("Current Cost Center", "Pusat Biaya Saat Ini"), Type: "string"},
					{Key: "lifecycle_status", Label: "Lifecycle Status", LabelI18n: localize("Lifecycle Status", "Status Siklus Hidup"), Type: "string"},
					{Key: "impairment_amount_total", Label: "Impairment Total", LabelI18n: localize("Impairment Total", "Total Penurunan Nilai"), Type: "number"},
					{Key: "revaluation_amount_total", Label: "Revaluation Total", LabelI18n: localize("Revaluation Total", "Total Revaluasi"), Type: "number"},
					{Key: "gross_amount_current", Label: "Current Gross Amount", LabelI18n: localize("Current Gross Amount", "Nilai Bruto Saat Ini"), Type: "number"},
					{Key: "carrying_amount", Label: "Carrying Amount", LabelI18n: localize("Carrying Amount", "Nilai Tercatat"), Type: "number"},
					{Key: "last_lifecycle_event_type", Label: "Last Lifecycle Event Type", LabelI18n: localize("Last Lifecycle Event Type", "Jenis Event Siklus Hidup Terakhir"), Type: "string"},
					{Key: "last_lifecycle_event_id", Label: "Last Lifecycle Event", LabelI18n: localize("Last Lifecycle Event", "Event Siklus Hidup Terakhir"), Type: "string"},
					{Key: "disposal_date", Label: "Disposal Date", LabelI18n: localize("Disposal Date", "Tanggal Pelepasan"), Type: "string"},
					{Key: "disposal_type", Label: "Disposal Type", LabelI18n: localize("Disposal Type", "Jenis Pelepasan"), Type: "string"},
					{Key: "disposal_posting_id", Label: "Disposal Posting", LabelI18n: localize("Disposal Posting", "Posting Pelepasan"), Type: "string"},
					{Key: "notes", Label: "Notes", LabelI18n: localize("Notes", "Catatan"), Type: "string"},
				},
			},
			{
				Key:                 "fixed_asset_schedule",
				DisplayName:         "Fixed Asset Schedule",
				DisplayNameI18n:     localize("Fixed Asset Schedule", "Jadwal Aset Tetap"),
				OwnerModuleKey:      "finance_asset_core",
				Version:             "v1",
				CreatePermissionKey: "fixed_asset_schedule.create",
				ListPermissionKey:   "fixed_asset_schedule.list",
				ReadPermissionKey:   "fixed_asset_schedule.read",
				UpdatePermissionKey: "fixed_asset_schedule.update",
				DefaultSort:         "next_posting_date",
				Fields: []model.FieldDefinition{
					{Key: "organization_id", Label: "Organization", LabelI18n: localize("Organization", "Organisasi"), Type: "string", Required: true},
					{Key: "location_id", Label: "Location", LabelI18n: localize("Location", "Lokasi"), Type: "string"},
					{Key: "fixed_asset_id", Label: "Fixed Asset", LabelI18n: localize("Fixed Asset", "Aset Tetap"), Type: "string", Required: true},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Type: "string", DefaultValue: "active"},
					{Key: "start_date", Label: "Start Date", LabelI18n: localize("Start Date", "Tanggal Mulai"), Type: "string"},
					{Key: "method", Label: "Method", LabelI18n: localize("Method", "Metode"), Type: "string"},
					{Key: "declining_rate_percent", Label: "Declining Rate %", LabelI18n: localize("Declining Rate %", "Tarif Menurun %"), Type: "number"},
					{Key: "cadence", Label: "Cadence", LabelI18n: localize("Cadence", "Cadence"), Type: "string"},
					{Key: "basis_amount", Label: "Basis Amount", LabelI18n: localize("Basis Amount", "Nilai Dasar"), Type: "number"},
					{Key: "depreciable_basis_amount", Label: "Depreciable Basis", LabelI18n: localize("Depreciable Basis", "Nilai Dasar Disusutkan"), Type: "number"},
					{Key: "salvage_amount", Label: "Salvage Amount", LabelI18n: localize("Salvage Amount", "Nilai Residu"), Type: "number"},
					{Key: "total_periods", Label: "Total Periods", LabelI18n: localize("Total Periods", "Total Periode"), Type: "int"},
					{Key: "periods_booked", Label: "Booked Periods", LabelI18n: localize("Booked Periods", "Periode Dibukukan"), Type: "int"},
					{Key: "booked_amount", Label: "Booked Amount", LabelI18n: localize("Booked Amount", "Jumlah Dibukukan"), Type: "number"},
					{Key: "remaining_amount", Label: "Remaining Amount", LabelI18n: localize("Remaining Amount", "Jumlah Tersisa"), Type: "number"},
					{Key: "accumulated_adjustment_amount", Label: "Adjustment Total", LabelI18n: localize("Adjustment Total", "Total Penyesuaian"), Type: "number"},
					{Key: "next_posting_date", Label: "Next Posting Date", LabelI18n: localize("Next Posting Date", "Tanggal Posting Berikutnya"), Type: "string"},
					{Key: "last_posting_id", Label: "Last Posting ID", LabelI18n: localize("Last Posting ID", "ID Posting Terakhir"), Type: "string"},
					{Key: "last_posting_date", Label: "Last Posting Date", LabelI18n: localize("Last Posting Date", "Tanggal Posting Terakhir"), Type: "string"},
					{Key: "last_posting_amount", Label: "Last Posting Amount", LabelI18n: localize("Last Posting Amount", "Jumlah Posting Terakhir"), Type: "number"},
					{Key: "last_rebase_date", Label: "Last Rebase Date", LabelI18n: localize("Last Rebase Date", "Tanggal Rebase Terakhir"), Type: "string"},
					{Key: "last_rebase_reason", Label: "Last Rebase Reason", LabelI18n: localize("Last Rebase Reason", "Alasan Rebase Terakhir"), Type: "string"},
					{Key: "asset_account_code", Label: "Asset Account", LabelI18n: localize("Asset Account", "Akun Aset"), Type: "string"},
					{Key: "accumulated_depreciation_account_code", Label: "Accumulated Depreciation Account", LabelI18n: localize("Accumulated Depreciation Account", "Akun Akumulasi Depresiasi"), Type: "string"},
					{Key: "depreciation_expense_account_code", Label: "Depreciation Expense Account", LabelI18n: localize("Depreciation Expense Account", "Akun Beban Depresiasi"), Type: "string"},
					{Key: "linked_journal_template_id", Label: "Journal Template", LabelI18n: localize("Journal Template", "Template Jurnal"), Type: "string"},
				},
			},
			{
				Key:                 "prepaid_expense",
				DisplayName:         "Prepaid Expense",
				DisplayNameI18n:     localize("Prepaid Expense", "Biaya Dibayar Dimuka"),
				OwnerModuleKey:      "finance_asset_core",
				Version:             "v1",
				CreatePermissionKey: "prepaid_expense.create",
				ListPermissionKey:   "prepaid_expense.list",
				ReadPermissionKey:   "prepaid_expense.read",
				UpdatePermissionKey: "prepaid_expense.update",
				DefaultSort:         "code",
				Fields: []model.FieldDefinition{
					{Key: "organization_id", Label: "Organization", LabelI18n: localize("Organization", "Organisasi"), Type: "string", Required: true},
					{Key: "location_id", Label: "Location", LabelI18n: localize("Location", "Lokasi"), Type: "string"},
					{Key: "code", Label: "Code", LabelI18n: localize("Code", "Kode"), Type: "string", Required: true},
					{Key: "name", Label: "Name", LabelI18n: localize("Name", "Nama"), Type: "string", Required: true},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Type: "string", DefaultValue: "active"},
					{Key: "recognition_start_date", Label: "Recognition Start", LabelI18n: localize("Recognition Start", "Mulai Pengakuan"), Type: "string"},
					{Key: "basis_amount", Label: "Basis Amount", LabelI18n: localize("Basis Amount", "Nilai Dasar"), Type: "number", Required: true},
					{Key: "method", Label: "Method", LabelI18n: localize("Method", "Metode"), Type: "string", DefaultValue: "straight_line"},
					{Key: "declining_rate_percent", Label: "Declining Rate %", LabelI18n: localize("Declining Rate %", "Tarif Menurun %"), Type: "number"},
					{Key: "cadence", Label: "Cadence", LabelI18n: localize("Cadence", "Cadence"), Type: "string", DefaultValue: "monthly"},
					{Key: "total_periods", Label: "Total Periods", LabelI18n: localize("Total Periods", "Total Periode"), Type: "int", Required: true},
					{Key: "periods_booked", Label: "Booked Periods", LabelI18n: localize("Booked Periods", "Periode Dibukukan"), Type: "int"},
					{Key: "booked_amount", Label: "Booked Amount", LabelI18n: localize("Booked Amount", "Jumlah Dibukukan"), Type: "number"},
					{Key: "remaining_amount", Label: "Remaining Amount", LabelI18n: localize("Remaining Amount", "Jumlah Tersisa"), Type: "number"},
					{Key: "next_posting_date", Label: "Next Posting Date", LabelI18n: localize("Next Posting Date", "Tanggal Posting Berikutnya"), Type: "string"},
					{Key: "prepaid_asset_account_code", Label: "Prepaid Asset Account", LabelI18n: localize("Prepaid Asset Account", "Akun Aset Dibayar Dimuka"), Type: "string"},
					{Key: "expense_account_code", Label: "Expense Account", LabelI18n: localize("Expense Account", "Akun Beban"), Type: "string"},
					{Key: "schedule_id", Label: "Schedule", LabelI18n: localize("Schedule", "Jadwal"), Type: "string"},
					{Key: "linked_journal_template_id", Label: "Journal Template", LabelI18n: localize("Journal Template", "Template Jurnal"), Type: "string"},
					{Key: "source_vendor_bill_id", Label: "Source Vendor Bill ID", LabelI18n: localize("Source Vendor Bill ID", "ID Tagihan Vendor Sumber"), Type: "string"},
					{Key: "source_vendor_bill_number", Label: "Source Vendor Bill", LabelI18n: localize("Source Vendor Bill", "Tagihan Vendor Sumber"), Type: "string"},
					{Key: "source_vendor_bill_line_index", Label: "Source Line Index", LabelI18n: localize("Source Line Index", "Indeks Baris Sumber"), Type: "int"},
					{Key: "notes", Label: "Notes", LabelI18n: localize("Notes", "Catatan"), Type: "string"},
				},
			},
			{
				Key:                 "prepaid_schedule",
				DisplayName:         "Prepaid Schedule",
				DisplayNameI18n:     localize("Prepaid Schedule", "Jadwal Biaya Dibayar Dimuka"),
				OwnerModuleKey:      "finance_asset_core",
				Version:             "v1",
				CreatePermissionKey: "prepaid_schedule.create",
				ListPermissionKey:   "prepaid_schedule.list",
				ReadPermissionKey:   "prepaid_schedule.read",
				UpdatePermissionKey: "prepaid_schedule.update",
				DefaultSort:         "next_posting_date",
				Fields: []model.FieldDefinition{
					{Key: "organization_id", Label: "Organization", LabelI18n: localize("Organization", "Organisasi"), Type: "string", Required: true},
					{Key: "location_id", Label: "Location", LabelI18n: localize("Location", "Lokasi"), Type: "string"},
					{Key: "prepaid_expense_id", Label: "Prepaid Expense", LabelI18n: localize("Prepaid Expense", "Biaya Dibayar Dimuka"), Type: "string", Required: true},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Type: "string", DefaultValue: "active"},
					{Key: "start_date", Label: "Start Date", LabelI18n: localize("Start Date", "Tanggal Mulai"), Type: "string"},
					{Key: "method", Label: "Method", LabelI18n: localize("Method", "Metode"), Type: "string"},
					{Key: "declining_rate_percent", Label: "Declining Rate %", LabelI18n: localize("Declining Rate %", "Tarif Menurun %"), Type: "number"},
					{Key: "cadence", Label: "Cadence", LabelI18n: localize("Cadence", "Cadence"), Type: "string"},
					{Key: "basis_amount", Label: "Basis Amount", LabelI18n: localize("Basis Amount", "Nilai Dasar"), Type: "number"},
					{Key: "total_periods", Label: "Total Periods", LabelI18n: localize("Total Periods", "Total Periode"), Type: "int"},
					{Key: "periods_booked", Label: "Booked Periods", LabelI18n: localize("Booked Periods", "Periode Dibukukan"), Type: "int"},
					{Key: "booked_amount", Label: "Booked Amount", LabelI18n: localize("Booked Amount", "Jumlah Dibukukan"), Type: "number"},
					{Key: "remaining_amount", Label: "Remaining Amount", LabelI18n: localize("Remaining Amount", "Jumlah Tersisa"), Type: "number"},
					{Key: "next_posting_date", Label: "Next Posting Date", LabelI18n: localize("Next Posting Date", "Tanggal Posting Berikutnya"), Type: "string"},
					{Key: "last_posting_id", Label: "Last Posting ID", LabelI18n: localize("Last Posting ID", "ID Posting Terakhir"), Type: "string"},
					{Key: "last_posting_date", Label: "Last Posting Date", LabelI18n: localize("Last Posting Date", "Tanggal Posting Terakhir"), Type: "string"},
					{Key: "last_posting_amount", Label: "Last Posting Amount", LabelI18n: localize("Last Posting Amount", "Jumlah Posting Terakhir"), Type: "number"},
					{Key: "prepaid_asset_account_code", Label: "Prepaid Asset Account", LabelI18n: localize("Prepaid Asset Account", "Akun Aset Dibayar Dimuka"), Type: "string"},
					{Key: "expense_account_code", Label: "Expense Account", LabelI18n: localize("Expense Account", "Akun Beban"), Type: "string"},
					{Key: "linked_journal_template_id", Label: "Journal Template", LabelI18n: localize("Journal Template", "Template Jurnal"), Type: "string"},
				},
			},
			{
				Key:                 "asset_disposal",
				DisplayName:         "Asset Disposal",
				DisplayNameI18n:     localize("Asset Disposal", "Pelepasan Aset"),
				OwnerModuleKey:      "finance_asset_core",
				Version:             "v1",
				CreatePermissionKey: "asset_disposal.create",
				ListPermissionKey:   "asset_disposal.list",
				ReadPermissionKey:   "asset_disposal.read",
				UpdatePermissionKey: "asset_disposal.update",
				DefaultSort:         "disposal_date",
				Fields: []model.FieldDefinition{
					{Key: "organization_id", Label: "Organization", LabelI18n: localize("Organization", "Organisasi"), Type: "string", Required: true},
					{Key: "location_id", Label: "Location", LabelI18n: localize("Location", "Lokasi"), Type: "string"},
					{Key: "fixed_asset_id", Label: "Fixed Asset", LabelI18n: localize("Fixed Asset", "Aset Tetap"), Type: "string", Required: true},
					{Key: "fixed_asset_schedule_id", Label: "Schedule", LabelI18n: localize("Schedule", "Jadwal"), Type: "string"},
					{Key: "disposal_date", Label: "Disposal Date", LabelI18n: localize("Disposal Date", "Tanggal Pelepasan"), Type: "string"},
					{Key: "disposal_type", Label: "Disposal Type", LabelI18n: localize("Disposal Type", "Jenis Pelepasan"), Type: "string"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Type: "string"},
					{Key: "proceeds_amount", Label: "Proceeds", LabelI18n: localize("Proceeds", "Hasil Penjualan"), Type: "number"},
					{Key: "carrying_amount", Label: "Carrying Amount", LabelI18n: localize("Carrying Amount", "Nilai Tercatat"), Type: "number"},
					{Key: "gain_loss_amount", Label: "Gain Loss", LabelI18n: localize("Gain Loss", "Laba Rugi"), Type: "number"},
					{Key: "posting_id", Label: "Posting", LabelI18n: localize("Posting", "Posting"), Type: "string"},
				},
			},
			{
				Key:                 "asset_transfer",
				DisplayName:         "Asset Transfer",
				DisplayNameI18n:     localize("Asset Transfer", "Transfer Aset"),
				OwnerModuleKey:      "finance_asset_core",
				Version:             "v1",
				CreatePermissionKey: "asset_transfer.create",
				ListPermissionKey:   "asset_transfer.list",
				ReadPermissionKey:   "asset_transfer.read",
				UpdatePermissionKey: "asset_transfer.update",
				DefaultSort:         "effective_date",
				Fields: []model.FieldDefinition{
					{Key: "organization_id", Label: "Organization", LabelI18n: localize("Organization", "Organisasi"), Type: "string", Required: true},
					{Key: "location_id", Label: "Location", LabelI18n: localize("Location", "Lokasi"), Type: "string"},
					{Key: "fixed_asset_id", Label: "Fixed Asset", LabelI18n: localize("Fixed Asset", "Aset Tetap"), Type: "string", Required: true},
					{Key: "effective_date", Label: "Effective Date", LabelI18n: localize("Effective Date", "Tanggal Efektif"), Type: "string"},
					{Key: "from_location_id", Label: "From Location", LabelI18n: localize("From Location", "Dari Lokasi"), Type: "string"},
					{Key: "to_location_id", Label: "To Location", LabelI18n: localize("To Location", "Ke Lokasi"), Type: "string"},
					{Key: "from_cost_center_code", Label: "From Cost Center", LabelI18n: localize("From Cost Center", "Dari Pusat Biaya"), Type: "string"},
					{Key: "to_cost_center_code", Label: "To Cost Center", LabelI18n: localize("To Cost Center", "Ke Pusat Biaya"), Type: "string"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Type: "string"},
				},
			},
			{
				Key:                 "asset_impairment",
				DisplayName:         "Asset Impairment",
				DisplayNameI18n:     localize("Asset Impairment", "Penurunan Nilai Aset"),
				OwnerModuleKey:      "finance_asset_core",
				Version:             "v1",
				CreatePermissionKey: "asset_impairment.create",
				ListPermissionKey:   "asset_impairment.list",
				ReadPermissionKey:   "asset_impairment.read",
				UpdatePermissionKey: "asset_impairment.update",
				DefaultSort:         "impairment_date",
				Fields: []model.FieldDefinition{
					{Key: "organization_id", Label: "Organization", LabelI18n: localize("Organization", "Organisasi"), Type: "string", Required: true},
					{Key: "location_id", Label: "Location", LabelI18n: localize("Location", "Lokasi"), Type: "string"},
					{Key: "fixed_asset_id", Label: "Fixed Asset", LabelI18n: localize("Fixed Asset", "Aset Tetap"), Type: "string", Required: true},
					{Key: "fixed_asset_schedule_id", Label: "Schedule", LabelI18n: localize("Schedule", "Jadwal"), Type: "string"},
					{Key: "impairment_date", Label: "Impairment Date", LabelI18n: localize("Impairment Date", "Tanggal Penurunan Nilai"), Type: "string"},
					{Key: "impairment_amount", Label: "Impairment Amount", LabelI18n: localize("Impairment Amount", "Jumlah Penurunan Nilai"), Type: "number"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Type: "string"},
					{Key: "posting_id", Label: "Posting", LabelI18n: localize("Posting", "Posting"), Type: "string"},
				},
			},
			{
				Key:                 "asset_revaluation",
				DisplayName:         "Asset Revaluation",
				DisplayNameI18n:     localize("Asset Revaluation", "Revaluasi Aset"),
				OwnerModuleKey:      "finance_asset_core",
				Version:             "v1",
				CreatePermissionKey: "asset_revaluation.create",
				ListPermissionKey:   "asset_revaluation.list",
				ReadPermissionKey:   "asset_revaluation.read",
				UpdatePermissionKey: "asset_revaluation.update",
				DefaultSort:         "revaluation_date",
				Fields: []model.FieldDefinition{
					{Key: "organization_id", Label: "Organization", LabelI18n: localize("Organization", "Organisasi"), Type: "string", Required: true},
					{Key: "location_id", Label: "Location", LabelI18n: localize("Location", "Lokasi"), Type: "string"},
					{Key: "fixed_asset_id", Label: "Fixed Asset", LabelI18n: localize("Fixed Asset", "Aset Tetap"), Type: "string", Required: true},
					{Key: "fixed_asset_schedule_id", Label: "Schedule", LabelI18n: localize("Schedule", "Jadwal"), Type: "string"},
					{Key: "revaluation_date", Label: "Revaluation Date", LabelI18n: localize("Revaluation Date", "Tanggal Revaluasi"), Type: "string"},
					{Key: "revaluation_amount", Label: "Revaluation Amount", LabelI18n: localize("Revaluation Amount", "Jumlah Revaluasi"), Type: "number"},
					{Key: "target_carrying_amount", Label: "Target Carrying Amount", LabelI18n: localize("Target Carrying Amount", "Target Nilai Tercatat"), Type: "number"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Type: "string"},
					{Key: "posting_id", Label: "Posting", LabelI18n: localize("Posting", "Posting"), Type: "string"},
				},
			},
		},
		Security: module.SecurityDefinition{
			Permissions: append(
				append(
					append(
						append(
							commercialModelPermissions("fixed_asset", "Fixed Asset"),
							commercialModelPermissions("fixed_asset_schedule", "Fixed Asset Schedule")...,
						),
						append(
							commercialModelPermissions("prepaid_expense", "Prepaid Expense"),
							commercialModelPermissions("prepaid_schedule", "Prepaid Schedule")...,
						)...,
					),
					append(
						append(
							commercialModelPermissions("asset_disposal", "Asset Disposal"),
							commercialModelPermissions("asset_transfer", "Asset Transfer")...,
						),
						append(
							commercialModelPermissions("asset_impairment", "Asset Impairment"),
							commercialModelPermissions("asset_revaluation", "Asset Revaluation")...,
						)...,
					)...,
				),
				module.PermissionDefinition{
					Key:             "finance.asset.manage",
					Action:          "manage",
					Resource:        "finance_assets",
					DisplayName:     "Manage Finance Assets",
					DisplayNameI18n: localize("Manage Finance Assets", "Kelola Aset Keuangan"),
				},
			),
			RoleTemplates: []module.RoleTemplateDefinition{
				{
					Key:           "finance_asset_manager",
					Name:          "Finance Asset Manager",
					NameI18n:      localize("Finance Asset Manager", "Manajer Aset Keuangan"),
					AllowedScopes: []string{"deployment", "organization", "location"},
					PermissionKeys: []string{
						"fixed_asset.create", "fixed_asset.list", "fixed_asset.read", "fixed_asset.update",
						"fixed_asset_schedule.create", "fixed_asset_schedule.list", "fixed_asset_schedule.read", "fixed_asset_schedule.update",
						"prepaid_expense.create", "prepaid_expense.list", "prepaid_expense.read", "prepaid_expense.update",
						"prepaid_schedule.create", "prepaid_schedule.list", "prepaid_schedule.read", "prepaid_schedule.update",
						"asset_disposal.create", "asset_disposal.list", "asset_disposal.read", "asset_disposal.update",
						"asset_transfer.create", "asset_transfer.list", "asset_transfer.read", "asset_transfer.update",
						"asset_impairment.create", "asset_impairment.list", "asset_impairment.read", "asset_impairment.update",
						"asset_revaluation.create", "asset_revaluation.list", "asset_revaluation.read", "asset_revaluation.update",
						"finance.asset.manage", "finance.read", "finance.period_end.manage",
						"journal_template.create", "journal_template.read", "journal_template.update",
						"document.create", "document.read",
					},
				},
			},
		},
		Frontend: module.FrontendDefinition{
			Menus: []module.MenuDefinition{
				{Key: "finance.fixed_assets", Label: "Fixed Assets", LabelI18n: localize("Fixed Assets", "Aset Tetap"), ActionKey: "finance.fixed_assets.list", Order: 121, RequiredPermissions: []string{"fixed_asset.list"}},
				{Key: "finance.fixed_asset_schedules", Label: "Fixed Asset Schedules", LabelI18n: localize("Fixed Asset Schedules", "Jadwal Aset Tetap"), ActionKey: "finance.fixed_asset_schedules.list", Order: 122, RequiredPermissions: []string{"fixed_asset_schedule.list"}},
				{Key: "finance.prepaids", Label: "Prepaids", LabelI18n: localize("Prepaids", "Biaya Dibayar Dimuka"), ActionKey: "finance.prepaids.list", Order: 123, RequiredPermissions: []string{"prepaid_expense.list"}},
				{Key: "finance.prepaid_schedules", Label: "Prepaid Schedules", LabelI18n: localize("Prepaid Schedules", "Jadwal Biaya Dibayar Dimuka"), ActionKey: "finance.prepaid_schedules.list", Order: 124, RequiredPermissions: []string{"prepaid_schedule.list"}},
				{Key: "finance.asset_disposals", Label: "Asset Disposals", LabelI18n: localize("Asset Disposals", "Pelepasan Aset"), ActionKey: "finance.asset_disposals.list", Order: 125, RequiredPermissions: []string{"asset_disposal.list"}},
				{Key: "finance.asset_transfers", Label: "Asset Transfers", LabelI18n: localize("Asset Transfers", "Transfer Aset"), ActionKey: "finance.asset_transfers.list", Order: 126, RequiredPermissions: []string{"asset_transfer.list"}},
				{Key: "finance.asset_impairments", Label: "Asset Impairments", LabelI18n: localize("Asset Impairments", "Penurunan Nilai Aset"), ActionKey: "finance.asset_impairments.list", Order: 127, RequiredPermissions: []string{"asset_impairment.list"}},
				{Key: "finance.asset_revaluations", Label: "Asset Revaluations", LabelI18n: localize("Asset Revaluations", "Revaluasi Aset"), ActionKey: "finance.asset_revaluations.list", Order: 128, RequiredPermissions: []string{"asset_revaluation.list"}},
			},
			Actions: []module.ActionDefinition{
				{Key: "finance.fixed_assets.list", Label: "Fixed Assets", LabelI18n: localize("Fixed Assets", "Aset Tetap"), Kind: "navigate", RoutePath: "/finance/fixed-assets", ViewKey: "finance.fixed_assets.list", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"fixed_asset.list"}},
				{Key: "finance.fixed_assets.detail", Label: "Fixed Asset Detail", LabelI18n: localize("Fixed Asset Detail", "Detail Aset Tetap"), Kind: "navigate", RoutePath: "/finance/fixed-assets/detail", ViewKey: "finance.fixed_assets.detail", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"fixed_asset.read"}},
				{Key: "finance.fixed_assets.form", Label: "Fixed Asset Form", LabelI18n: localize("Fixed Asset Form", "Form Aset Tetap"), Kind: "navigate", RoutePath: "/finance/fixed-assets/form", ViewKey: "finance.fixed_assets.form", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"fixed_asset.update"}},
				{Key: "finance.fixed_asset_schedules.list", Label: "Fixed Asset Schedules", LabelI18n: localize("Fixed Asset Schedules", "Jadwal Aset Tetap"), Kind: "navigate", RoutePath: "/finance/fixed-asset-schedules", ViewKey: "finance.fixed_asset_schedules.list", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"fixed_asset_schedule.list"}},
				{Key: "finance.fixed_asset_schedules.detail", Label: "Fixed Asset Schedule Detail", LabelI18n: localize("Fixed Asset Schedule Detail", "Detail Jadwal Aset Tetap"), Kind: "navigate", RoutePath: "/finance/fixed-asset-schedules/detail", ViewKey: "finance.fixed_asset_schedules.detail", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"fixed_asset_schedule.read"}},
				{Key: "finance.prepaids.list", Label: "Prepaids", LabelI18n: localize("Prepaids", "Biaya Dibayar Dimuka"), Kind: "navigate", RoutePath: "/finance/prepaids", ViewKey: "finance.prepaids.list", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"prepaid_expense.list"}},
				{Key: "finance.prepaids.detail", Label: "Prepaid Detail", LabelI18n: localize("Prepaid Detail", "Detail Biaya Dibayar Dimuka"), Kind: "navigate", RoutePath: "/finance/prepaids/detail", ViewKey: "finance.prepaids.detail", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"prepaid_expense.read"}},
				{Key: "finance.prepaids.form", Label: "Prepaid Form", LabelI18n: localize("Prepaid Form", "Form Biaya Dibayar Dimuka"), Kind: "navigate", RoutePath: "/finance/prepaids/form", ViewKey: "finance.prepaids.form", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"prepaid_expense.update"}},
				{Key: "finance.prepaid_schedules.list", Label: "Prepaid Schedules", LabelI18n: localize("Prepaid Schedules", "Jadwal Biaya Dibayar Dimuka"), Kind: "navigate", RoutePath: "/finance/prepaid-schedules", ViewKey: "finance.prepaid_schedules.list", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"prepaid_schedule.list"}},
				{Key: "finance.prepaid_schedules.detail", Label: "Prepaid Schedule Detail", LabelI18n: localize("Prepaid Schedule Detail", "Detail Jadwal Biaya Dibayar Dimuka"), Kind: "navigate", RoutePath: "/finance/prepaid-schedules/detail", ViewKey: "finance.prepaid_schedules.detail", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"prepaid_schedule.read"}},
				{Key: "finance.asset_disposals.list", Label: "Asset Disposals", LabelI18n: localize("Asset Disposals", "Pelepasan Aset"), Kind: "navigate", RoutePath: "/finance/asset-disposals", ViewKey: "finance.asset_disposals.list", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"asset_disposal.list"}},
				{Key: "finance.asset_disposals.detail", Label: "Asset Disposal Detail", LabelI18n: localize("Asset Disposal Detail", "Detail Pelepasan Aset"), Kind: "navigate", RoutePath: "/finance/asset-disposals/detail", ViewKey: "finance.asset_disposals.detail", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"asset_disposal.read"}},
				{Key: "finance.asset_transfers.list", Label: "Asset Transfers", LabelI18n: localize("Asset Transfers", "Transfer Aset"), Kind: "navigate", RoutePath: "/finance/asset-transfers", ViewKey: "finance.asset_transfers.list", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"asset_transfer.list"}},
				{Key: "finance.asset_transfers.detail", Label: "Asset Transfer Detail", LabelI18n: localize("Asset Transfer Detail", "Detail Transfer Aset"), Kind: "navigate", RoutePath: "/finance/asset-transfers/detail", ViewKey: "finance.asset_transfers.detail", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"asset_transfer.read"}},
				{Key: "finance.asset_impairments.list", Label: "Asset Impairments", LabelI18n: localize("Asset Impairments", "Penurunan Nilai Aset"), Kind: "navigate", RoutePath: "/finance/asset-impairments", ViewKey: "finance.asset_impairments.list", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"asset_impairment.list"}},
				{Key: "finance.asset_impairments.detail", Label: "Asset Impairment Detail", LabelI18n: localize("Asset Impairment Detail", "Detail Penurunan Nilai Aset"), Kind: "navigate", RoutePath: "/finance/asset-impairments/detail", ViewKey: "finance.asset_impairments.detail", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"asset_impairment.read"}},
				{Key: "finance.asset_revaluations.list", Label: "Asset Revaluations", LabelI18n: localize("Asset Revaluations", "Revaluasi Aset"), Kind: "navigate", RoutePath: "/finance/asset-revaluations", ViewKey: "finance.asset_revaluations.list", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"asset_revaluation.list"}},
				{Key: "finance.asset_revaluations.detail", Label: "Asset Revaluation Detail", LabelI18n: localize("Asset Revaluation Detail", "Detail Revaluasi Aset"), Kind: "navigate", RoutePath: "/finance/asset-revaluations/detail", ViewKey: "finance.asset_revaluations.detail", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"asset_revaluation.read"}},
			},
			Views: []module.ViewDefinition{
				commercialModelListView("finance.fixed_assets.list", "Fixed Assets", "fixed_asset", []module.ColumnDefinition{
					{Key: "code", Label: "Code", LabelI18n: localize("Code", "Kode"), Path: "values.code"},
					{Key: "name", Label: "Name", LabelI18n: localize("Name", "Nama"), Path: "values.name"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status"},
					{Key: "basis_amount", Label: "Basis", LabelI18n: localize("Basis", "Nilai Dasar"), Path: "values.basis_amount"},
					{Key: "remaining_amount", Label: "Remaining", LabelI18n: localize("Remaining", "Sisa"), Path: "values.remaining_amount"},
					{Key: "next_posting_date", Label: "Next Posting", LabelI18n: localize("Next Posting", "Posting Berikutnya"), Path: "values.next_posting_date"},
				}, []string{"active", "completed", "suspended", "disposed", "retired", "impaired", "revalued", "transferred"}),
				commercialModelDetailView("finance.fixed_assets.detail", "Fixed Asset Detail", "fixed_asset", []module.FieldDefinition{
					{Key: "code", Label: "Code", LabelI18n: localize("Code", "Kode"), Path: "values.code", Type: "string"},
					{Key: "name", Label: "Name", LabelI18n: localize("Name", "Nama"), Path: "values.name", Type: "string"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status", Type: "string"},
					{Key: "basis_amount", Label: "Basis Amount", LabelI18n: localize("Basis Amount", "Nilai Dasar"), Path: "values.basis_amount", Type: "number"},
					{Key: "salvage_amount", Label: "Salvage Amount", LabelI18n: localize("Salvage Amount", "Nilai Residu"), Path: "values.salvage_amount", Type: "number"},
					{Key: "method", Label: "Method", LabelI18n: localize("Method", "Metode"), Path: "values.method", Type: "string"},
					{Key: "cadence", Label: "Cadence", LabelI18n: localize("Cadence", "Cadence"), Path: "values.cadence", Type: "string"},
					{Key: "total_periods", Label: "Total Periods", LabelI18n: localize("Total Periods", "Total Periode"), Path: "values.total_periods", Type: "number"},
					{Key: "periods_booked", Label: "Booked Periods", LabelI18n: localize("Booked Periods", "Periode Dibukukan"), Path: "values.periods_booked", Type: "number"},
					{Key: "booked_amount", Label: "Booked Amount", LabelI18n: localize("Booked Amount", "Jumlah Dibukukan"), Path: "values.booked_amount", Type: "number"},
					{Key: "remaining_amount", Label: "Remaining Amount", LabelI18n: localize("Remaining Amount", "Jumlah Tersisa"), Path: "values.remaining_amount", Type: "number"},
					{Key: "next_posting_date", Label: "Next Posting Date", LabelI18n: localize("Next Posting Date", "Tanggal Posting Berikutnya"), Path: "values.next_posting_date", Type: "string"},
					{Key: "source_vendor_bill_number", Label: "Source Vendor Bill", LabelI18n: localize("Source Vendor Bill", "Tagihan Vendor Sumber"), Path: "values.source_vendor_bill_number", Type: "string"},
				}),
				commercialModelFormView("finance.fixed_assets.form", "Fixed Asset Form", "fixed_asset", []module.FieldDefinition{
					{Key: "code", Label: "Code", LabelI18n: localize("Code", "Kode"), Path: "values.code", Type: "string", Widget: "text"},
					{Key: "name", Label: "Name", LabelI18n: localize("Name", "Nama"), Path: "values.name", Type: "string", Widget: "text"},
					{Key: "basis_amount", Label: "Basis Amount", LabelI18n: localize("Basis Amount", "Nilai Dasar"), Path: "values.basis_amount", Type: "number", Widget: "number"},
					{Key: "salvage_amount", Label: "Salvage Amount", LabelI18n: localize("Salvage Amount", "Nilai Residu"), Path: "values.salvage_amount", Type: "number", Widget: "number"},
					{Key: "method", Label: "Method", LabelI18n: localize("Method", "Metode"), Path: "values.method", Type: "string", Widget: "select", Options: []string{"straight_line", "declining_balance"}},
					{Key: "declining_rate_percent", Label: "Declining Rate %", LabelI18n: localize("Declining Rate %", "Tarif Menurun %"), Path: "values.declining_rate_percent", Type: "number", Widget: "number"},
					{Key: "cadence", Label: "Cadence", LabelI18n: localize("Cadence", "Cadence"), Path: "values.cadence", Type: "string", Widget: "select", Options: []string{"monthly", "quarterly", "yearly"}},
					{Key: "total_periods", Label: "Total Periods", LabelI18n: localize("Total Periods", "Total Periode"), Path: "values.total_periods", Type: "number", Widget: "number"},
					{Key: "asset_account_code", Label: "Asset Account", LabelI18n: localize("Asset Account", "Akun Aset"), Path: "values.asset_account_code", Type: "string", Widget: "text"},
					{Key: "accumulated_depreciation_account_code", Label: "Accumulated Depreciation Account", LabelI18n: localize("Accumulated Depreciation Account", "Akun Akumulasi Depresiasi"), Path: "values.accumulated_depreciation_account_code", Type: "string", Widget: "text"},
					{Key: "depreciation_expense_account_code", Label: "Depreciation Expense Account", LabelI18n: localize("Depreciation Expense Account", "Akun Beban Depresiasi"), Path: "values.depreciation_expense_account_code", Type: "string", Widget: "text"},
					{Key: "notes", Label: "Notes", LabelI18n: localize("Notes", "Catatan"), Path: "values.notes", Type: "string", Widget: "textarea"},
				}),
				commercialModelListView("finance.fixed_asset_schedules.list", "Fixed Asset Schedules", "fixed_asset_schedule", []module.ColumnDefinition{
					{Key: "fixed_asset_id", Label: "Fixed Asset", LabelI18n: localize("Fixed Asset", "Aset Tetap"), Path: "values.fixed_asset_id"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status"},
					{Key: "next_posting_date", Label: "Next Posting", LabelI18n: localize("Next Posting", "Posting Berikutnya"), Path: "values.next_posting_date"},
					{Key: "remaining_amount", Label: "Remaining", LabelI18n: localize("Remaining", "Sisa"), Path: "values.remaining_amount"},
				}, []string{"active", "completed", "suspended"}),
				commercialModelDetailView("finance.fixed_asset_schedules.detail", "Fixed Asset Schedule Detail", "fixed_asset_schedule", []module.FieldDefinition{
					{Key: "fixed_asset_id", Label: "Fixed Asset", LabelI18n: localize("Fixed Asset", "Aset Tetap"), Path: "values.fixed_asset_id", Type: "string"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status", Type: "string"},
					{Key: "method", Label: "Method", LabelI18n: localize("Method", "Metode"), Path: "values.method", Type: "string"},
					{Key: "cadence", Label: "Cadence", LabelI18n: localize("Cadence", "Cadence"), Path: "values.cadence", Type: "string"},
					{Key: "next_posting_date", Label: "Next Posting Date", LabelI18n: localize("Next Posting Date", "Tanggal Posting Berikutnya"), Path: "values.next_posting_date", Type: "string"},
					{Key: "booked_amount", Label: "Booked Amount", LabelI18n: localize("Booked Amount", "Jumlah Dibukukan"), Path: "values.booked_amount", Type: "number"},
					{Key: "remaining_amount", Label: "Remaining Amount", LabelI18n: localize("Remaining Amount", "Jumlah Tersisa"), Path: "values.remaining_amount", Type: "number"},
				}),
				commercialModelListView("finance.prepaids.list", "Prepaids", "prepaid_expense", []module.ColumnDefinition{
					{Key: "code", Label: "Code", LabelI18n: localize("Code", "Kode"), Path: "values.code"},
					{Key: "name", Label: "Name", LabelI18n: localize("Name", "Nama"), Path: "values.name"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status"},
					{Key: "basis_amount", Label: "Basis", LabelI18n: localize("Basis", "Nilai Dasar"), Path: "values.basis_amount"},
					{Key: "remaining_amount", Label: "Remaining", LabelI18n: localize("Remaining", "Sisa"), Path: "values.remaining_amount"},
					{Key: "next_posting_date", Label: "Next Posting", LabelI18n: localize("Next Posting", "Posting Berikutnya"), Path: "values.next_posting_date"},
				}, []string{"active", "completed", "suspended"}),
				commercialModelDetailView("finance.prepaids.detail", "Prepaid Detail", "prepaid_expense", []module.FieldDefinition{
					{Key: "code", Label: "Code", LabelI18n: localize("Code", "Kode"), Path: "values.code", Type: "string"},
					{Key: "name", Label: "Name", LabelI18n: localize("Name", "Nama"), Path: "values.name", Type: "string"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status", Type: "string"},
					{Key: "basis_amount", Label: "Basis Amount", LabelI18n: localize("Basis Amount", "Nilai Dasar"), Path: "values.basis_amount", Type: "number"},
					{Key: "method", Label: "Method", LabelI18n: localize("Method", "Metode"), Path: "values.method", Type: "string"},
					{Key: "cadence", Label: "Cadence", LabelI18n: localize("Cadence", "Cadence"), Path: "values.cadence", Type: "string"},
					{Key: "total_periods", Label: "Total Periods", LabelI18n: localize("Total Periods", "Total Periode"), Path: "values.total_periods", Type: "number"},
					{Key: "periods_booked", Label: "Booked Periods", LabelI18n: localize("Booked Periods", "Periode Dibukukan"), Path: "values.periods_booked", Type: "number"},
					{Key: "booked_amount", Label: "Booked Amount", LabelI18n: localize("Booked Amount", "Jumlah Dibukukan"), Path: "values.booked_amount", Type: "number"},
					{Key: "remaining_amount", Label: "Remaining Amount", LabelI18n: localize("Remaining Amount", "Jumlah Tersisa"), Path: "values.remaining_amount", Type: "number"},
					{Key: "next_posting_date", Label: "Next Posting Date", LabelI18n: localize("Next Posting Date", "Tanggal Posting Berikutnya"), Path: "values.next_posting_date", Type: "string"},
					{Key: "source_vendor_bill_number", Label: "Source Vendor Bill", LabelI18n: localize("Source Vendor Bill", "Tagihan Vendor Sumber"), Path: "values.source_vendor_bill_number", Type: "string"},
				}),
				commercialModelFormView("finance.prepaids.form", "Prepaid Form", "prepaid_expense", []module.FieldDefinition{
					{Key: "code", Label: "Code", LabelI18n: localize("Code", "Kode"), Path: "values.code", Type: "string", Widget: "text"},
					{Key: "name", Label: "Name", LabelI18n: localize("Name", "Nama"), Path: "values.name", Type: "string", Widget: "text"},
					{Key: "basis_amount", Label: "Basis Amount", LabelI18n: localize("Basis Amount", "Nilai Dasar"), Path: "values.basis_amount", Type: "number", Widget: "number"},
					{Key: "method", Label: "Method", LabelI18n: localize("Method", "Metode"), Path: "values.method", Type: "string", Widget: "select", Options: []string{"straight_line", "declining_balance"}},
					{Key: "declining_rate_percent", Label: "Declining Rate %", LabelI18n: localize("Declining Rate %", "Tarif Menurun %"), Path: "values.declining_rate_percent", Type: "number", Widget: "number"},
					{Key: "cadence", Label: "Cadence", LabelI18n: localize("Cadence", "Cadence"), Path: "values.cadence", Type: "string", Widget: "select", Options: []string{"monthly", "quarterly", "yearly"}},
					{Key: "total_periods", Label: "Total Periods", LabelI18n: localize("Total Periods", "Total Periode"), Path: "values.total_periods", Type: "number", Widget: "number"},
					{Key: "prepaid_asset_account_code", Label: "Prepaid Asset Account", LabelI18n: localize("Prepaid Asset Account", "Akun Aset Dibayar Dimuka"), Path: "values.prepaid_asset_account_code", Type: "string", Widget: "text"},
					{Key: "expense_account_code", Label: "Expense Account", LabelI18n: localize("Expense Account", "Akun Beban"), Path: "values.expense_account_code", Type: "string", Widget: "text"},
					{Key: "notes", Label: "Notes", LabelI18n: localize("Notes", "Catatan"), Path: "values.notes", Type: "string", Widget: "textarea"},
				}),
				commercialModelListView("finance.prepaid_schedules.list", "Prepaid Schedules", "prepaid_schedule", []module.ColumnDefinition{
					{Key: "prepaid_expense_id", Label: "Prepaid", LabelI18n: localize("Prepaid", "Biaya Dibayar Dimuka"), Path: "values.prepaid_expense_id"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status"},
					{Key: "next_posting_date", Label: "Next Posting", LabelI18n: localize("Next Posting", "Posting Berikutnya"), Path: "values.next_posting_date"},
					{Key: "remaining_amount", Label: "Remaining", LabelI18n: localize("Remaining", "Sisa"), Path: "values.remaining_amount"},
				}, []string{"active", "completed", "suspended"}),
				commercialModelDetailView("finance.prepaid_schedules.detail", "Prepaid Schedule Detail", "prepaid_schedule", []module.FieldDefinition{
					{Key: "prepaid_expense_id", Label: "Prepaid", LabelI18n: localize("Prepaid", "Biaya Dibayar Dimuka"), Path: "values.prepaid_expense_id", Type: "string"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status", Type: "string"},
					{Key: "method", Label: "Method", LabelI18n: localize("Method", "Metode"), Path: "values.method", Type: "string"},
					{Key: "cadence", Label: "Cadence", LabelI18n: localize("Cadence", "Cadence"), Path: "values.cadence", Type: "string"},
					{Key: "next_posting_date", Label: "Next Posting Date", LabelI18n: localize("Next Posting Date", "Tanggal Posting Berikutnya"), Path: "values.next_posting_date", Type: "string"},
					{Key: "booked_amount", Label: "Booked Amount", LabelI18n: localize("Booked Amount", "Jumlah Dibukukan"), Path: "values.booked_amount", Type: "number"},
					{Key: "remaining_amount", Label: "Remaining Amount", LabelI18n: localize("Remaining Amount", "Jumlah Tersisa"), Path: "values.remaining_amount", Type: "number"},
				}),
				commercialModelListView("finance.asset_disposals.list", "Asset Disposals", "asset_disposal", []module.ColumnDefinition{
					{Key: "fixed_asset_id", Label: "Asset", LabelI18n: localize("Asset", "Aset"), Path: "values.fixed_asset_id"},
					{Key: "disposal_date", Label: "Date", LabelI18n: localize("Date", "Tanggal"), Path: "values.disposal_date"},
					{Key: "disposal_type", Label: "Type", LabelI18n: localize("Type", "Jenis"), Path: "values.disposal_type"},
					{Key: "gain_loss_amount", Label: "Gain Loss", LabelI18n: localize("Gain Loss", "Laba Rugi"), Path: "values.gain_loss_amount"},
				}, []string{"posted"}),
				commercialModelDetailView("finance.asset_disposals.detail", "Asset Disposal Detail", "asset_disposal", []module.FieldDefinition{
					{Key: "fixed_asset_id", Label: "Asset", LabelI18n: localize("Asset", "Aset"), Path: "values.fixed_asset_id", Type: "string"},
					{Key: "disposal_date", Label: "Disposal Date", LabelI18n: localize("Disposal Date", "Tanggal Pelepasan"), Path: "values.disposal_date", Type: "string"},
					{Key: "disposal_type", Label: "Disposal Type", LabelI18n: localize("Disposal Type", "Jenis Pelepasan"), Path: "values.disposal_type", Type: "string"},
					{Key: "proceeds_amount", Label: "Proceeds", LabelI18n: localize("Proceeds", "Hasil Penjualan"), Path: "values.proceeds_amount", Type: "number"},
					{Key: "gain_loss_amount", Label: "Gain Loss", LabelI18n: localize("Gain Loss", "Laba Rugi"), Path: "values.gain_loss_amount", Type: "number"},
				}),
				commercialModelListView("finance.asset_transfers.list", "Asset Transfers", "asset_transfer", []module.ColumnDefinition{
					{Key: "fixed_asset_id", Label: "Asset", LabelI18n: localize("Asset", "Aset"), Path: "values.fixed_asset_id"},
					{Key: "effective_date", Label: "Effective Date", LabelI18n: localize("Effective Date", "Tanggal Efektif"), Path: "values.effective_date"},
					{Key: "to_location_id", Label: "To Location", LabelI18n: localize("To Location", "Ke Lokasi"), Path: "values.to_location_id"},
					{Key: "to_cost_center_code", Label: "To Cost Center", LabelI18n: localize("To Cost Center", "Ke Pusat Biaya"), Path: "values.to_cost_center_code"},
				}, []string{"posted"}),
				commercialModelDetailView("finance.asset_transfers.detail", "Asset Transfer Detail", "asset_transfer", []module.FieldDefinition{
					{Key: "fixed_asset_id", Label: "Asset", LabelI18n: localize("Asset", "Aset"), Path: "values.fixed_asset_id", Type: "string"},
					{Key: "effective_date", Label: "Effective Date", LabelI18n: localize("Effective Date", "Tanggal Efektif"), Path: "values.effective_date", Type: "string"},
					{Key: "from_location_id", Label: "From Location", LabelI18n: localize("From Location", "Dari Lokasi"), Path: "values.from_location_id", Type: "string"},
					{Key: "to_location_id", Label: "To Location", LabelI18n: localize("To Location", "Ke Lokasi"), Path: "values.to_location_id", Type: "string"},
					{Key: "from_cost_center_code", Label: "From Cost Center", LabelI18n: localize("From Cost Center", "Dari Pusat Biaya"), Path: "values.from_cost_center_code", Type: "string"},
					{Key: "to_cost_center_code", Label: "To Cost Center", LabelI18n: localize("To Cost Center", "Ke Pusat Biaya"), Path: "values.to_cost_center_code", Type: "string"},
				}),
				commercialModelListView("finance.asset_impairments.list", "Asset Impairments", "asset_impairment", []module.ColumnDefinition{
					{Key: "fixed_asset_id", Label: "Asset", LabelI18n: localize("Asset", "Aset"), Path: "values.fixed_asset_id"},
					{Key: "impairment_date", Label: "Date", LabelI18n: localize("Date", "Tanggal"), Path: "values.impairment_date"},
					{Key: "impairment_amount", Label: "Amount", LabelI18n: localize("Amount", "Jumlah"), Path: "values.impairment_amount"},
				}, []string{"posted"}),
				commercialModelDetailView("finance.asset_impairments.detail", "Asset Impairment Detail", "asset_impairment", []module.FieldDefinition{
					{Key: "fixed_asset_id", Label: "Asset", LabelI18n: localize("Asset", "Aset"), Path: "values.fixed_asset_id", Type: "string"},
					{Key: "impairment_date", Label: "Impairment Date", LabelI18n: localize("Impairment Date", "Tanggal Penurunan Nilai"), Path: "values.impairment_date", Type: "string"},
					{Key: "impairment_amount", Label: "Impairment Amount", LabelI18n: localize("Impairment Amount", "Jumlah Penurunan Nilai"), Path: "values.impairment_amount", Type: "number"},
					{Key: "posting_id", Label: "Posting", LabelI18n: localize("Posting", "Posting"), Path: "values.posting_id", Type: "string"},
				}),
				commercialModelListView("finance.asset_revaluations.list", "Asset Revaluations", "asset_revaluation", []module.ColumnDefinition{
					{Key: "fixed_asset_id", Label: "Asset", LabelI18n: localize("Asset", "Aset"), Path: "values.fixed_asset_id"},
					{Key: "revaluation_date", Label: "Date", LabelI18n: localize("Date", "Tanggal"), Path: "values.revaluation_date"},
					{Key: "revaluation_amount", Label: "Amount", LabelI18n: localize("Amount", "Jumlah"), Path: "values.revaluation_amount"},
				}, []string{"posted"}),
				commercialModelDetailView("finance.asset_revaluations.detail", "Asset Revaluation Detail", "asset_revaluation", []module.FieldDefinition{
					{Key: "fixed_asset_id", Label: "Asset", LabelI18n: localize("Asset", "Aset"), Path: "values.fixed_asset_id", Type: "string"},
					{Key: "revaluation_date", Label: "Revaluation Date", LabelI18n: localize("Revaluation Date", "Tanggal Revaluasi"), Path: "values.revaluation_date", Type: "string"},
					{Key: "revaluation_amount", Label: "Revaluation Amount", LabelI18n: localize("Revaluation Amount", "Jumlah Revaluasi"), Path: "values.revaluation_amount", Type: "number"},
					{Key: "target_carrying_amount", Label: "Target Carrying Amount", LabelI18n: localize("Target Carrying Amount", "Target Nilai Tercatat"), Path: "values.target_carrying_amount", Type: "number"},
					{Key: "posting_id", Label: "Posting", LabelI18n: localize("Posting", "Posting"), Path: "values.posting_id", Type: "string"},
				}),
			},
		},
	}
}
