package app

import (
	"orbyte/internal/platform/httpx"
	"orbyte/internal/platform/module"
)

func analyticsKernelPackManifest() module.Manifest {
	return module.Manifest{
		Key:          "analytics",
		Name:         "Analytics",
		NameI18n:     localize("Analytics", "Analitik"),
		Version:      "1.0.0",
		DomainFamily: "platform",
		DependencyRequirements: []module.DependencyRequirement{
			{ModuleKey: "documents", VersionRange: ">=1.1.0,<2.0.0", Kind: module.DependencyKindRequired},
			{ModuleKey: "monitoring", VersionRange: ">=1.0.0,<2.0.0", Kind: module.DependencyKindOptional},
		},
		OwnedProjectionKeys: []string{"document_summary"},
		AdminConsole: module.AdminConsoleDefinition{
			Title:           "Analytics Console",
			TitleI18n:       localize("Analytics Console", "Konsol Analitik"),
			Description:     "Analytics cockpit, reporting templates, and operational shortcuts.",
			DescriptionI18n: localize("Analytics cockpit, reporting templates, and operational shortcuts.", "Kokpit analitik, template pelaporan, dan pintasan operasi."),
			Sections: []module.AdminConsoleSectionDefinition{
				{
					Key:       "analytics_operations",
					Title:     "Analytics Operations",
					TitleI18n: localize("Analytics Operations", "Operasi Analitik"),
					Kind:      module.AdminConsoleSectionResourceLinks,
					Links: []module.AdminConsoleLinkDefinition{
						adminConsoleLink("cockpit", "Analytics Cockpit", "Kokpit Analitik", "/ui/analytics/cockpit", "Open the analytics cockpit.", "Buka kokpit analitik.", "analytics.read"),
						adminConsoleLink("observability", "Observability", "Observabilitas", "/admin/observability", "Open platform observability.", "Buka observabilitas platform.", "module.read"),
					},
				},
				{
					Key:       "analytics_templates",
					Title:     "Analytics Templates",
					TitleI18n: localize("Analytics Templates", "Template Analitik"),
					Kind:      module.AdminConsoleSectionTemplateLinks,
					Links: []module.AdminConsoleLinkDefinition{
						adminConsoleLink("document_reporting", "Document Reporting Print", "Cetak Pelaporan Dokumen", "/admin/templates/designer?key=analytics.document_reporting.default", "Open the document reporting print template.", "Buka template cetak pelaporan dokumen.", "template.read"),
					},
				},
			},
		},
		DocumentExtensions: []module.DocumentExtension{{
			DocumentType:       "generic_request",
			SchemaVersion:      "v1",
			DisplayName:        "Analytics Extension",
			DisplayNameI18n:    localize("Analytics Extension", "Ekstensi Analitik"),
			ReadPermissionKey:  "analytics.read",
			WritePermissionKey: "analytics.manage_reports",
		}},
		Security: module.SecurityDefinition{
			Permissions: []module.PermissionDefinition{
				{Key: "analytics.read", Action: "read", Resource: "analytics", DisplayName: "Read Analytics", DisplayNameI18n: localize("Read Analytics", "Lihat Analitik")},
				{Key: "analytics.author", Action: "author", Resource: "analytics_runtime", DisplayName: "Author Runtime Analytics", DisplayNameI18n: localize("Author Runtime Analytics", "Kelola Analitik Runtime"), RiskLevel: "high"},
				{Key: "analytics.manage_reports", Action: "manage_reports", Resource: "analytics_report", DisplayName: "Manage Analytics Reports", DisplayNameI18n: localize("Manage Analytics Reports", "Kelola Laporan Analitik"), RiskLevel: "high"},
				{Key: "analytics.deliver_reports", Action: "deliver_reports", Resource: "analytics_report", DisplayName: "Deliver Analytics Reports", DisplayNameI18n: localize("Deliver Analytics Reports", "Kirim Laporan Analitik"), RiskLevel: "high"},
			},
			RoleTemplates: []module.RoleTemplateDefinition{{
				Key: "analytics_viewer", Name: "Analytics Viewer", NameI18n: localize("Analytics Viewer", "Pembaca Analitik"), AllowedScopes: []string{"deployment", "location"}, PermissionKeys: []string{"analytics.read"},
			}},
		},
		Observability: module.ObservabilityDefinition{
			Dashboards: []module.DashboardDefinition{
				{Key: "analytics.cockpit", Title: "Analytics Cockpit", TitleI18n: localize("Analytics Cockpit", "Kokpit Analitik"), RequiredPermissions: []string{"analytics.read"}},
			},
			Reports: []module.ReportDefinition{
				{Key: "analytics.documents.reporting", Title: "Document Reporting", TitleI18n: localize("Document Reporting", "Pelaporan Dokumen"), Dataset: "document_reporting", Formats: []string{"csv", "xlsx", "pdf"}, RequiredPermissions: []string{"analytics.read"}},
			},
			Metrics: []module.MetricDefinition{
				{Key: "analytics.snapshots.total", Type: "counter", Description: "Captured analytics snapshots"},
			},
			LogEvents: []module.LogEventDefinition{{
				Key: "analytics.report.delivery", Category: "analytics", Severity: "info", RequiredFields: []string{"artifact_id", "channel", "recipient"},
			}},
			DomainEvents: []module.DomainEventDefinition{
				{Type: "analytics.snapshot.captured", Role: "producer", CorrelationRequired: true},
			},
		},
		Templates: []module.TemplateDefinition{{
			Key:                 "analytics.document_reporting.default",
			Title:               "Document Reporting Print",
			TitleI18n:           localize("Document Reporting Print", "Cetak Pelaporan Dokumen"),
			Description:         "Default printable analytics reporting template.",
			DescriptionI18n:     localize("Default printable analytics reporting template.", "Template cetak default untuk pelaporan analitik."),
			TargetKind:          "report",
			TargetKey:           "document_reporting",
			RendererKind:        "visual",
			DefaultFormat:       "html",
			Formats:             []string{"html", "pdf"},
			Purpose:             "report",
			Channel:             "print",
			AllowedScopes:       []string{"deployment", "organization", "location"},
			RequiredPermissions: []string{"template.read", "template.render", "analytics.read"},
			DefaultBody:         `{"schema_version":"visual-grid/v1","title":"Document Reporting","settings":{"paper_preset":"a4","orientation":"portrait","density":"comfortable"},"sections":[{"id":"header","title":"Summary","rows":[{"columns":[{"span":8,"blocks":[{"type":"text","text":"Document Reporting","font_size":"xl","emphasis":"strong"}]},{"span":4,"blocks":[{"type":"field","label":"Total Rows","path":"report.total","align":"right"}]}]}]},{"id":"body","title":"Rows","rows":[{"columns":[{"span":12,"blocks":[{"type":"table","rows_path":"report.rows","columns":[{"label":"Dimension","path":"dimension_key"},{"label":"Label","path":"label"},{"label":"Total","path":"total"}]}]}]}]},{"id":"footer","title":"Notes","rows":[{"columns":[{"span":12,"blocks":[{"type":"text","text":"Generated from the reporting workspace.","align":"right","emphasis":"muted"}]}]}]}]}`,
			DefaultStyle:        `.template-visual{font-family:Arial,sans-serif;color:#0f172a}`,
		}},
		Frontend: module.FrontendDefinition{
			Menus: []module.MenuDefinition{{
				Key:                 "analytics.cockpit",
				Label:               "Analytics Cockpit",
				LabelI18n:           localize("Analytics Cockpit", "Kokpit Analitik"),
				ActionKey:           "analytics.cockpit",
				Order:               20,
				RequiredPermissions: []string{"analytics.read"},
			}, {
				Key:                 "dashboard.surface",
				Label:               "Dashboard",
				LabelI18n:           localize("Dashboard", "Dasbor"),
				ActionKey:           "dashboard.surface",
				Order:               10,
				Surface:             module.UISurfaceDashboard,
				RequiredPermissions: []string{"analytics.read"},
			}, {
				Key:                 "analytics.dashboard_boards",
				Label:               "Dashboards",
				LabelI18n:           localize("Dashboards", "Dasbor"),
				ActionKey:           "analytics.dashboard_boards",
				Order:               26,
				Surface:             module.UISurfaceAdmin,
				RequiredPermissions: []string{"analytics.read"},
			}},
			Actions: []module.ActionDefinition{{
				Key:                 "analytics.cockpit",
				Label:               "Analytics Cockpit",
				LabelI18n:           localize("Analytics Cockpit", "Kokpit Analitik"),
				Kind:                "navigate",
				RoutePath:           "/analytics/cockpit",
				CustomEntryKey:      "analytics.cockpit",
				RenderMode:          module.RenderModeCustom,
				RequiredPermissions: []string{"analytics.read"},
			}, {
				Key:                 "dashboard.surface",
				Label:               "Dashboard",
				LabelI18n:           localize("Dashboard", "Dasbor"),
				Kind:                "navigate",
				RoutePath:           "/dashboard",
				ViewKey:             "dashboard.surface",
				RenderMode:          module.RenderModeGeneric,
				Surface:             module.UISurfaceDashboard,
				RequiredPermissions: []string{"analytics.read"},
			}, {
				Key:                 "analytics.dashboard_boards",
				Label:               "Dashboards",
				LabelI18n:           localize("Dashboards", "Dasbor"),
				Kind:                "navigate",
				RoutePath:           "/dashboards",
				ViewKey:             "analytics.dashboard_boards",
				RenderMode:          module.RenderModeGeneric,
				Surface:             module.UISurfaceAdmin,
				RequiredPermissions: []string{"analytics.read"},
			}},
			Views: []module.ViewDefinition{
				{
					Key:                 "dashboard.surface",
					Title:               "Dashboard",
					TitleI18n:           localize("Dashboard", "Dasbor"),
					Kind:                "dashboard",
					RequiredPermissions: []string{"analytics.read"},
					Surface:             module.UISurfaceDashboard,
				},
				{
					Key:                 "analytics.dashboard_boards",
					Title:               "Dashboards",
					TitleI18n:           localize("Dashboards", "Dasbor"),
					Kind:                "list",
					RequiredPermissions: []string{"analytics.read"},
					Surface:             module.UISurfaceAdmin,
				},
			},
			CustomEntries: []module.CustomEntryDefinition{{
				Key:                 "analytics.cockpit",
				Title:               "Analytics Cockpit",
				TitleI18n:           localize("Analytics Cockpit", "Kokpit Analitik"),
				RoutePath:           "/analytics/cockpit",
				BundleKey:           "analytics-cockpit",
				ComponentExport:     "render",
				RequiredPermissions: []string{"analytics.read"},
			}},
			DashboardWidgets: []module.DashboardWidgetDefinition{
				{
					Key:                 "analytics.snapshot.submitted_documents",
					Title:               "Submitted Documents",
					TitleI18n:           localize("Submitted Documents", "Dokumen Dikirim"),
					Surface:             module.UISurfaceDashboard,
					RendererKind:        "metric",
					RefreshPolicy:       "hourly",
					DataPath:            "/ui/data/analytics/snapshot",
					RequiredPermissions: []string{"analytics.read"},
					DefaultWidth:        3,
					DefaultHeight:       1,
					Metric: &module.DashboardMetricSpec{
						ValuePath: "documents.submitted",
						Format:    "number",
					},
				},
				{
					Key:                 "analytics.snapshot.pending_approvals",
					Title:               "Pending Approvals",
					TitleI18n:           localize("Pending Approvals", "Persetujuan Tertunda"),
					Surface:             module.UISurfaceDashboard,
					RendererKind:        "metric",
					RefreshPolicy:       "hourly",
					DataPath:            "/ui/data/analytics/snapshot",
					RequiredPermissions: []string{"analytics.read"},
					DefaultWidth:        3,
					DefaultHeight:       1,
					Metric: &module.DashboardMetricSpec{
						ValuePath: "workflow.pending_approvals",
						Format:    "number",
					},
				},
				{
					Key:                 "analytics.demo.submitted_documents",
					Title:               "Submitted Documents",
					TitleI18n:           localize("Submitted Documents", "Dokumen Dikirim"),
					Surface:             module.UISurfaceDashboard,
					RendererKind:        "metric",
					RefreshPolicy:       "minutes",
					DataPath:            "/ui/data/dashboard/demo",
					RequiredPermissions: []string{"analytics.read"},
					DefaultWidth:        3,
					DefaultHeight:       1,
					Metric: &module.DashboardMetricSpec{
						ValuePath: "overview.submitted_documents",
						DeltaPath: "comparison.delta.submitted_documents",
						Format:    "number",
					},
				},
				{
					Key:                 "analytics.demo.approval_rate",
					Title:               "Approval Rate",
					TitleI18n:           localize("Approval Rate", "Tingkat Persetujuan"),
					Surface:             module.UISurfaceDashboard,
					RendererKind:        "gauge",
					RefreshPolicy:       "minutes",
					DataPath:            "/ui/data/dashboard/demo",
					RequiredPermissions: []string{"analytics.read"},
					DefaultWidth:        3,
					DefaultHeight:       2,
					Gauge: &module.DashboardGaugeSpec{
						ValuePath:  "overview.approval_rate_percent",
						MinValue:   0,
						MaxValue:   100,
						Thresholds: []float64{60, 80, 95},
						Format:     "percent",
					},
				},
				{
					Key:                 "analytics.demo.submission_trend",
					Title:               "Submission Trend",
					TitleI18n:           localize("Submission Trend", "Tren Pengiriman"),
					Surface:             module.UISurfaceDashboard,
					RendererKind:        "chart_line",
					RefreshPolicy:       "minutes",
					DataPath:            "/ui/data/dashboard/demo",
					RequiredPermissions: []string{"analytics.read"},
					DefaultWidth:        6,
					DefaultHeight:       2,
					Chart: &module.DashboardChartSpec{
						SeriesPath: "trends.documents",
						Category:   "label",
						Value:      "submitted_documents",
						Format:     "number",
					},
				},
				{
					Key:                 "analytics.demo.document_mix",
					Title:               "Document Type Mix",
					TitleI18n:           localize("Document Type Mix", "Campuran Tipe Dokumen"),
					Surface:             module.UISurfaceDashboard,
					RendererKind:        "chart_bar",
					RefreshPolicy:       "minutes",
					DataPath:            "/ui/data/dashboard/demo",
					RequiredPermissions: []string{"analytics.read"},
					DefaultWidth:        6,
					DefaultHeight:       2,
					Chart: &module.DashboardChartSpec{
						SeriesPath: "charts.document_types",
						Category:   "document_type",
						Value:      "submitted",
						Format:     "number",
					},
				},
				{
					Key:                 "analytics.demo.document_breakdown",
					Title:               "Document Breakdown",
					TitleI18n:           localize("Document Breakdown", "Rincian Dokumen"),
					Surface:             module.UISurfaceDashboard,
					RendererKind:        "table",
					RefreshPolicy:       "minutes",
					DataPath:            "/ui/data/dashboard/demo",
					RequiredPermissions: []string{"analytics.read"},
					DefaultWidth:        6,
					DefaultHeight:       2,
					Table: &module.DashboardTableSpec{
						RowsPath: "tables.document_types",
						Columns: []module.ColumnDefinition{
							{Key: "document_type", Label: "Document", LabelI18n: localize("Document", "Dokumen"), Path: "document_type"},
							{Key: "created", Label: "Created", LabelI18n: localize("Created", "Dibuat"), Path: "created"},
							{Key: "submitted", Label: "Submitted", LabelI18n: localize("Submitted", "Dikirim"), Path: "submitted"},
							{Key: "approved", Label: "Approved", LabelI18n: localize("Approved", "Disetujui"), Path: "approved"},
						},
					},
				},
				{
					Key:                 "analytics.demo.branch_map",
					Title:               "Branch Performance",
					TitleI18n:           localize("Branch Performance", "Kinerja Cabang"),
					Surface:             module.UISurfaceDashboard,
					RendererKind:        "map",
					RefreshPolicy:       "minutes",
					DataPath:            "/ui/data/dashboard/demo",
					RequiredPermissions: []string{"analytics.read"},
					DefaultWidth:        6,
					DefaultHeight:       2,
					Map: &module.DashboardMapSpec{
						PointsPath: "map.branches",
						Latitude:   "latitude",
						Longitude:  "longitude",
						Label:      "label",
						Value:      "submitted",
					},
				},
				{
					Key:                 "analytics.demo.sales.net_sales",
					Title:               "Demo Net Sales",
					TitleI18n:           localize("Demo Net Sales", "Penjualan Bersih Demo"),
					Surface:             module.UISurfaceDashboard,
					RendererKind:        "metric",
					RefreshPolicy:       "minutes",
					DataPath:            "/ui/data/dashboard/sales-demo",
					RequiredPermissions: []string{"analytics.read"},
					DefaultWidth:        3,
					DefaultHeight:       1,
					Metric: &module.DashboardMetricSpec{
						ValuePath:  "overview.net_sales",
						TargetPath: "overview.target_sales",
						Format:     "currency",
					},
				},
				{
					Key:                 "analytics.demo.sales.target_attainment",
					Title:               "Demo Target Attainment",
					TitleI18n:           localize("Demo Target Attainment", "Pencapaian Target Demo"),
					Surface:             module.UISurfaceDashboard,
					RendererKind:        "gauge",
					RefreshPolicy:       "minutes",
					DataPath:            "/ui/data/dashboard/sales-demo",
					RequiredPermissions: []string{"analytics.read"},
					DefaultWidth:        3,
					DefaultHeight:       2,
					Gauge: &module.DashboardGaugeSpec{
						ValuePath:  "overview.target_attainment_percent",
						MinValue:   0,
						MaxValue:   100,
						Thresholds: []float64{70, 90, 100},
						Format:     "percent",
					},
				},
				{
					Key:                 "analytics.demo.sales.daily_trend",
					Title:               "Demo Daily Sales Trend",
					TitleI18n:           localize("Demo Daily Sales Trend", "Tren Penjualan Harian Demo"),
					Surface:             module.UISurfaceDashboard,
					RendererKind:        "chart_line",
					RefreshPolicy:       "minutes",
					DataPath:            "/ui/data/dashboard/sales-demo",
					RequiredPermissions: []string{"analytics.read"},
					DefaultWidth:        6,
					DefaultHeight:       2,
					Chart: &module.DashboardChartSpec{
						SeriesPath: "trends.sales",
						Category:   "label",
						Value:      "net_sales",
						Format:     "currency",
					},
				},
				{
					Key:                 "analytics.demo.sales.branch_mix",
					Title:               "Demo Branch Sales Mix",
					TitleI18n:           localize("Demo Branch Sales Mix", "Campuran Penjualan Cabang Demo"),
					Surface:             module.UISurfaceDashboard,
					RendererKind:        "chart_bar",
					RefreshPolicy:       "minutes",
					DataPath:            "/ui/data/dashboard/sales-demo",
					RequiredPermissions: []string{"analytics.read"},
					DefaultWidth:        6,
					DefaultHeight:       2,
					Chart: &module.DashboardChartSpec{
						SeriesPath: "charts.branches",
						Category:   "branch",
						Value:      "net_sales",
						Format:     "currency",
					},
				},
				{
					Key:                 "analytics.demo.sales.branch_table",
					Title:               "Demo Branch Sales Breakdown",
					TitleI18n:           localize("Demo Branch Sales Breakdown", "Rincian Penjualan Cabang Demo"),
					Surface:             module.UISurfaceDashboard,
					RendererKind:        "table",
					RefreshPolicy:       "minutes",
					DataPath:            "/ui/data/dashboard/sales-demo",
					RequiredPermissions: []string{"analytics.read"},
					DefaultWidth:        6,
					DefaultHeight:       2,
					Table: &module.DashboardTableSpec{
						RowsPath: "tables.branches",
						Columns: []module.ColumnDefinition{
							{Key: "branch", Label: "Branch", LabelI18n: localize("Branch", "Cabang"), Path: "branch"},
							{Key: "net_sales", Label: "Net Sales", LabelI18n: localize("Net Sales", "Penjualan Bersih"), Path: "net_sales"},
							{Key: "orders", Label: "Orders", LabelI18n: localize("Orders", "Pesanan"), Path: "orders"},
							{Key: "variance_to_target", Label: "Vs Target", LabelI18n: localize("Vs Target", "Vs Target"), Path: "variance_to_target"},
						},
					},
				},
				{
					Key:                 "analytics.demo.sales.branch_map",
					Title:               "Demo Branch Performance",
					TitleI18n:           localize("Demo Branch Performance", "Kinerja Cabang Demo"),
					Surface:             module.UISurfaceDashboard,
					RendererKind:        "map",
					RefreshPolicy:       "minutes",
					DataPath:            "/ui/data/dashboard/sales-demo",
					RequiredPermissions: []string{"analytics.read"},
					DefaultWidth:        6,
					DefaultHeight:       2,
					Map: &module.DashboardMapSpec{
						PointsPath: "map.branches",
						Latitude:   "latitude",
						Longitude:  "longitude",
						Label:      "label",
						Value:      "net_sales",
					},
				},
			},
		},
		MCP: module.MCPDefinition{
			Tools: []module.MCPToolDefinition{{
				Key:                 "analytics.snapshot.get",
				Title:               "Get Analytics Snapshot",
				TitleI18n:           localize("Get Analytics Snapshot", "Ambil Snapshot Analitik"),
				Description:         "Returns the latest analytics snapshot and links the cockpit app.",
				DescriptionI18n:     localize("Returns the latest analytics snapshot and links the cockpit app.", "Mengembalikan snapshot analitik terbaru dan menautkan aplikasi kokpit."),
				Operation:           "analytics.snapshot.get",
				RequiredPermissions: []string{"analytics.read"},
				AppKey:              "analytics.cockpit",
			}},
			Resources: []module.MCPResourceDefinition{
				{
					Key:                 "analytics.snapshot.current",
					Title:               "Current Analytics Snapshot",
					TitleI18n:           localize("Current Analytics Snapshot", "Snapshot Analitik Saat Ini"),
					Description:         "Structured current-state analytics snapshot.",
					DescriptionI18n:     localize("Structured current-state analytics snapshot.", "Snapshot analitik terstruktur untuk kondisi saat ini."),
					URI:                 "orbyte://analytics/snapshot/current",
					MIMEType:            "application/json",
					Provider:            "analytics.snapshot.current",
					RequiredPermissions: []string{"analytics.read"},
				},
				{
					Key:                 "analytics.cockpit.app",
					Title:               "Analytics Cockpit App",
					TitleI18n:           localize("Analytics Cockpit App", "Aplikasi Kokpit Analitik"),
					Description:         "Inline MCP app resource for the analytics cockpit.",
					DescriptionI18n:     localize("Inline MCP app resource for the analytics cockpit.", "Resource aplikasi MCP inline untuk kokpit analitik."),
					URI:                 "orbyte://apps/analytics.cockpit",
					MIMEType:            "text/html",
					Provider:            "mcp.app",
					RequiredPermissions: []string{"analytics.read"},
					AppKey:              "analytics.cockpit",
				},
			},
			Apps: []module.MCPAppDefinition{{
				Key:                 "analytics.cockpit",
				Title:               "Analytics Cockpit",
				TitleI18n:           localize("Analytics Cockpit", "Kokpit Analitik"),
				Description:         "Interactive analytics cockpit for MCP-capable hosts.",
				DescriptionI18n:     localize("Interactive analytics cockpit for MCP-capable hosts.", "Kokpit analitik interaktif untuk host yang mendukung MCP."),
				ResourceKey:         "analytics.cockpit.app",
				CustomEntryKey:      "analytics.cockpit",
				RequiredPermissions: []string{"analytics.read"},
			}},
		},
		Bundles: []module.BundleDefinition{{
			Key:    "analytics-cockpit",
			Script: httpx.AnalyticsCockpitBundle(),
		}},
	}
}
