package app

import (
	"orbyte/internal/platform/model"
	"orbyte/internal/platform/module"
)

func treasuryCoreKernelPackManifests() []module.Manifest {
	return []module.Manifest{treasuryCoreKernelPackManifest()}
}

func treasuryCoreKernelPackManifest() module.Manifest {
	return module.Manifest{
		Key:                    "treasury_core",
		Name:                   "Treasury Core",
		NameI18n:               localize("Treasury Core", "Inti Treasury"),
		Version:                "1.0.0",
		DomainFamily:           "business",
		DependencyRequirements: requiredModuleDependencies("finance_reporting_core", "retail_finance_core", "commercial_core", "procurement_core"),
		AdminConsole: module.AdminConsoleDefinition{
			Title:           "Treasury Console",
			TitleI18n:       localize("Treasury Console", "Konsol Treasury"),
			Description:     "Bank statements, cash position, treasury exceptions, and transfers.",
			DescriptionI18n: localize("Bank statements, cash position, treasury exceptions, and transfers.", "Mutasi bank, posisi kas, exception treasury, dan transfer."),
			Sections: []module.AdminConsoleSectionDefinition{{
				Key:       "treasury",
				Kind:      module.AdminConsoleSectionResourceLinks,
				Title:     "Treasury",
				TitleI18n: localize("Treasury", "Treasury"),
				Links: []module.AdminConsoleLinkDefinition{
					adminConsoleLink("treasury_accounts", "Treasury Accounts", "Akun Treasury", "/ui/finance/treasury-accounts", "Manage bank and petty cash accounts.", "Kelola akun bank dan petty cash.", "treasury_account.list"),
					adminConsoleLink("bank_statements", "Bank Statements", "Mutasi Bank", "/ui/finance/bank-statements", "Manage imported and manual bank statements.", "Kelola mutasi bank hasil impor dan manual.", "bank_statement.list"),
					adminConsoleLink("bank_import_templates", "Bank Import Templates", "Template Impor Bank", "/ui/finance/bank-import-templates", "Manage reusable bank import templates.", "Kelola template impor bank yang dapat digunakan ulang.", "bank_import_template.list"),
					adminConsoleLink("bank_import_runs", "Statement Import Runs", "Riwayat Impor Statement", "/ui/finance/bank-import-runs", "Review bank statement import runs and warnings.", "Tinjau riwayat impor statement bank dan peringatannya.", "bank_statement_import_run.list"),
					adminConsoleLink("bank_reconciliations", "Bank Reconciliations", "Rekonsiliasi Bank", "/ui/finance/bank-reconciliation", "Review bank reconciliations.", "Tinjau rekonsiliasi bank.", "bank_reconciliation.list"),
					adminConsoleLink("cash_position", "Cash Position", "Posisi Kas", "/ui/finance/cash-position", "Review treasury cash positions.", "Tinjau posisi kas treasury.", "finance.read"),
					adminConsoleLink("clearing_balance", "Clearing Balance", "Saldo Clearing", "/ui/finance/clearing-balance", "Review open clearing balances.", "Tinjau saldo clearing terbuka.", "finance.read"),
					adminConsoleLink("treasury_exceptions", "Treasury Exceptions", "Exception Treasury", "/ui/finance/treasury-exceptions", "Review unmatched bank and treasury items.", "Tinjau item bank dan treasury yang belum cocok.", "treasury_exception.list"),
					adminConsoleLink("treasury_transfers", "Treasury Transfers", "Transfer Treasury", "/ui/finance/treasury-transfers", "Manage cash and bank transfers.", "Kelola transfer kas dan bank.", "treasury_transfer.list"),
				},
			}},
		},
		Models: []model.Definition{
			treasuryModelDefinition("treasury_account", "Treasury Account", []model.FieldDefinition{
				{Key: "organization_id", Type: "string", Required: true},
				{Key: "location_id", Type: "string"},
				{Key: "account_code", Type: "string", Required: true},
				{Key: "name", Type: "string", Required: true},
				{Key: "treasury_type", Type: "string", Required: true, DefaultValue: "bank"},
				{Key: "currency_code", Type: "string", DefaultValue: "IDR"},
				{Key: "gl_account_code", Type: "string", Required: true},
				{Key: "clearing_account_code", Type: "string"},
				{Key: "bank_name", Type: "string"},
				{Key: "bank_account_number", Type: "string"},
				{Key: "store_code", Type: "string"},
				{Key: "status", Type: "string", DefaultValue: "active"},
			}),
			treasuryModelDefinition("bank_statement", "Bank Statement", []model.FieldDefinition{
				{Key: "organization_id", Type: "string", Required: true},
				{Key: "location_id", Type: "string"},
				{Key: "treasury_account_id", Type: "string", Required: true},
				{Key: "statement_number", Type: "string", Required: true},
				{Key: "statement_date", Type: "string", Required: true},
				{Key: "from_date", Type: "string"},
				{Key: "to_date", Type: "string"},
				{Key: "opening_balance", Type: "number"},
				{Key: "closing_balance", Type: "number"},
				{Key: "import_method", Type: "string", DefaultValue: "manual"},
				{Key: "source_file_name", Type: "string"},
				{Key: "status", Type: "string", DefaultValue: "draft"},
			}),
			treasuryModelDefinition("bank_statement_line", "Bank Statement Line", []model.FieldDefinition{
				{Key: "organization_id", Type: "string", Required: true},
				{Key: "location_id", Type: "string"},
				{Key: "bank_statement_id", Type: "string", Required: true},
				{Key: "treasury_account_id", Type: "string", Required: true},
				{Key: "statement_date", Type: "string"},
				{Key: "value_date", Type: "string"},
				{Key: "reference", Type: "string"},
				{Key: "description", Type: "string"},
				{Key: "debit_amount", Type: "number"},
				{Key: "credit_amount", Type: "number"},
				{Key: "signed_amount", Type: "number"},
				{Key: "running_balance", Type: "number"},
				{Key: "matched_amount", Type: "number"},
				{Key: "remaining_amount", Type: "number"},
				{Key: "match_status", Type: "string", DefaultValue: "open"},
				{Key: "matched_source_type", Type: "string"},
				{Key: "matched_source_id", Type: "string"},
			}),
			treasuryModelDefinition("bank_import_template", "Bank Import Template", []model.FieldDefinition{
				{Key: "organization_id", Type: "string", Required: true},
				{Key: "location_id", Type: "string"},
				{Key: "treasury_account_id", Type: "string"},
				{Key: "template_code", Type: "string", Required: true},
				{Key: "name", Type: "string", Required: true},
				{Key: "bank_name", Type: "string"},
				{Key: "format_key", Type: "string"},
				{Key: "header_row_index", Type: "number"},
				{Key: "date_column", Type: "string"},
				{Key: "value_date_column", Type: "string"},
				{Key: "reference_column", Type: "string"},
				{Key: "external_reference_column", Type: "string"},
				{Key: "description_column", Type: "string"},
				{Key: "debit_column", Type: "string"},
				{Key: "credit_column", Type: "string"},
				{Key: "amount_column", Type: "string"},
				{Key: "balance_column", Type: "string"},
				{Key: "date_format", Type: "string"},
				{Key: "decimal_separator", Type: "string"},
				{Key: "thousands_separator", Type: "string"},
				{Key: "sign_convention", Type: "string", DefaultValue: "credit_minus_debit"},
				{Key: "header_aliases_json", Type: "string"},
				{Key: "status", Type: "string", DefaultValue: "active"},
			}),
			treasuryModelDefinition("bank_import_preset", "Bank Import Preset", []model.FieldDefinition{
				{Key: "preset_key", Type: "string", Required: true},
				{Key: "name", Type: "string", Required: true},
				{Key: "bank_name", Type: "string"},
				{Key: "format_key", Type: "string"},
				{Key: "header_row_index", Type: "number"},
				{Key: "date_column", Type: "string"},
				{Key: "value_date_column", Type: "string"},
				{Key: "reference_column", Type: "string"},
				{Key: "external_reference_column", Type: "string"},
				{Key: "description_column", Type: "string"},
				{Key: "debit_column", Type: "string"},
				{Key: "credit_column", Type: "string"},
				{Key: "amount_column", Type: "string"},
				{Key: "balance_column", Type: "string"},
				{Key: "date_format", Type: "string"},
				{Key: "decimal_separator", Type: "string"},
				{Key: "thousands_separator", Type: "string"},
				{Key: "sign_convention", Type: "string", DefaultValue: "credit_minus_debit"},
				{Key: "header_aliases_json", Type: "string"},
				{Key: "status", Type: "string", DefaultValue: "active"},
			}),
			treasuryModelDefinition("bank_statement_import_run", "Bank Statement Import Run", []model.FieldDefinition{
				{Key: "organization_id", Type: "string", Required: true},
				{Key: "location_id", Type: "string"},
				{Key: "treasury_account_id", Type: "string"},
				{Key: "bank_statement_id", Type: "string"},
				{Key: "bank_import_template_id", Type: "string"},
				{Key: "preset_key", Type: "string"},
				{Key: "source_file_name", Type: "string"},
				{Key: "row_count", Type: "number"},
				{Key: "duplicate_count", Type: "number"},
				{Key: "warning_count", Type: "number"},
				{Key: "warnings_json", Type: "string"},
				{Key: "status", Type: "string", DefaultValue: "draft"},
			}),
			treasuryModelDefinition("bank_reconciliation", "Bank Reconciliation", []model.FieldDefinition{
				{Key: "organization_id", Type: "string", Required: true},
				{Key: "location_id", Type: "string"},
				{Key: "treasury_account_id", Type: "string", Required: true},
				{Key: "bank_statement_id", Type: "string", Required: true},
				{Key: "reconciliation_date", Type: "string"},
				{Key: "book_balance", Type: "number"},
				{Key: "statement_balance", Type: "number"},
				{Key: "matched_amount", Type: "number"},
				{Key: "outstanding_book_amount", Type: "number"},
				{Key: "difference_amount", Type: "number"},
				{Key: "status", Type: "string", DefaultValue: "draft"},
				{Key: "approved_by", Type: "string"},
				{Key: "approved_at", Type: "string"},
			}),
			treasuryModelDefinition("bank_match_rule", "Bank Match Rule", []model.FieldDefinition{
				{Key: "organization_id", Type: "string", Required: true},
				{Key: "location_id", Type: "string"},
				{Key: "name", Type: "string", Required: true},
				{Key: "source_type", Type: "string"},
				{Key: "reference_contains", Type: "string"},
				{Key: "description_contains", Type: "string"},
				{Key: "date_tolerance_days", Type: "number"},
				{Key: "priority_weight", Type: "number"},
				{Key: "status", Type: "string", DefaultValue: "active"},
			}),
			treasuryModelDefinition("bank_reconciliation_match", "Bank Reconciliation Match", []model.FieldDefinition{
				{Key: "organization_id", Type: "string", Required: true},
				{Key: "location_id", Type: "string"},
				{Key: "bank_reconciliation_id", Type: "string", Required: true},
				{Key: "bank_statement_line_id", Type: "string", Required: true},
				{Key: "matched_source_type", Type: "string", Required: true},
				{Key: "matched_source_id", Type: "string", Required: true},
				{Key: "matched_amount", Type: "number"},
				{Key: "match_kind", Type: "string", DefaultValue: "manual"},
				{Key: "notes", Type: "string"},
			}),
			treasuryModelDefinition("treasury_transfer", "Treasury Transfer", []model.FieldDefinition{
				{Key: "organization_id", Type: "string", Required: true},
				{Key: "location_id", Type: "string"},
				{Key: "transfer_date", Type: "string", Required: true},
				{Key: "from_treasury_account_id", Type: "string", Required: true},
				{Key: "to_treasury_account_id", Type: "string", Required: true},
				{Key: "from_account_code", Type: "string"},
				{Key: "to_account_code", Type: "string"},
				{Key: "amount", Type: "number", Required: true},
				{Key: "reference", Type: "string"},
				{Key: "posting_id", Type: "string"},
				{Key: "status", Type: "string", DefaultValue: "draft"},
				{Key: "notes", Type: "string"},
			}),
			treasuryModelDefinition("treasury_exception", "Treasury Exception", []model.FieldDefinition{
				{Key: "organization_id", Type: "string", Required: true},
				{Key: "location_id", Type: "string"},
				{Key: "treasury_account_id", Type: "string"},
				{Key: "bank_statement_id", Type: "string"},
				{Key: "bank_statement_line_id", Type: "string"},
				{Key: "exception_kind", Type: "string", Required: true},
				{Key: "statement_date", Type: "string"},
				{Key: "description", Type: "string"},
				{Key: "amount", Type: "number"},
				{Key: "status", Type: "string", DefaultValue: "open"},
				{Key: "note", Type: "string"},
				{Key: "resolved_at", Type: "string"},
				{Key: "resolved_by", Type: "string"},
			}),
		},
		Security: module.SecurityDefinition{
			Permissions: append(
				append(
					append(
						commercialModelPermissions("treasury_account", "Treasury Account"),
						commercialModelPermissions("bank_statement", "Bank Statement")...,
					),
					append(
						commercialModelPermissions("bank_statement_line", "Bank Statement Line"),
						append(
							commercialModelPermissions("bank_reconciliation", "Bank Reconciliation"),
							append(
								commercialModelPermissions("bank_reconciliation_match", "Bank Reconciliation Match"),
								append(
									commercialModelPermissions("bank_import_template", "Bank Import Template"),
									append(
										commercialModelPermissions("bank_import_preset", "Bank Import Preset"),
										append(
											commercialModelPermissions("bank_statement_import_run", "Bank Statement Import Run"),
											commercialModelPermissions("bank_match_rule", "Bank Match Rule")...,
										)...,
									)...,
								)...,
							)...,
						)...,
					)...,
				),
				append(
					append(
						commercialModelPermissions("treasury_transfer", "Treasury Transfer"),
						commercialModelPermissions("treasury_exception", "Treasury Exception")...,
					),
					[]module.PermissionDefinition{
						{Key: "treasury.manage", Action: "manage", Resource: "treasury", DisplayName: "Manage Treasury", DisplayNameI18n: localize("Manage Treasury", "Kelola Treasury")},
						{Key: "treasury.reconcile", Action: "reconcile", Resource: "treasury", DisplayName: "Reconcile Treasury", DisplayNameI18n: localize("Reconcile Treasury", "Rekonsiliasi Treasury")},
					}...,
				)...,
			),
			RoleTemplates: []module.RoleTemplateDefinition{{
				Key:           "treasury_manager",
				Name:          "Treasury Manager",
				NameI18n:      localize("Treasury Manager", "Manajer Treasury"),
				AllowedScopes: []string{"deployment", "organization", "location"},
				PermissionKeys: []string{
					"treasury_account.create", "treasury_account.list", "treasury_account.read", "treasury_account.update",
					"bank_statement.create", "bank_statement.list", "bank_statement.read", "bank_statement.update",
					"bank_statement_line.create", "bank_statement_line.list", "bank_statement_line.read", "bank_statement_line.update",
					"bank_reconciliation.create", "bank_reconciliation.list", "bank_reconciliation.read", "bank_reconciliation.update",
					"bank_reconciliation_match.create", "bank_reconciliation_match.list", "bank_reconciliation_match.read", "bank_reconciliation_match.update",
					"treasury_transfer.create", "treasury_transfer.list", "treasury_transfer.read", "treasury_transfer.update",
					"treasury_exception.create", "treasury_exception.list", "treasury_exception.read", "treasury_exception.update",
					"treasury.manage", "treasury.reconcile", "finance.read", "document.create", "document.read", "document.approve",
				},
			}},
		},
		Frontend: module.FrontendDefinition{
			Menus: []module.MenuDefinition{
				{Key: "finance.cash_position", Label: "Cash Position", LabelI18n: localize("Cash Position", "Posisi Kas"), ActionKey: "finance.cash_position", Order: 117, RequiredPermissions: []string{"finance.read"}},
				{Key: "finance.clearing_balance", Label: "Clearing Balance", LabelI18n: localize("Clearing Balance", "Saldo Clearing"), ActionKey: "finance.clearing_balance", Order: 118, RequiredPermissions: []string{"finance.read"}},
				{Key: "finance.bank_reconciliation", Label: "Bank Reconciliation", LabelI18n: localize("Bank Reconciliation", "Rekonsiliasi Bank"), ActionKey: "finance.bank_reconciliation", Order: 119, RequiredPermissions: []string{"finance.read", "bank_statement.read"}},
				{Key: "finance.bank_import_templates", Label: "Bank Import Templates", LabelI18n: localize("Bank Import Templates", "Template Impor Bank"), ActionKey: "finance.bank_import_templates.list", Order: 119, RequiredPermissions: []string{"bank_import_template.list"}},
				{Key: "finance.bank_import_runs", Label: "Statement Import Runs", LabelI18n: localize("Statement Import Runs", "Riwayat Impor Statement"), ActionKey: "finance.bank_import_runs.list", Order: 119, RequiredPermissions: []string{"bank_statement_import_run.list"}},
				{Key: "finance.treasury_exceptions", Label: "Treasury Exceptions", LabelI18n: localize("Treasury Exceptions", "Exception Treasury"), ActionKey: "finance.treasury_exceptions", Order: 120, RequiredPermissions: []string{"treasury_exception.list"}},
				{Key: "finance.treasury_accounts", Label: "Treasury Accounts", LabelI18n: localize("Treasury Accounts", "Akun Treasury"), ActionKey: "finance.treasury_accounts.list", Order: 121, RequiredPermissions: []string{"treasury_account.list"}},
				{Key: "finance.bank_statements", Label: "Bank Statements", LabelI18n: localize("Bank Statements", "Mutasi Bank"), ActionKey: "finance.bank_statements.list", Order: 122, RequiredPermissions: []string{"bank_statement.list"}},
				{Key: "finance.treasury_transfers", Label: "Treasury Transfers", LabelI18n: localize("Treasury Transfers", "Transfer Treasury"), ActionKey: "finance.treasury_transfers.list", Order: 123, RequiredPermissions: []string{"treasury_transfer.list"}},
			},
			Actions: []module.ActionDefinition{
				{Key: "finance.cash_position", Label: "Cash Position", LabelI18n: localize("Cash Position", "Posisi Kas"), Kind: "navigate", RoutePath: "/finance/cash-position", CustomEntryKey: "finance.cash_position", RenderMode: module.RenderModeCustom, RequiredPermissions: []string{"finance.read"}},
				{Key: "finance.clearing_balance", Label: "Clearing Balance", LabelI18n: localize("Clearing Balance", "Saldo Clearing"), Kind: "navigate", RoutePath: "/finance/clearing-balance", CustomEntryKey: "finance.clearing_balance", RenderMode: module.RenderModeCustom, RequiredPermissions: []string{"finance.read"}},
				{Key: "finance.bank_reconciliation", Label: "Bank Reconciliation", LabelI18n: localize("Bank Reconciliation", "Rekonsiliasi Bank"), Kind: "navigate", RoutePath: "/finance/bank-reconciliation", CustomEntryKey: "finance.bank_reconciliation", RenderMode: module.RenderModeCustom, RequiredPermissions: []string{"finance.read", "bank_statement.read"}},
				{Key: "finance.bank_import_templates.list", Label: "Bank Import Templates", LabelI18n: localize("Bank Import Templates", "Template Impor Bank"), Kind: "navigate", RoutePath: "/finance/bank-import-templates", ViewKey: "finance.bank_import_templates.list", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"bank_import_template.list"}},
				{Key: "finance.bank_import_runs.list", Label: "Statement Import Runs", LabelI18n: localize("Statement Import Runs", "Riwayat Impor Statement"), Kind: "navigate", RoutePath: "/finance/bank-import-runs", ViewKey: "finance.bank_import_runs.list", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"bank_statement_import_run.list"}},
				{Key: "finance.treasury_exceptions", Label: "Treasury Exceptions", LabelI18n: localize("Treasury Exceptions", "Exception Treasury"), Kind: "navigate", RoutePath: "/finance/treasury-exceptions", CustomEntryKey: "finance.treasury_exceptions", RenderMode: module.RenderModeCustom, RequiredPermissions: []string{"treasury_exception.list"}},
				{Key: "finance.treasury_accounts.list", Label: "Treasury Accounts", LabelI18n: localize("Treasury Accounts", "Akun Treasury"), Kind: "navigate", RoutePath: "/finance/treasury-accounts", ViewKey: "finance.treasury_accounts.list", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"treasury_account.list"}},
				{Key: "finance.bank_statements.list", Label: "Bank Statements", LabelI18n: localize("Bank Statements", "Mutasi Bank"), Kind: "navigate", RoutePath: "/finance/bank-statements", ViewKey: "finance.bank_statements.list", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"bank_statement.list"}},
				{Key: "finance.treasury_transfers.list", Label: "Treasury Transfers", LabelI18n: localize("Treasury Transfers", "Transfer Treasury"), Kind: "navigate", RoutePath: "/finance/treasury-transfers", ViewKey: "finance.treasury_transfers.list", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{"treasury_transfer.list"}},
			},
			Views: []module.ViewDefinition{
				commercialModelListView("finance.treasury_accounts.list", "Treasury Accounts", "treasury_account", []module.ColumnDefinition{
					{Key: "account_code", Label: "Code", Path: "values.account_code"},
					{Key: "name", Label: "Name", Path: "values.name"},
					{Key: "treasury_type", Label: "Type", Path: "values.treasury_type"},
					{Key: "gl_account_code", Label: "GL Account", Path: "values.gl_account_code"},
					{Key: "status", Label: "Status", Path: "values.status"},
				}, []string{"active", "inactive"}),
				commercialModelListView("finance.bank_statements.list", "Bank Statements", "bank_statement", []module.ColumnDefinition{
					{Key: "statement_number", Label: "Statement", Path: "values.statement_number"},
					{Key: "statement_date", Label: "Date", Path: "values.statement_date"},
					{Key: "closing_balance", Label: "Closing", Path: "values.closing_balance"},
					{Key: "status", Label: "Status", Path: "values.status"},
				}, []string{"draft", "imported", "reconciling", "reconciled"}),
				commercialModelListView("finance.bank_import_templates.list", "Bank Import Templates", "bank_import_template", []module.ColumnDefinition{
					{Key: "template_code", Label: "Code", Path: "values.template_code"},
					{Key: "name", Label: "Name", Path: "values.name"},
					{Key: "bank_name", Label: "Bank", Path: "values.bank_name"},
					{Key: "format_key", Label: "Format", Path: "values.format_key"},
					{Key: "status", Label: "Status", Path: "values.status"},
				}, []string{"active", "inactive"}),
				commercialModelListView("finance.bank_import_runs.list", "Statement Import Runs", "bank_statement_import_run", []module.ColumnDefinition{
					{Key: "source_file_name", Label: "Source", Path: "values.source_file_name"},
					{Key: "row_count", Label: "Rows", Path: "values.row_count"},
					{Key: "duplicate_count", Label: "Duplicates", Path: "values.duplicate_count"},
					{Key: "warning_count", Label: "Warnings", Path: "values.warning_count"},
					{Key: "status", Label: "Status", Path: "values.status"},
				}, []string{"draft", "parsed", "imported", "failed"}),
				commercialModelListView("finance.treasury_transfers.list", "Treasury Transfers", "treasury_transfer", []module.ColumnDefinition{
					{Key: "transfer_date", Label: "Date", Path: "values.transfer_date"},
					{Key: "from_account_code", Label: "From", Path: "values.from_account_code"},
					{Key: "to_account_code", Label: "To", Path: "values.to_account_code"},
					{Key: "amount", Label: "Amount", Path: "values.amount"},
					{Key: "status", Label: "Status", Path: "values.status"},
				}, []string{"draft", "posted", "cancelled"}),
			},
			CustomEntries: []module.CustomEntryDefinition{
				{Key: "finance.cash_position", Title: "Cash Position", TitleI18n: localize("Cash Position", "Posisi Kas"), RoutePath: "/finance/cash-position", BundleKey: "finance-reports", ComponentExport: "render", RequiredPermissions: []string{"finance.read"}},
				{Key: "finance.clearing_balance", Title: "Clearing Balance", TitleI18n: localize("Clearing Balance", "Saldo Clearing"), RoutePath: "/finance/clearing-balance", BundleKey: "finance-reports", ComponentExport: "render", RequiredPermissions: []string{"finance.read"}},
				{Key: "finance.bank_reconciliation", Title: "Bank Reconciliation", TitleI18n: localize("Bank Reconciliation", "Rekonsiliasi Bank"), RoutePath: "/finance/bank-reconciliation", BundleKey: "finance-reports", ComponentExport: "render", RequiredPermissions: []string{"finance.read", "bank_statement.read"}},
				{Key: "finance.treasury_exceptions", Title: "Treasury Exceptions", TitleI18n: localize("Treasury Exceptions", "Exception Treasury"), RoutePath: "/finance/treasury-exceptions", BundleKey: "finance-reports", ComponentExport: "render", RequiredPermissions: []string{"treasury_exception.list"}},
			},
		},
	}
}

func treasuryModelDefinition(key, singular string, fields []model.FieldDefinition) model.Definition {
	return model.Definition{
		Key:                 key,
		DisplayName:         singular,
		DisplayNameI18n:     localize(singular, singular),
		OwnerModuleKey:      "treasury_core",
		Version:             "v1",
		CreatePermissionKey: key + ".create",
		ListPermissionKey:   key + ".list",
		ReadPermissionKey:   key + ".read",
		UpdatePermissionKey: key + ".update",
		DefaultSort:         "updated_at",
		Fields:              fields,
	}
}
