package app

import (
	"orbyte/internal/platform/model"
	"orbyte/internal/platform/module"
	"orbyte/internal/platform/search"
)

func masterdataKernelPackManifest() module.Manifest {
	return module.Manifest{
		Key:                  "masterdata",
		Name:                 "Master Data",
		NameI18n:             localize("Master Data", "Data Master"),
		Version:              "1.0.0",
		DomainFamily:         "platform",
		Description:          "Shared party, customer, contact, and address masters used across business domains.",
		DescriptionI18n:      localize("Shared party, customer, contact, and address masters used across business domains.", "Data master pihak, pelanggan, kontak, dan alamat yang digunakan lintas domain bisnis."),
		BusinessCapabilities: []string{"party master", "customer master", "contact master", "address book", "shared counterparty identity"},
		DependencyRequirements: []module.DependencyRequirement{
			{ModuleKey: "platform.core", VersionRange: ">=1.0.0,<2.0.0", Kind: module.DependencyKindRequired},
			{ModuleKey: "reference_masterdata", VersionRange: ">=1.0.0,<2.0.0", Kind: module.DependencyKindRequired},
		},
		AdminConsole: module.AdminConsoleDefinition{
			Title:           "Master Data Console",
			TitleI18n:       localize("Master Data Console", "Konsol Data Master"),
			Description:     "Shared party, customer, contact, and address operations with links into commercial and procurement flows.",
			DescriptionI18n: localize("Shared party, customer, contact, and address operations with links into commercial and procurement flows.", "Operasi pihak, pelanggan, kontak, dan alamat bersama dengan pintu masuk ke alur komersial dan pengadaan."),
			Sections: []module.AdminConsoleSectionDefinition{
				{
					Key:       "masterdata_operations",
					Title:     "Master Data Operations",
					TitleI18n: localize("Master Data Operations", "Operasi Data Master"),
					Kind:      module.AdminConsoleSectionResourceLinks,
					Links: []module.AdminConsoleLinkDefinition{
						adminConsoleLink("parties", "Parties", "Pihak", "/ui/masterdata/parties", "Open shared root party records.", "Buka data pihak induk bersama.", "party.list"),
						adminConsoleLink("customers", "Customers", "Pelanggan", "/ui/masterdata/customers", "Open customer profiles built on top of parties.", "Buka profil pelanggan di atas pihak.", "customer.list"),
						adminConsoleLink("contacts", "Contacts", "Kontak", "/ui/masterdata/contacts", "Open shared contact records.", "Buka data kontak bersama.", "party.read"),
						adminConsoleLink("addresses", "Addresses", "Alamat", "/ui/masterdata/addresses", "Open shared address records.", "Buka data alamat bersama.", "party.read"),
						adminConsoleLink("vendors", "Vendors", "Vendor", "/ui/procurement/vendors", "Open vendor profiles linked to parties.", "Buka profil vendor yang terhubung ke pihak.", "vendor.list"),
					},
				},
			},
		},
		Models: []model.Definition{
			{
				Key:                 "party",
				DisplayName:         "Party",
				DisplayNameI18n:     localize("Party", "Pihak"),
				OwnerModuleKey:      "masterdata",
				Version:             "v1",
				CreatePermissionKey: "party.create",
				ListPermissionKey:   "party.list",
				ReadPermissionKey:   "party.read",
				UpdatePermissionKey: "party.update",
				DefaultSort:         "name",
				Fields: []model.FieldDefinition{
					{Key: "name", Label: "Name", LabelI18n: localize("Name", "Nama"), Type: "string", Required: true},
					{Key: "display_name", Label: "Display Name", LabelI18n: localize("Display Name", "Nama Tampil"), Type: "string", ReadOnly: true, ComputeRuleKey: "party.display_name.compute"},
					{Key: "legal_name", Label: "Legal Name", LabelI18n: localize("Legal Name", "Nama Legal"), Type: "string"},
					{Key: "party_kind", Label: "Party Kind", LabelI18n: localize("Party Kind", "Jenis Pihak"), Type: "string", DefaultValue: "organization"},
					{Key: "email", Label: "Email", LabelI18n: localize("Email", "Email"), Type: "string"},
					{Key: "phone", Label: "Phone", LabelI18n: localize("Phone", "Telepon"), Type: "string"},
					{Key: "tax_identifier", Label: "Tax Identifier", LabelI18n: localize("Tax Identifier", "Nomor Pajak"), Type: "string"},
					{Key: "currency_code", Label: "Currency", LabelI18n: localize("Currency", "Mata Uang"), Type: "string"},
					{Key: "customer_type", Label: "Customer Type", LabelI18n: localize("Customer Type", "Tipe Pelanggan"), Type: "string"},
					{Key: "member_status", Label: "Member Status", LabelI18n: localize("Member Status", "Status Member"), Type: "string"},
					{Key: "member_tier", Label: "Member Tier", LabelI18n: localize("Member Tier", "Tier Member"), Type: "string"},
					{Key: "member_valid_from", Label: "Member Valid From", LabelI18n: localize("Member Valid From", "Member Berlaku Dari"), Type: "string"},
					{Key: "member_valid_to", Label: "Member Valid To", LabelI18n: localize("Member Valid To", "Member Berlaku Sampai"), Type: "string"},
					{Key: "tax_profile_code", Label: "Tax Profile", LabelI18n: localize("Tax Profile", "Profil Pajak"), Type: "string"},
					{Key: "default_price_list_code", Label: "Default Price List", LabelI18n: localize("Default Price List", "Daftar Harga Default"), Type: "string"},
					{Key: "payment_term_days", Label: "Payment Term Days", LabelI18n: localize("Payment Term Days", "Hari Termin Pembayaran"), Type: "number"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Type: "string", DefaultRuleKey: "party.status.default", ConstraintRuleKeys: []string{"party.status.allowed"}},
				},
				Relations: []model.RelationDefinition{
					{Key: "contacts", Type: "has_many", TargetModelKey: "party_contact", ForeignKey: "party_id"},
					{Key: "addresses", Type: "has_many", TargetModelKey: "party_address", ForeignKey: "party_id"},
					{Key: "customer_profiles", Type: "has_many", TargetModelKey: "customer_profile", ForeignKey: "party_id"},
					{Key: "vendor_profiles", Type: "has_many", TargetModelKey: "vendor_profile", ForeignKey: "party_id"},
				},
			},
			{
				Key:                 "customer_profile",
				DisplayName:         "Customer Profile",
				DisplayNameI18n:     localize("Customer Profile", "Profil Pelanggan"),
				OwnerModuleKey:      "masterdata",
				Version:             "v1",
				CreatePermissionKey: "customer.create",
				ListPermissionKey:   "customer.list",
				ReadPermissionKey:   "customer.read",
				UpdatePermissionKey: "customer.update",
				DefaultSort:         "customer_name",
				Fields: []model.FieldDefinition{
					{Key: "party_id", Label: "Party", LabelI18n: localize("Party", "Pihak"), Type: "string", Required: true},
					{Key: "customer_name", Label: "Customer Name", LabelI18n: localize("Customer Name", "Nama Pelanggan"), Type: "string"},
					{Key: "customer_type", Label: "Customer Type", LabelI18n: localize("Customer Type", "Tipe Pelanggan"), Type: "string"},
					{Key: "customer_segment", Label: "Customer Segment", LabelI18n: localize("Customer Segment", "Segmen Pelanggan"), Type: "string"},
					{Key: "member_status", Label: "Member Status", LabelI18n: localize("Member Status", "Status Member"), Type: "string"},
					{Key: "member_tier", Label: "Member Tier", LabelI18n: localize("Member Tier", "Tier Member"), Type: "string"},
					{Key: "member_valid_from", Label: "Member Valid From", LabelI18n: localize("Member Valid From", "Member Berlaku Dari"), Type: "string"},
					{Key: "member_valid_to", Label: "Member Valid To", LabelI18n: localize("Member Valid To", "Member Berlaku Sampai"), Type: "string"},
					{Key: "tax_profile_code", Label: "Tax Profile", LabelI18n: localize("Tax Profile", "Profil Pajak"), Type: "string"},
					{Key: "default_price_list_code", Label: "Default Price List", LabelI18n: localize("Default Price List", "Daftar Harga Default"), Type: "string"},
					{Key: "payment_term_days", Label: "Payment Term Days", LabelI18n: localize("Payment Term Days", "Hari Termin Pembayaran"), Type: "number"},
					{Key: "credit_limit_amount", Label: "Credit Limit", LabelI18n: localize("Credit Limit", "Batas Kredit"), Type: "number"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Type: "string", DefaultValue: "active"},
				},
			},
			{
				Key:                 "party_contact",
				DisplayName:         "Party Contact",
				DisplayNameI18n:     localize("Party Contact", "Kontak Pihak"),
				OwnerModuleKey:      "masterdata",
				Version:             "v1",
				CreatePermissionKey: "party.update",
				ListPermissionKey:   "party.read",
				ReadPermissionKey:   "party.read",
				UpdatePermissionKey: "party.update",
				DefaultSort:         "name",
				Fields: []model.FieldDefinition{
					{Key: "party_id", Label: "Party ID", LabelI18n: localize("Party ID", "ID Pihak"), Type: "string", Required: true},
					{Key: "contact_kind", Label: "Contact Kind", LabelI18n: localize("Contact Kind", "Jenis Kontak"), Type: "string", DefaultValue: "person"},
					{Key: "name", Label: "Name", LabelI18n: localize("Name", "Nama"), Type: "string", Required: true},
					{Key: "title", Label: "Title", LabelI18n: localize("Title", "Jabatan"), Type: "string"},
					{Key: "email", Label: "Email", LabelI18n: localize("Email", "Email"), Type: "string"},
					{Key: "phone", Label: "Phone", LabelI18n: localize("Phone", "Telepon"), Type: "string"},
					{Key: "mobile_phone", Label: "Mobile Phone", LabelI18n: localize("Mobile Phone", "Telepon Seluler"), Type: "string"},
					{Key: "role", Label: "Role", LabelI18n: localize("Role", "Peran"), Type: "string"},
					{Key: "is_primary", Label: "Primary", LabelI18n: localize("Primary", "Utama"), Type: "bool"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Type: "string", DefaultValue: "active"},
				},
			},
			{
				Key:                 "party_address",
				DisplayName:         "Party Address",
				DisplayNameI18n:     localize("Party Address", "Alamat Pihak"),
				OwnerModuleKey:      "masterdata",
				Version:             "v1",
				CreatePermissionKey: "party.update",
				ListPermissionKey:   "party.read",
				ReadPermissionKey:   "party.read",
				UpdatePermissionKey: "party.update",
				DefaultSort:         "address_type",
				Fields: []model.FieldDefinition{
					{Key: "party_id", Label: "Party ID", LabelI18n: localize("Party ID", "ID Pihak"), Type: "string", Required: true},
					{Key: "address_type", Label: "Address Type", LabelI18n: localize("Address Type", "Tipe Alamat"), Type: "string", Required: true},
					{Key: "line1", Label: "Address Line 1", LabelI18n: localize("Address Line 1", "Alamat Baris 1"), Type: "string", Required: true},
					{Key: "line2", Label: "Address Line 2", LabelI18n: localize("Address Line 2", "Alamat Baris 2"), Type: "string"},
					{Key: "city", Label: "City", LabelI18n: localize("City", "Kota"), Type: "string"},
					{Key: "region", Label: "Region", LabelI18n: localize("Region", "Wilayah"), Type: "string"},
					{Key: "postal_code", Label: "Postal Code", LabelI18n: localize("Postal Code", "Kode Pos"), Type: "string"},
					{Key: "country_code", Label: "Country", LabelI18n: localize("Country", "Negara"), Type: "string"},
					{Key: "is_primary", Label: "Primary", LabelI18n: localize("Primary", "Utama"), Type: "bool"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Type: "string", DefaultValue: "active"},
				},
			},
		},
		Datasets: []module.DatasetDefinition{
			{
				Key:        "masterdata.party.summary",
				Title:      "Party Summary",
				TitleI18n:  localize("Party Summary", "Ringkasan Pihak"),
				SourceKind: "model",
				ModelKey:   "party",
				Dimensions: []module.DatasetDimension{{Key: "by_status", Label: "By Status", LabelI18n: localize("By Status", "Berdasarkan Status"), Path: "status"}},
				Measures:   []module.DatasetMeasure{{Key: "total", Label: "Total", LabelI18n: localize("Total", "Total"), Kind: "count"}},
			},
			{
				Key:        "masterdata.customer.summary",
				Title:      "Customer Summary",
				TitleI18n:  localize("Customer Summary", "Ringkasan Pelanggan"),
				SourceKind: "model",
				ModelKey:   "customer_profile",
				Dimensions: []module.DatasetDimension{{Key: "by_status", Label: "By Status", LabelI18n: localize("By Status", "Berdasarkan Status"), Path: "status"}},
				Measures:   []module.DatasetMeasure{{Key: "total", Label: "Total", LabelI18n: localize("Total", "Total"), Kind: "count"}},
			},
		},
		SearchIndexes: []search.IndexDefinition{
			{
				Key:                 "masterdata.party.search",
				Title:               "Party Search",
				SourceKind:          "model",
				ModelKey:            "party",
				ViewKey:             "masterdata.parties.list",
				Modes:               []string{"keyword", "vector", "hybrid"},
				OrganizationSplit:   true,
				RequiredPermissions: []string{"party.list"},
				QueryFilterFields:   []string{"status", "location_id"},
				QuerySortFields:     []string{"name", "updated_at"},
				Fields: []search.IndexFieldDefinition{
					{Key: "name", Path: "name", Type: "string", Searchable: true, Sort: true},
					{Key: "legal_name", Path: "legal_name", Type: "string", Searchable: true},
					{Key: "email", Path: "email", Type: "string", Searchable: true},
					{Key: "location_id", Path: "location_id", Type: "string", Facet: true},
					{Key: "status", Path: "status", Type: "string", Facet: true, Sort: true},
				},
				VectorFields: []search.VectorFieldDefinition{{
					Key: "semantic", SourcePaths: []string{"name", "legal_name", "email"}, EmbeddingMode: "external", Dimensions: 8, DistanceMetric: "cosine",
				}},
			},
			{
				Key:                 "masterdata.customer.search",
				Title:               "Customer Search",
				SourceKind:          "model",
				ModelKey:            "customer_profile",
				ViewKey:             "masterdata.customers.list",
				Modes:               []string{"keyword", "vector", "hybrid"},
				OrganizationSplit:   true,
				RequiredPermissions: []string{"customer.list"},
				QueryFilterFields:   []string{"status", "customer_type", "customer_segment"},
				QuerySortFields:     []string{"customer_name", "updated_at"},
				Fields: []search.IndexFieldDefinition{
					{Key: "customer_name", Path: "customer_name", Type: "string", Searchable: true, Sort: true},
					{Key: "party_id", Path: "party_id", Type: "string", Searchable: true},
					{Key: "customer_type", Path: "customer_type", Type: "string", Facet: true},
					{Key: "customer_segment", Path: "customer_segment", Type: "string", Facet: true},
					{Key: "status", Path: "status", Type: "string", Facet: true, Sort: true},
				},
				VectorFields: []search.VectorFieldDefinition{{
					Key: "semantic", SourcePaths: []string{"customer_name", "customer_type", "customer_segment"}, EmbeddingMode: "external", Dimensions: 8, DistanceMetric: "cosine",
				}},
			},
			{
				Key:                 "masterdata.contact.search",
				Title:               "Contact Search",
				SourceKind:          "model",
				ModelKey:            "party_contact",
				ViewKey:             "masterdata.contacts.list",
				Modes:               []string{"keyword", "hybrid"},
				OrganizationSplit:   true,
				RequiredPermissions: []string{"party.read"},
				QueryFilterFields:   []string{"party_id", "status", "contact_kind", "is_primary"},
				QuerySortFields:     []string{"name", "updated_at"},
				Fields: []search.IndexFieldDefinition{
					{Key: "party_id", Path: "party_id", Type: "string", Facet: true},
					{Key: "name", Path: "name", Type: "string", Searchable: true, Sort: true},
					{Key: "email", Path: "email", Type: "string", Searchable: true},
					{Key: "phone", Path: "phone", Type: "string", Searchable: true},
					{Key: "contact_kind", Path: "contact_kind", Type: "string", Facet: true},
					{Key: "is_primary", Path: "is_primary", Type: "bool", Facet: true},
					{Key: "role", Path: "role", Type: "string", Searchable: true},
					{Key: "status", Path: "status", Type: "string", Facet: true, Sort: true},
				},
			},
		},
		Security: module.SecurityDefinition{
			Permissions: []module.PermissionDefinition{
				{Key: "party.create", Action: "create", Resource: "party", DisplayName: "Create Parties", DisplayNameI18n: localize("Create Parties", "Buat Pihak")},
				{Key: "party.list", Action: "list", Resource: "party", DisplayName: "List Parties", DisplayNameI18n: localize("List Parties", "Daftar Pihak")},
				{Key: "party.read", Action: "read", Resource: "party", DisplayName: "Read Parties", DisplayNameI18n: localize("Read Parties", "Lihat Pihak")},
				{Key: "party.update", Action: "update", Resource: "party", DisplayName: "Update Parties", DisplayNameI18n: localize("Update Parties", "Perbarui Pihak")},
				{Key: "customer.create", Action: "create", Resource: "customer", DisplayName: "Create Customers", DisplayNameI18n: localize("Create Customers", "Buat Pelanggan")},
				{Key: "customer.list", Action: "list", Resource: "customer", DisplayName: "List Customers", DisplayNameI18n: localize("List Customers", "Daftar Pelanggan")},
				{Key: "customer.read", Action: "read", Resource: "customer", DisplayName: "Read Customers", DisplayNameI18n: localize("Read Customers", "Lihat Pelanggan")},
				{Key: "customer.update", Action: "update", Resource: "customer", DisplayName: "Update Customers", DisplayNameI18n: localize("Update Customers", "Perbarui Pelanggan")},
			},
			RoleTemplates: []module.RoleTemplateDefinition{{
				Key: "party_manager", Name: "Party Manager", NameI18n: localize("Party Manager", "Pengelola Pihak"), AllowedScopes: []string{"deployment", "location"}, PermissionKeys: []string{"party.create", "party.list", "party.read", "party.update", "customer.create", "customer.list", "customer.read", "customer.update"},
			}},
		},
		Frontend: module.FrontendDefinition{
			Menus: []module.MenuDefinition{
				{Key: "masterdata.parties", Label: "Parties", LabelI18n: localize("Parties", "Pihak"), ActionKey: "masterdata.parties.list", Order: 5, RequiredPermissions: []string{"party.list"}},
				{Key: "masterdata.customers", Label: "Customers", LabelI18n: localize("Customers", "Pelanggan"), ActionKey: "masterdata.customers.list", Order: 6, RequiredPermissions: []string{"customer.list"}},
				{Key: "masterdata.contacts", Label: "Contacts", LabelI18n: localize("Contacts", "Kontak"), ActionKey: "masterdata.contacts.list", Order: 7, RequiredPermissions: []string{"party.read"}},
				{Key: "masterdata.addresses", Label: "Addresses", LabelI18n: localize("Addresses", "Alamat"), ActionKey: "masterdata.addresses.list", Order: 8, RequiredPermissions: []string{"party.read"}},
			},
			Actions: append(masterdataModelActions("parties", "Parties", "Party Detail", "Party Form", "party", "party.list", "party.read", "party.update"),
				append(masterdataModelActions("customers", "Customers", "Customer Detail", "Customer Form", "customer_profile", "customer.list", "customer.read", "customer.update"),
					append(masterdataModelActions("contacts", "Contacts", "Contact Detail", "Contact Form", "party_contact", "party.read", "party.read", "party.update"),
						masterdataModelActions("addresses", "Addresses", "Address Detail", "Address Form", "party_address", "party.read", "party.read", "party.update")...)...)...),
			Views: []module.ViewDefinition{
				masterdataPartyListView(),
				masterdataPartyDetailView(),
				masterdataPartyFormView(),
				commercialModelListView("masterdata.customers.list", "Customers", "customer_profile", []module.ColumnDefinition{
					{Key: "customer_name", Label: "Customer", LabelI18n: localize("Customer", "Pelanggan"), Path: "values.customer_name"},
					{Key: "party_id", Label: "Party", LabelI18n: localize("Party", "Pihak"), Path: "values.party_id"},
					{Key: "customer_type", Label: "Customer Type", LabelI18n: localize("Customer Type", "Tipe Pelanggan"), Path: "values.customer_type"},
					{Key: "customer_segment", Label: "Segment", LabelI18n: localize("Segment", "Segmen"), Path: "values.customer_segment"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status"},
				}, []string{"active", "inactive"}),
				commercialModelDetailView("masterdata.customers.detail", "Customer Detail", "customer_profile", []module.FieldDefinition{
					{Key: "customer_name", Label: "Customer Name", LabelI18n: localize("Customer Name", "Nama Pelanggan"), Path: "values.customer_name", Type: "string"},
					{Key: "party_id", Label: "Party", LabelI18n: localize("Party", "Pihak"), Path: "values.party_id", Type: "string"},
					{Key: "customer_type", Label: "Customer Type", LabelI18n: localize("Customer Type", "Tipe Pelanggan"), Path: "values.customer_type", Type: "string"},
					{Key: "customer_segment", Label: "Customer Segment", LabelI18n: localize("Customer Segment", "Segmen Pelanggan"), Path: "values.customer_segment", Type: "string"},
					{Key: "member_status", Label: "Member Status", LabelI18n: localize("Member Status", "Status Member"), Path: "values.member_status", Type: "string"},
					{Key: "member_tier", Label: "Member Tier", LabelI18n: localize("Member Tier", "Tier Member"), Path: "values.member_tier", Type: "string"},
					{Key: "member_valid_from", Label: "Member Valid From", LabelI18n: localize("Member Valid From", "Member Berlaku Dari"), Path: "values.member_valid_from", Type: "string"},
					{Key: "member_valid_to", Label: "Member Valid To", LabelI18n: localize("Member Valid To", "Member Berlaku Sampai"), Path: "values.member_valid_to", Type: "string"},
					{Key: "tax_profile_code", Label: "Tax Profile", LabelI18n: localize("Tax Profile", "Profil Pajak"), Path: "values.tax_profile_code", Type: "string"},
					{Key: "default_price_list_code", Label: "Default Price List", LabelI18n: localize("Default Price List", "Daftar Harga Default"), Path: "values.default_price_list_code", Type: "string"},
					{Key: "payment_term_days", Label: "Payment Term Days", LabelI18n: localize("Payment Term Days", "Hari Termin Pembayaran"), Path: "values.payment_term_days", Type: "number"},
					{Key: "credit_limit_amount", Label: "Credit Limit", LabelI18n: localize("Credit Limit", "Batas Kredit"), Path: "values.credit_limit_amount", Type: "number"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status", Type: "string"},
				}),
				commercialModelFormView("masterdata.customers.form", "Customer Form", "customer_profile", []module.FieldDefinition{
					{Key: "party_id", Label: "Party", LabelI18n: localize("Party", "Pihak"), Path: "values.party_id", Type: "string", Widget: "select", Required: true},
					{Key: "customer_name", Label: "Customer Name", LabelI18n: localize("Customer Name", "Nama Pelanggan"), Path: "values.customer_name", Type: "string", Widget: "text"},
					{Key: "customer_type", Label: "Customer Type", LabelI18n: localize("Customer Type", "Tipe Pelanggan"), Path: "values.customer_type", Type: "string", Widget: "select", Options: []string{"retail", "member", "vip", "corporate"}},
					{Key: "customer_segment", Label: "Customer Segment", LabelI18n: localize("Customer Segment", "Segmen Pelanggan"), Path: "values.customer_segment", Type: "string", Widget: "text"},
					{Key: "member_status", Label: "Member Status", LabelI18n: localize("Member Status", "Status Member"), Path: "values.member_status", Type: "string", Widget: "select", Options: []string{"inactive", "active", "expired"}},
					{Key: "member_tier", Label: "Member Tier", LabelI18n: localize("Member Tier", "Tier Member"), Path: "values.member_tier", Type: "string", Widget: "text"},
					{Key: "member_valid_from", Label: "Member Valid From", LabelI18n: localize("Member Valid From", "Member Berlaku Dari"), Path: "values.member_valid_from", Type: "string", Widget: "text"},
					{Key: "member_valid_to", Label: "Member Valid To", LabelI18n: localize("Member Valid To", "Member Berlaku Sampai"), Path: "values.member_valid_to", Type: "string", Widget: "text"},
					{Key: "tax_profile_code", Label: "Tax Profile", LabelI18n: localize("Tax Profile", "Profil Pajak"), Path: "values.tax_profile_code", Type: "string", Widget: "select"},
					{Key: "default_price_list_code", Label: "Default Price List", LabelI18n: localize("Default Price List", "Daftar Harga Default"), Path: "values.default_price_list_code", Type: "string", Widget: "select"},
					{Key: "payment_term_days", Label: "Payment Term Days", LabelI18n: localize("Payment Term Days", "Hari Termin Pembayaran"), Path: "values.payment_term_days", Type: "number"},
					{Key: "credit_limit_amount", Label: "Credit Limit", LabelI18n: localize("Credit Limit", "Batas Kredit"), Path: "values.credit_limit_amount", Type: "number"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status", Type: "string", Widget: "select", Options: []string{"active", "inactive"}},
				}),
				commercialModelListView("masterdata.contacts.list", "Contacts", "party_contact", []module.ColumnDefinition{
					{Key: "name", Label: "Name", LabelI18n: localize("Name", "Nama"), Path: "values.name"},
					{Key: "party_id", Label: "Party", LabelI18n: localize("Party", "Pihak"), Path: "values.party_id"},
					{Key: "role", Label: "Role", LabelI18n: localize("Role", "Peran"), Path: "values.role"},
					{Key: "email", Label: "Email", LabelI18n: localize("Email", "Email"), Path: "values.email"},
					{Key: "phone", Label: "Phone", LabelI18n: localize("Phone", "Telepon"), Path: "values.phone"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status"},
				}, []string{"active", "inactive"}),
				commercialModelDetailView("masterdata.contacts.detail", "Contact Detail", "party_contact", []module.FieldDefinition{
					{Key: "party_id", Label: "Party", LabelI18n: localize("Party", "Pihak"), Path: "values.party_id", Type: "string"},
					{Key: "contact_kind", Label: "Contact Kind", LabelI18n: localize("Contact Kind", "Jenis Kontak"), Path: "values.contact_kind", Type: "string"},
					{Key: "name", Label: "Name", LabelI18n: localize("Name", "Nama"), Path: "values.name", Type: "string"},
					{Key: "title", Label: "Title", LabelI18n: localize("Title", "Jabatan"), Path: "values.title", Type: "string"},
					{Key: "role", Label: "Role", LabelI18n: localize("Role", "Peran"), Path: "values.role", Type: "string"},
					{Key: "email", Label: "Email", LabelI18n: localize("Email", "Email"), Path: "values.email", Type: "string"},
					{Key: "phone", Label: "Phone", LabelI18n: localize("Phone", "Telepon"), Path: "values.phone", Type: "string"},
					{Key: "mobile_phone", Label: "Mobile Phone", LabelI18n: localize("Mobile Phone", "Telepon Seluler"), Path: "values.mobile_phone", Type: "string"},
					{Key: "is_primary", Label: "Primary", LabelI18n: localize("Primary", "Utama"), Path: "values.is_primary", Type: "bool"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status", Type: "string"},
				}),
				commercialModelFormView("masterdata.contacts.form", "Contact Form", "party_contact", []module.FieldDefinition{
					{Key: "party_id", Label: "Party", LabelI18n: localize("Party", "Pihak"), Path: "values.party_id", Type: "string", Widget: "select", Required: true},
					{Key: "contact_kind", Label: "Contact Kind", LabelI18n: localize("Contact Kind", "Jenis Kontak"), Path: "values.contact_kind", Type: "string", Widget: "select", Options: []string{"person", "organization"}, Required: true},
					{Key: "name", Label: "Name", LabelI18n: localize("Name", "Nama"), Path: "values.name", Type: "string", Widget: "text", Required: true},
					{Key: "title", Label: "Title", LabelI18n: localize("Title", "Jabatan"), Path: "values.title", Type: "string", Widget: "text"},
					{Key: "role", Label: "Role", LabelI18n: localize("Role", "Peran"), Path: "values.role", Type: "string", Widget: "text"},
					{Key: "email", Label: "Email", LabelI18n: localize("Email", "Email"), Path: "values.email", Type: "string", Widget: "text"},
					{Key: "phone", Label: "Phone", LabelI18n: localize("Phone", "Telepon"), Path: "values.phone", Type: "string", Widget: "text"},
					{Key: "mobile_phone", Label: "Mobile Phone", LabelI18n: localize("Mobile Phone", "Telepon Seluler"), Path: "values.mobile_phone", Type: "string", Widget: "text"},
					{Key: "is_primary", Label: "Primary", LabelI18n: localize("Primary", "Utama"), Path: "values.is_primary", Type: "bool"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status", Type: "string", Widget: "select", Options: []string{"active", "inactive"}},
				}),
				commercialModelListView("masterdata.addresses.list", "Addresses", "party_address", []module.ColumnDefinition{
					{Key: "party_id", Label: "Party", LabelI18n: localize("Party", "Pihak"), Path: "values.party_id"},
					{Key: "address_type", Label: "Address Type", LabelI18n: localize("Address Type", "Tipe Alamat"), Path: "values.address_type"},
					{Key: "line1", Label: "Address", LabelI18n: localize("Address", "Alamat"), Path: "values.line1"},
					{Key: "city", Label: "City", LabelI18n: localize("City", "Kota"), Path: "values.city"},
					{Key: "country_code", Label: "Country", LabelI18n: localize("Country", "Negara"), Path: "values.country_code"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status"},
				}, []string{"active", "inactive"}),
				commercialModelDetailView("masterdata.addresses.detail", "Address Detail", "party_address", []module.FieldDefinition{
					{Key: "party_id", Label: "Party", LabelI18n: localize("Party", "Pihak"), Path: "values.party_id", Type: "string"},
					{Key: "address_type", Label: "Address Type", LabelI18n: localize("Address Type", "Tipe Alamat"), Path: "values.address_type", Type: "string"},
					{Key: "line1", Label: "Address Line 1", LabelI18n: localize("Address Line 1", "Alamat Baris 1"), Path: "values.line1", Type: "string"},
					{Key: "line2", Label: "Address Line 2", LabelI18n: localize("Address Line 2", "Alamat Baris 2"), Path: "values.line2", Type: "string"},
					{Key: "city", Label: "City", LabelI18n: localize("City", "Kota"), Path: "values.city", Type: "string"},
					{Key: "region", Label: "Region", LabelI18n: localize("Region", "Wilayah"), Path: "values.region", Type: "string"},
					{Key: "postal_code", Label: "Postal Code", LabelI18n: localize("Postal Code", "Kode Pos"), Path: "values.postal_code", Type: "string"},
					{Key: "country_code", Label: "Country", LabelI18n: localize("Country", "Negara"), Path: "values.country_code", Type: "string"},
					{Key: "is_primary", Label: "Primary", LabelI18n: localize("Primary", "Utama"), Path: "values.is_primary", Type: "bool"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status", Type: "string"},
				}),
				commercialModelFormView("masterdata.addresses.form", "Address Form", "party_address", []module.FieldDefinition{
					{Key: "party_id", Label: "Party", LabelI18n: localize("Party", "Pihak"), Path: "values.party_id", Type: "string", Widget: "select", Required: true},
					{Key: "address_type", Label: "Address Type", LabelI18n: localize("Address Type", "Tipe Alamat"), Path: "values.address_type", Type: "string", Widget: "select", Options: []string{"billing", "shipping", "remit_to", "business"}, Required: true},
					{Key: "line1", Label: "Address Line 1", LabelI18n: localize("Address Line 1", "Alamat Baris 1"), Path: "values.line1", Type: "string", Widget: "text", Required: true},
					{Key: "line2", Label: "Address Line 2", LabelI18n: localize("Address Line 2", "Alamat Baris 2"), Path: "values.line2", Type: "string", Widget: "text"},
					{Key: "city", Label: "City", LabelI18n: localize("City", "Kota"), Path: "values.city", Type: "string", Widget: "text"},
					{Key: "region", Label: "Region", LabelI18n: localize("Region", "Wilayah"), Path: "values.region", Type: "string", Widget: "text"},
					{Key: "postal_code", Label: "Postal Code", LabelI18n: localize("Postal Code", "Kode Pos"), Path: "values.postal_code", Type: "string", Widget: "text"},
					{Key: "country_code", Label: "Country", LabelI18n: localize("Country", "Negara"), Path: "values.country_code", Type: "string", Widget: "text"},
					{Key: "is_primary", Label: "Primary", LabelI18n: localize("Primary", "Utama"), Path: "values.is_primary", Type: "bool"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status", Type: "string", Widget: "select", Options: []string{"active", "inactive"}},
				}),
			},
		},
		Offline: module.OfflineDefinition{
			Projections: []module.OfflineProjectionDefinition{
				{IndexKey: "masterdata.party.search", Title: "Party Search", TitleI18n: localize("Party Search", "Pencarian Pihak"), RequiredPermissions: []string{"party.list"}, DefaultIncludeFields: []string{"name", "email", "status"}},
				{IndexKey: "masterdata.customer.search", Title: "Customer Search", TitleI18n: localize("Customer Search", "Pencarian Pelanggan"), RequiredPermissions: []string{"customer.list"}, DefaultIncludeFields: []string{"customer_name", "customer_type", "status"}},
			},
			Models: []module.OfflineModelDefinition{
				{ModelKey: "party", Title: "Party", TitleI18n: localize("Party", "Pihak"), CreatePermissionKey: "party.create", UpdatePermissionKey: "party.update", RequiredPermissions: []string{"party.read"}},
				{ModelKey: "customer_profile", Title: "Customer", TitleI18n: localize("Customer", "Pelanggan"), CreatePermissionKey: "customer.create", UpdatePermissionKey: "customer.update", RequiredPermissions: []string{"customer.read"}},
			},
		},
	}
}

func masterdataModelActions(prefix, listLabel, detailLabel, formLabel, modelKey, listPerm, readPerm, updatePerm string) []module.ActionDefinition {
	_ = modelKey
	base := "/masterdata/" + prefix
	return []module.ActionDefinition{
		{Key: "masterdata." + prefix + ".list", Label: listLabel, LabelI18n: localize(listLabel, listLabel), Kind: "navigate", RoutePath: base, ViewKey: "masterdata." + prefix + ".list", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{listPerm}},
		{Key: "masterdata." + prefix + ".detail", Label: detailLabel, LabelI18n: localize(detailLabel, detailLabel), Kind: "navigate", RoutePath: base + "/detail", ViewKey: "masterdata." + prefix + ".detail", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{readPerm}},
		{Key: "masterdata." + prefix + ".form", Label: formLabel, LabelI18n: localize(formLabel, formLabel), Kind: "navigate", RoutePath: base + "/form", ViewKey: "masterdata." + prefix + ".form", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{updatePerm}},
		{Key: "masterdata." + prefix + ".new", Label: "New " + listLabel, LabelI18n: localize("New "+listLabel, "Baru"), Kind: "navigate", RoutePath: base + "/new", ViewKey: "masterdata." + prefix + ".form", RenderMode: module.RenderModeGeneric, RequiredPermissions: []string{updatePerm}},
	}
}

func masterdataPartyListView() module.ViewDefinition {
	return module.ViewDefinition{
		Key:                 "masterdata.parties.list",
		Title:               "Parties",
		TitleI18n:           localize("Parties", "Pihak"),
		Kind:                "list",
		ModelKey:            "party",
		RequiredPermissions: []string{"party.list"},
		Columns: []module.ColumnDefinition{
			{Key: "name", Label: "Name", LabelI18n: localize("Name", "Nama"), Path: "values.name"},
			{Key: "legal_name", Label: "Legal Name", LabelI18n: localize("Legal Name", "Nama Legal"), Path: "values.legal_name"},
			{Key: "party_kind", Label: "Kind", LabelI18n: localize("Kind", "Jenis"), Path: "values.party_kind"},
			{Key: "email", Label: "Email", LabelI18n: localize("Email", "Email"), Path: "values.email"},
			{Key: "phone", Label: "Phone", LabelI18n: localize("Phone", "Telepon"), Path: "values.phone"},
			{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status"},
		},
		Filters: []module.FilterDefinition{
			{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Type: "enum", Options: []string{"active", "inactive", "blocked"}},
			{Key: "party_kind", Label: "Kind", LabelI18n: localize("Kind", "Jenis"), Type: "enum", Options: []string{"organization", "person"}},
		},
		DefaultPageSize: 10,
		EmptyState:      "No parties registered yet.",
		EmptyStateI18n:  localize("No parties registered yet.", "Belum ada pihak terdaftar."),
	}
}

func masterdataPartyDetailView() module.ViewDefinition {
	return module.ViewDefinition{
		Key:                 "masterdata.parties.detail",
		Title:               "Party Detail",
		TitleI18n:           localize("Party Detail", "Detail Pihak"),
		Kind:                "detail",
		ModelKey:            "party",
		RequiredPermissions: []string{"party.read"},
		Tabs: []module.TabDefinition{{
			Key: "summary", Title: "Summary", TitleI18n: localize("Summary", "Ringkasan"), Sections: []module.SectionDefinition{{
				Key: "core", Title: "Core Fields", TitleI18n: localize("Core Fields", "Field Utama"), Fields: []module.FieldDefinition{
					{Key: "name", Label: "Name", LabelI18n: localize("Name", "Nama"), Path: "values.name", Type: "string"},
					{Key: "display_name", Label: "Display Name", LabelI18n: localize("Display Name", "Nama Tampil"), Path: "values.display_name", Type: "string"},
					{Key: "legal_name", Label: "Legal Name", LabelI18n: localize("Legal Name", "Nama Legal"), Path: "values.legal_name", Type: "string"},
					{Key: "party_kind", Label: "Party Kind", LabelI18n: localize("Party Kind", "Jenis Pihak"), Path: "values.party_kind", Type: "string"},
					{Key: "email", Label: "Email", LabelI18n: localize("Email", "Email"), Path: "values.email", Type: "string"},
					{Key: "phone", Label: "Phone", LabelI18n: localize("Phone", "Telepon"), Path: "values.phone", Type: "string"},
					{Key: "tax_identifier", Label: "Tax Identifier", LabelI18n: localize("Tax Identifier", "Nomor Pajak"), Path: "values.tax_identifier", Type: "string"},
					{Key: "currency_code", Label: "Currency", LabelI18n: localize("Currency", "Mata Uang"), Path: "values.currency_code", Type: "string"},
					{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status", Type: "string"},
				},
			}},
		}},
		RelatedViews: []module.RelatedViewDefinition{
			{Key: "timeline", Title: "Timeline", TitleI18n: localize("Timeline", "Linimasa"), Source: "timeline", EmptyState: "No activity yet", EmptyStateI18n: localize("No activity yet", "Belum ada aktivitas")},
			{Key: "contacts", Title: "Contacts", TitleI18n: localize("Contacts", "Kontak"), Source: "contacts", EmptyState: "No related contacts", EmptyStateI18n: localize("No related contacts", "Belum ada kontak terkait")},
			{Key: "addresses", Title: "Addresses", TitleI18n: localize("Addresses", "Alamat"), Source: "addresses", EmptyState: "No related addresses", EmptyStateI18n: localize("No related addresses", "Belum ada alamat terkait")},
			{Key: "customer_profiles", Title: "Customer Profiles", TitleI18n: localize("Customer Profiles", "Profil Pelanggan"), Source: "customer_profiles", EmptyState: "No related customer profiles", EmptyStateI18n: localize("No related customer profiles", "Belum ada profil pelanggan terkait")},
			{Key: "vendor_profiles", Title: "Vendor Profiles", TitleI18n: localize("Vendor Profiles", "Profil Vendor"), Source: "vendor_profiles", EmptyState: "No related vendor profiles", EmptyStateI18n: localize("No related vendor profiles", "Belum ada profil vendor terkait")},
		},
	}
}

func masterdataPartyFormView() module.ViewDefinition {
	return module.ViewDefinition{
		Key:                 "masterdata.parties.form",
		Title:               "Party Form",
		TitleI18n:           localize("Party Form", "Form Pihak"),
		Kind:                "form",
		ModelKey:            "party",
		RequiredPermissions: []string{"party.update"},
		Sections: []module.SectionDefinition{{
			Key: "edit", Title: "Edit Party", TitleI18n: localize("Edit Party", "Ubah Pihak"), Fields: []module.FieldDefinition{
				{Key: "name", Label: "Name", LabelI18n: localize("Name", "Nama"), Path: "values.name", Type: "string", Widget: "text", Required: true},
				{Key: "legal_name", Label: "Legal Name", LabelI18n: localize("Legal Name", "Nama Legal"), Path: "values.legal_name", Type: "string", Widget: "text"},
				{Key: "party_kind", Label: "Party Kind", LabelI18n: localize("Party Kind", "Jenis Pihak"), Path: "values.party_kind", Type: "string", Widget: "select", Options: []string{"organization", "person"}, Required: true},
				{Key: "email", Label: "Email", LabelI18n: localize("Email", "Email"), Path: "values.email", Type: "string", Widget: "text"},
				{Key: "phone", Label: "Phone", LabelI18n: localize("Phone", "Telepon"), Path: "values.phone", Type: "string", Widget: "text"},
				{Key: "tax_identifier", Label: "Tax Identifier", LabelI18n: localize("Tax Identifier", "Nomor Pajak"), Path: "values.tax_identifier", Type: "string", Widget: "text"},
				{Key: "currency_code", Label: "Currency", LabelI18n: localize("Currency", "Mata Uang"), Path: "values.currency_code", Type: "string", Widget: "text"},
				{Key: "customer_type", Label: "Legacy Customer Type", LabelI18n: localize("Legacy Customer Type", "Tipe Pelanggan Legacy"), Path: "values.customer_type", Type: "string", Widget: "text"},
				{Key: "member_status", Label: "Legacy Member Status", LabelI18n: localize("Legacy Member Status", "Status Member Legacy"), Path: "values.member_status", Type: "string", Widget: "text"},
				{Key: "member_tier", Label: "Legacy Member Tier", LabelI18n: localize("Legacy Member Tier", "Tier Member Legacy"), Path: "values.member_tier", Type: "string", Widget: "text"},
				{Key: "tax_profile_code", Label: "Legacy Tax Profile", LabelI18n: localize("Legacy Tax Profile", "Profil Pajak Legacy"), Path: "values.tax_profile_code", Type: "string", Widget: "select"},
				{Key: "default_price_list_code", Label: "Legacy Default Price List", LabelI18n: localize("Legacy Default Price List", "Daftar Harga Default Legacy"), Path: "values.default_price_list_code", Type: "string", Widget: "select"},
				{Key: "payment_term_days", Label: "Legacy Payment Term Days", LabelI18n: localize("Legacy Payment Term Days", "Hari Termin Pembayaran Legacy"), Path: "values.payment_term_days", Type: "number"},
				{Key: "status", Label: "Status", LabelI18n: localize("Status", "Status"), Path: "values.status", Type: "string", Widget: "select", Options: []string{"active", "inactive", "blocked"}},
			},
		}},
		RelatedViews: []module.RelatedViewDefinition{
			{Key: "contacts", Title: "Contacts", TitleI18n: localize("Contacts", "Kontak"), Source: "contacts", EmptyState: "No related contacts", EmptyStateI18n: localize("No related contacts", "Belum ada kontak terkait")},
			{Key: "addresses", Title: "Addresses", TitleI18n: localize("Addresses", "Alamat"), Source: "addresses", EmptyState: "No related addresses", EmptyStateI18n: localize("No related addresses", "Belum ada alamat terkait")},
		},
	}
}
